-- Initial stock belongs to one owned instance; using the property is confirmed by its owner.
UPDATE dndshare.item_type SET fields=fields || jsonb_build_array($field${"key": "initial_charges", "name": "Начальный запас зарядов", "type": "object", "fields": [{"key": "mode", "name": "Как определить запас", "type": "select", "options": [{"value": "fixed", "label": "Заданное число"}, {"value": "roll", "label": "Бросок костей"}]}, {"key": "value", "name": "Начальное число зарядов", "type": "int", "min": 0, "max": 100}, {"key": "formula", "name": "Формула начального запаса", "type": "text", "hint": "Бросок выполняется один раз при добавлении экземпляра, например 1к8+1."}]}$field$::jsonb)
WHERE id=19 AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(fields) f WHERE f->>'key'='initial_charges');

UPDATE dndshare.item_type SET fields=fields || jsonb_build_array($field${"key": "confirmed_uses", "name": "Применение по условию", "type": "object_array", "fields": [{"key": "title", "name": "Название свойства", "type": "text"}, {"key": "key", "name": "Ключ", "type": "text"}, {"key": "description", "name": "Что происходит", "type": "description", "hint": "Опишите эффект и спасбросок. Условия применения задайте отдельно."}, {"key": "requirements", "name": "Условия применения", "type": "text_array", "hint": "Каждое условие — отдельный тезис. Проверяет игрок, в том числе при бросках физических костей."}, {"key": "confirm_label", "name": "Когда списать ресурс", "type": "text", "hint": "Подпись кнопки подтверждения результата, например «Цель погибла». Расход не происходит при броске атаки."}, {"key": "resource_key", "name": "Ресурс экземпляра", "type": "text"}, {"key": "resource_cost", "name": "Сколько потратить", "type": "int", "default": 1, "min": 1, "max": 100}]}$field$::jsonb)
WHERE id=19 AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(fields) f WHERE f->>'key'='confirmed_uses');

UPDATE dndshare.item SET data=data || jsonb_build_object('initial_charges', COALESCE(data->'initial_charges', '{"mode":"roll","formula":"1к8+1"}'::jsonb),
 'confirmed_uses', COALESCE(data->'confirmed_uses','[]'::jsonb) || jsonb_build_array($use${"key": "life_stealing", "title": "Похищение жизни", "description": "<p>Цель совершает спасбросок Телосложения Сл 15. При провале она мгновенно погибает. Заряд расходуется только если цель погибла от этого свойства.</p>", "requirements": ["Критическое попадание этим оружием", "У цели меньше 100 хитов", "Цель не является конструктом или нежитью"], "confirm_label": "Цель погибла", "resource_cost": 1}$use$::jsonb))
WHERE id=134 AND name='Похититель девяти жизней' AND type_id=19 AND user_id IS NULL
 AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(data->'confirmed_uses','[]'::jsonb)) r WHERE r->>'key'='life_stealing');
