-- Editing contracts for the remaining fixed catalogues. Existing item data is unchanged.
WITH patches(type_id, fields) AS (VALUES
  (1, $fields$[{"key":"weight","name":"Вес, фнт.","type":"float"},{"key":"range_min","name":"Дистанция мин","type":"int","show_on":{"key":"tags","value":[1,4,6,11]}},{"key":"range_max","name":"Дистанция макс","type":"int","show_on":{"key":"tags","value":[1,4,6,11]}}]$fields$::jsonb),
  (2, $fields$[{"key":"rarity","name":"Редкость","type":"suggest","suggest_id":23,"filter":true},{"key":"type","name":"Подтип предмета","type":"text"},{"key":"weight","name":"Вес, фнт.","type":"float"},{"key":"unit_weight","name":"Вес единицы, фнт.","type":"float","show_on":{"key":"measurement","value":"length"}}]$fields$::jsonb),
  (5, $fields$[{"key":"concentration","name":"Требует концентрации","type":"bool"},{"key":"ritual","name":"Можно сотворить ритуалом","type":"bool"},{"name":"Урон","key":"damage","type":"object","fields":[{"name":"Дальнобойная атака","key":"range_attack","type":"boolean"},{"name":"Спасбросок (хар-ка)","key":"save_ability","type":"text"},{"name":"Спасбросок (эффект)","key":"save_effect","type":"text"},{"name":"Тип роста","key":"scaling","type":"text","default":"none","filter_values":["none","slot","cantrip"],"filter_labels":{"none":"нет","slot":"за круг ячейки","cantrip":"за уровень героя"}},{"name":"Снарядов/лучей","key":"instances","type":"int","default":1},{"name":"Снарядов за круг выше","key":"addon_instances","type":"int"},{"name":"Кубики (база)","key":"dices","type":"object_array","fields":[{"name":"Количество кубиков","key":"count","type":"int","default":1},{"name":"Кубик","key":"dice_id","type":"dice"},{"name":"Вид урона","key":"type","type":"suggest","suggest_id":12},{"name":"Бонус","key":"bonus","type":"int"}]},{"name":"Кубики (аддон за уровень)","key":"addon","type":"object_array","fields":[{"name":"Количество кубиков","key":"count","type":"int","default":1},{"name":"Кубик","key":"dice_id","type":"dice"},{"name":"Вид урона","key":"type","type":"suggest","suggest_id":12},{"name":"Бонус","key":"bonus","type":"int"}]}]},{"name":"Лечение","key":"heal","type":"object","fields":[{"name":"Плюс модификатор хар-ки","key":"add_mod","type":"bool"},{"name":"Тип роста","key":"scaling","type":"text","default":"none","filter_values":["none","slot","cantrip"],"filter_labels":{"none":"нет","slot":"за круг ячейки","cantrip":"за уровень героя"}},{"name":"Кубики (база)","key":"dices","type":"object_array","fields":[{"name":"Количество кубиков","key":"count","type":"int","default":1},{"name":"Кубик","key":"dice_id","type":"dice"}]},{"name":"Кубики (аддон за уровень)","key":"addon","type":"object_array","fields":[{"name":"Количество кубиков","key":"count","type":"int","default":1},{"name":"Кубик","key":"dice_id","type":"dice"}]}]}]$fields$::jsonb),
  (8, $fields$[{"key":"asi_choice","name":"Характеристики на выбор","type":"object","fields":[{"key":"count","name":"Сколько характеристик","type":"int","default":1},{"key":"bonus","name":"Бонус каждой","type":"int","default":1}]},{"key":"lang_choice","name":"Языки на выбор","type":"object","fields":[{"key":"count","name":"Сколько выбрать","type":"int","default":1},{"key":"from","name":"Доступные варианты","type":"suggest_array","suggest_id":6}]},{"key":"skill_choice","name":"Навыки на выбор","type":"object","fields":[{"key":"count","name":"Сколько выбрать","type":"int","default":1},{"key":"from","name":"Доступные варианты","type":"suggest_array","suggest_id":15}]},{"key":"feat_choice","name":"Черта на выбор","type":"object","fields":[{"key":"count","name":"Сколько выбрать","type":"int","default":1}]},{"key":"variants","name":"Варианты расы","type":"object_array","fields":[{"key":"label","name":"Название варианта","type":"text"},{"key":"value","name":"Ключ","type":"text"},{"key":"desc","name":"Краткое описание","type":"text"},{"key":"asi","name":"Бонусы характеристик","type":"object_array","fields":[{"key":"ability","name":"Характеристика","type":"suggest","suggest_id":16},{"key":"bonus","name":"Бонус","type":"int","default":1}]},{"key":"asi_choice","name":"Характеристики на выбор","type":"object","fields":[{"key":"count","name":"Сколько характеристик","type":"int","default":1},{"key":"bonus","name":"Бонус каждой","type":"int","default":1}]},{"key":"lang_choice","name":"Языки на выбор","type":"object","fields":[{"key":"count","name":"Сколько выбрать","type":"int","default":1},{"key":"from","name":"Доступные варианты","type":"suggest_array","suggest_id":6}]},{"key":"skill_choice","name":"Навыки на выбор","type":"object","fields":[{"key":"count","name":"Сколько выбрать","type":"int","default":1},{"key":"from","name":"Доступные варианты","type":"suggest_array","suggest_id":15}]},{"key":"feat_choice","name":"Черта на выбор","type":"object","fields":[{"key":"count","name":"Сколько выбрать","type":"int","default":1}]}]}]$fields$::jsonb),
  (9, $fields$[{"key":"caster_progression","name":"Рост ячеек заклинаний","type":"select","options":[{"label":"Полный заклинатель","value":"full"},{"label":"Половина уровня","value":"half"},{"label":"Половина с округлением вверх","value":"halfup"},{"label":"Треть уровня","value":"third"},{"label":"Магия договора","value":"pact"}]}]$fields$::jsonb),
  (10, $fields$[{"key":"weight","name":"Вес, фнт.","type":"float"}]$fields$::jsonb),
  (11, $fields$[{"key":"tool_items","name":"Инструменты справочника","type":"object_array","fields":[{"key":"item_id","name":"Предмет","type":"item","item_type":14},{"key":"count","name":"Количество","type":"int","default":1},{"key":"params","name":"Параметры экземпляра","type":"object","fields":[{"key":"length_ft","name":"Длина, фт.","type":"int"},{"key":"magic_bonus","name":"Магический бонус","type":"int"}]}]},{"key":"equipment_items","name":"Стартовое снаряжение справочника","type":"object_array","fields":[{"key":"item_id","name":"Предмет","type":"item","item_type":2},{"key":"count","name":"Количество","type":"int","default":1},{"key":"params","name":"Параметры экземпляра","type":"object","fields":[{"key":"length_ft","name":"Длина, фт.","type":"int"},{"key":"magic_bonus","name":"Магический бонус","type":"int"}]}]},{"key":"item_choices","name":"Выборы предметов предыстории","type":"object_array","fields":[{"key":"key","name":"Ключ","type":"text"},{"key":"label","name":"Название","type":"text"},{"key":"option_item_ids","name":"Варианты снаряжения","type":"item_array","item_type":2},{"key":"grants_tool_proficiency","name":"Даёт владение инструментом","type":"boolean"},{"key":"grants_tool_item","name":"Показывать среди инструментов","type":"boolean"},{"key":"grants_equipment_item","name":"Выдавать в снаряжение","type":"boolean"},{"key":"replace_tool_prof_id","name":"Заменяет владение","type":"suggest","suggest_id":5},{"key":"replace_tool_item_id","name":"Заменяет инструмент","type":"item","item_type":14},{"key":"replace_equipment_item_id","name":"Заменяет предмет","type":"item","item_type":2}]}]$fields$::jsonb),
  (12, $fields$[{"key":"weight","name":"Вес, фнт.","type":"float"}]$fields$::jsonb),
  (13, $fields$[{"key":"weight","name":"Вес, фнт.","type":"float"}]$fields$::jsonb),
  (14, $fields$[{"key":"rarity","name":"Редкость","type":"suggest","suggest_id":23,"filter":true},{"key":"is_container","name":"Контейнер","type":"bool"},{"key":"type","name":"Подтип инструмента","type":"text"},{"key":"weight","name":"Вес, фнт.","type":"float"}]$fields$::jsonb),
  (15, $fields$[{"key":"code","name":"Ключ эффекта","type":"text"},{"key":"max_level","name":"Максимальная ступень","type":"int"}]$fields$::jsonb),
  (16, $fields$[{"key":"asi_choice","name":"Характеристики на выбор","type":"object","fields":[{"key":"count","name":"Сколько характеристик","type":"int","default":1},{"key":"bonus","name":"Бонус каждой","type":"int","default":1}]},{"key":"lang_choice","name":"Языки на выбор","type":"object","fields":[{"key":"count","name":"Сколько выбрать","type":"int","default":1},{"key":"from","name":"Доступные варианты","type":"suggest_array","suggest_id":6}]},{"key":"skill_choice","name":"Навыки на выбор","type":"object","fields":[{"key":"count","name":"Сколько выбрать","type":"int","default":1},{"key":"from","name":"Доступные варианты","type":"suggest_array","suggest_id":15}]},{"key":"feat_choice","name":"Черта на выбор","type":"object","fields":[{"key":"count","name":"Сколько выбрать","type":"int","default":1}]}]$fields$::jsonb),
  (17, $fields$[{"key":"caster_progression","name":"Рост ячеек заклинаний","type":"select","options":[{"label":"Полный заклинатель","value":"full"},{"label":"Половина уровня","value":"half"},{"label":"Половина с округлением вверх","value":"halfup"},{"label":"Треть уровня","value":"third"},{"label":"Магия договора","value":"pact"}]}]$fields$::jsonb)
)
UPDATE dndshare.item_type t
SET fields = (
  SELECT jsonb_agg(COALESCE(original.field, '{}'::jsonb) || COALESCE(patch.field, '{}'::jsonb) ORDER BY COALESCE(original.ord, 10000 + patch.ord))
  FROM jsonb_array_elements(t.fields) WITH ORDINALITY original(field, ord)
  FULL JOIN jsonb_array_elements(p.fields) WITH ORDINALITY patch(field, ord) ON original.field->>'key' = patch.field->>'key'
)
FROM patches p WHERE t.id = p.type_id;
