-- Magic items retain their identity and inventory links. Mechanics use the ability contract.
INSERT INTO dndshare.item_type (id, name, parent_type_id, source_id, color, important, description, icon_image_id, cover_image_id)
SELECT 19, 'Магические предметы', 2, source_id, '#a78bfa', true,
       'Магическое снаряжение: свойства, настройка, заряды и зависимости на листе персонажа.', icon_image_id, cover_image_id
FROM dndshare.item_type WHERE id=2;

UPDATE dndshare.item_type SET fields =
  COALESCE((SELECT jsonb_agg(f ORDER BY n) FROM dndshare.item_type, jsonb_array_elements(fields) WITH ORDINALITY a(f,n) WHERE id=2 AND f->>'key'<>'type'), '[]'::jsonb)
  || $properties$[{"key":"type","name":"Вид предмета","type":"select","filter":true,"options":[{"value":"чудесный предмет","label":"Чудесный предмет"},{"value":"броня","label":"Броня"},{"value":"оружие","label":"Оружие"},{"value":"кольцо","label":"Кольцо"},{"value":"жезл","label":"Жезл"},{"value":"посох","label":"Посох"},{"value":"волшебная палочка","label":"Волшебная палочка"},{"value":"свиток","label":"Свиток"}]},{"key":"attunement","name":"Настройка на предмет","type":"select","default":"none","filter":true,"hint":"Настройка отмечается отдельно для каждого экземпляра в инвентаре. Требования проверяет игрок с мастером.","options":[{"value":"none","label":"Не требуется"},{"value":"required","label":"Требуется"},{"value":"unknown","label":"Нужно уточнить"}]},{"key":"attunement_requirement","name":"Кто может настроиться","type":"text","hint":"Например: заклинатель, паладин или существо доброго мировоззрения.","show_on":{"key":"attunement","value":"required"}},{"key":"activation","name":"Когда действуют свойства","type":"select","default":"equipped","hint":"Влияет на автоматические бонусы, действия и заклинания на листе. Настройка, если нужна, проверяется дополнительно.","options":[{"value":"equipped","label":"Когда экипирован / в руках"},{"value":"carried","label":"Пока находится в инвентаре"}]},{"key":"recharge_note","name":"Особое восстановление зарядов","type":"text","hint":"Например: на рассвете восстановить 1к6 + 1. Такие заряды меняются вручную; отдых не заменяет рассвет."}]$properties$::jsonb
  || COALESCE((SELECT jsonb_agg(f ORDER BY n) FROM dndshare.item_type, jsonb_array_elements(fields) WITH ORDINALITY a(f,n) WHERE id=12 AND f->>'key' IN ('category','required_armor_proficiency','strength_required','stealth_disadvantage')), '[]'::jsonb)
  || COALESCE((SELECT jsonb_agg(f ORDER BY n) FROM dndshare.item_type, jsonb_array_elements(fields) WITH ORDINALITY a(f,n) WHERE id=4 AND f->>'key' NOT IN ('desc','race_ids','subrace_ids','class_ids','subclass_ids')), '[]'::jsonb)
WHERE id=19;

-- Audited against SRD 5.1 (2014), Magic Items. These are explicit public item IDs,
-- not a rarity heuristic: mundane gear has rarity=0, as does the common spell scroll.
WITH audited(id, expected_name, properties) AS (VALUES
  (75, 'Складная лодка', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (76, 'Талисман абсолютного добра', '{"type":"чудесный предмет","attunement":"required","activation":"equipped","attunement_requirement":"Существо доброго мировоззрения"}'::jsonb),
  (77, 'Рог Валгаллы', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (78, 'Щит притяжения снарядов', '{"type":"броня","attunement":"required","activation":"equipped"}'::jsonb),
  (79, 'Суверенный клей', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (80, 'Элементальный самоцвет', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (81, 'Кольцо управления элементалями', '{"type":"кольцо","attunement":"required","activation":"equipped"}'::jsonb),
  (82, 'Сфера драконьего рода', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (83, 'Шлем понимания языков', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (85, 'Танцующий меч', '{"type":"оружие","attunement":"required","activation":"equipped"}'::jsonb),
  (86, 'Посох иссушения', '{"type":"посох","attunement":"required","activation":"equipped","attunement_requirement":"Жрец, друид или колдун"}'::jsonb),
  (87, 'Свиток заклинания', '{"type":"свиток","attunement":"none","activation":"carried","consumable":true}'::jsonb),
  (88, 'Посох грома и молнии', '{"type":"посох","attunement":"required","activation":"equipped"}'::jsonb),
  (89, 'Бусина силы', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (90, 'Жезл владычьей мощи', '{"type":"жезл","attunement":"required","activation":"equipped"}'::jsonb),
  (91, 'Фонарь обнаружения', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (92, 'Щит +1', '{"type":"броня","attunement":"none","activation":"equipped","category":"shield","armor":{"shield":true,"shield_bonus":3}}'::jsonb),
  (93, 'Амулет здоровья', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (94, 'Боеприпасы', '{"type":"оружие","attunement":"none","activation":"equipped"}'::jsonb),
  (95, 'Волшебная палочка огненных шаров', '{"type":"волшебная палочка","attunement":"required","activation":"equipped","attunement_requirement":"Заклинатель","max_use":7,"recharge_note":"На рассвете восстановить 1к6 + 1 заряда (не больше 7). При расходе последнего заряда бросить к20: на 1 палочка уничтожается.","feature_actions":[{"key":"fireball","title":"Огненный шар из палочки","action_type":"action","uses_resource":true,"resource_cost":1,"description":"<p>За 1 заряд: огненный шар 3-го уровня, Сл спасброска 15. Каждый дополнительный заряд повышает уровень на 1; спишите дополнительные заряды вручную. Заклинание и риск уничтожения палочки описаны в предмете.</p>"}]}'::jsonb),
  (96, 'Мгновенная крепость', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (97, 'Шляпа маскировки', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (98, 'Талисман сферы', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (100, 'Кольцо влияния на животных', '{"type":"кольцо","attunement":"none","activation":"equipped"}'::jsonb),
  (101, 'Очки орла', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (102, 'Медальон мыслей', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (103, 'Плащ защиты', '{"type":"чудесный предмет","attunement":"required","activation":"equipped","derived_effects":[{"kind":"armor_bonus","value":1,"label":"Защита +1"},{"kind":"save_bonus","value":1,"label":"Спасброски +1"}]}'::jsonb),
  (104, 'Святой мститель', '{"type":"оружие","attunement":"required","activation":"equipped","attunement_requirement":"Паладин"}'::jsonb),
  (105, 'Том ясной мысли', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (106, 'Зеркало ловли жизни', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (107, 'Брошь защиты', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (108, 'Посох лечения', '{"type":"посох","attunement":"required","activation":"equipped","attunement_requirement":"Бард, жрец или друид"}'::jsonb),
  (110, 'Боеприпасы', '{"type":"оружие","attunement":"none","activation":"equipped"}'::jsonb),
  (111, 'Камень Иoun', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (112, 'Щит +2', '{"type":"броня","attunement":"none","activation":"equipped","category":"shield","armor":{"shield":true,"shield_bonus":4}}'::jsonb),
  (113, 'Эльфийская кольчуга', '{"type":"броня","attunement":"none","activation":"equipped"}'::jsonb),
  (114, 'Доспех из драконьей чешуи', '{"type":"броня","attunement":"required","activation":"equipped"}'::jsonb),
  (116, 'Переносная дыра', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (117, 'Щит защиты от заклинаний', '{"type":"броня","attunement":"required","activation":"equipped"}'::jsonb),
  (118, 'Железная фляга', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (119, 'Волшебная палочка обнаружения магии', '{"type":"волшебная палочка","attunement":"none","activation":"equipped"}'::jsonb),
  (121, 'Рог Валгаллы', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (122, 'Одеяние звёзд', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (124, 'Куб силы', '{"type":"чудесный предмет","attunement":"required","activation":"carried"}'::jsonb),
  (125, 'Амулет планов', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (126, 'Кольцо плавания', '{"type":"кольцо","attunement":"none","activation":"equipped"}'::jsonb),
  (127, 'Сумка фокусов', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (128, 'Колода многих вещей', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (129, 'Свиток заклинания', '{"type":"свиток","attunement":"none","activation":"carried","consumable":true}'::jsonb),
  (130, 'Фигурка чудесной силы', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (131, 'Посох огня', '{"type":"посох","attunement":"required","activation":"equipped","attunement_requirement":"Друид, чародей, колдун или волшебник"}'::jsonb),
  (132, 'Посох очарования', '{"type":"посох","attunement":"required","activation":"equipped","attunement_requirement":"Бард, жрец, друид, чародей, колдун или волшебник"}'::jsonb),
  (134, 'Похититель девяти жизней', '{"type":"оружие","attunement":"required","activation":"equipped"}'::jsonb),
  (135, 'Мантия сопротивления заклинаниям', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (136, 'Пламенный язык', '{"type":"оружие","attunement":"required","activation":"equipped"}'::jsonb),
  (137, 'Булава сокрушения', '{"type":"оружие","attunement":"none","activation":"equipped"}'::jsonb),
  (138, 'Жезл поглощения', '{"type":"жезл","attunement":"required","activation":"equipped"}'::jsonb),
  (139, 'Одеяние архимага', '{"type":"чудесный предмет","attunement":"required","activation":"equipped","attunement_requirement":"Чародей, колдун или волшебник"}'::jsonb),
  (140, 'Повязка интеллекта', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (141, 'Амулет защиты от обнаружения и поиска', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (142, 'Крылатые сапоги', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (144, 'Кольцо сопротивления', '{"type":"кольцо","attunement":"required","activation":"equipped"}'::jsonb),
  (145, 'Камень удачи', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (146, 'Сапоги эльфийской поступи', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (147, 'Жемчужина силы', '{"type":"чудесный предмет","attunement":"required","activation":"equipped","attunement_requirement":"Заклинатель"}'::jsonb),
  (148, 'Морозная марка', '{"type":"оружие","attunement":"required","activation":"equipped"}'::jsonb),
  (149, 'Кинжал яда', '{"type":"оружие","attunement":"none","activation":"equipped"}'::jsonb),
  (150, 'Самоцвет яркости', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (151, 'Жезл бдительности', '{"type":"жезл","attunement":"required","activation":"equipped"}'::jsonb),
  (152, 'Руководство по големам', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (153, 'Волшебная палочка боевого мага', '{"type":"волшебная палочка","attunement":"required","activation":"equipped","attunement_requirement":"Заклинатель"}'::jsonb),
  (154, 'Сумка хранения', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (155, 'Доспех неуязвимости', '{"type":"броня","attunement":"required","activation":"equipped"}'::jsonb),
  (156, 'Пыль чихания и удушья', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (157, 'Оружие', '{"type":"оружие","attunement":"none","activation":"equipped"}'::jsonb),
  (158, 'Перчатки плавания и лазания', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (159, 'Волшебная палочка волшебных стрел', '{"type":"волшебная палочка","attunement":"none","activation":"equipped"}'::jsonb),
  (160, 'Меч остроты', '{"type":"оружие","attunement":"required","activation":"equipped"}'::jsonb),
  (161, 'Волшебная палочка связывания', '{"type":"волшебная палочка","attunement":"required","activation":"equipped","attunement_requirement":"Заклинатель"}'::jsonb),
  (162, 'Бутылка ифрита', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (164, 'Посох силы', '{"type":"посох","attunement":"required","activation":"equipped","attunement_requirement":"Чародей, колдун или волшебник"}'::jsonb),
  (165, 'Амулет защиты от яда', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (166, 'Пояс силы великана', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (168, 'Посох лесов', '{"type":"посох","attunement":"required","activation":"equipped","attunement_requirement":"Друид"}'::jsonb),
  (169, 'Посох питона', '{"type":"посох","attunement":"required","activation":"equipped","attunement_requirement":"Жрец, друид или колдун"}'::jsonb),
  (170, 'Щит ловли стрел', '{"type":"броня","attunement":"required","activation":"equipped"}'::jsonb),
  (171, 'Клинок удачи', '{"type":"оружие","attunement":"required","activation":"equipped"}'::jsonb),
  (172, 'Подковы зефира', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (173, 'Сапоги левитации', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (174, 'Кольцо невидимости', '{"type":"кольцо","attunement":"required","activation":"equipped"}'::jsonb),
  (175, 'Кольцо телекинеза', '{"type":"кольцо","attunement":"required","activation":"equipped"}'::jsonb),
  (176, 'Посох роя насекомых', '{"type":"посох","attunement":"required","activation":"equipped","attunement_requirement":"Бард, жрец, друид, чародей, колдун или волшебник"}'::jsonb),
  (177, 'Плащ паукообразного', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (178, 'Трезубец управления рыбами', '{"type":"оружие","attunement":"required","activation":"equipped"}'::jsonb),
  (179, 'Обруч взрыва', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (180, 'Кольцо свободы действий', '{"type":"кольцо","attunement":"required","activation":"equipped"}'::jsonb),
  (181, 'Кольцо призыва джинна', '{"type":"кольцо","attunement":"required","activation":"equipped"}'::jsonb),
  (182, 'Убийца великанов', '{"type":"оружие","attunement":"none","activation":"equipped"}'::jsonb),
  (184, 'Доспех', '{"type":"броня","attunement":"none","activation":"equipped"}'::jsonb),
  (185, 'Сумка пожирания', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (186, 'Шлем сияния', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (187, 'Доспех уязвимости', '{"type":"броня","attunement":"required","activation":"equipped"}'::jsonb),
  (188, 'Талисман абсолютного зла', '{"type":"чудесный предмет","attunement":"required","activation":"equipped","attunement_requirement":"Существо злого мировоззрения"}'::jsonb),
  (189, 'Посох ударов', '{"type":"посох","attunement":"required","activation":"equipped"}'::jsonb),
  (190, 'Булава разрушения', '{"type":"оружие","attunement":"required","activation":"equipped"}'::jsonb),
  (191, 'Ожерелье молитвенных бусин', '{"type":"чудесный предмет","attunement":"required","activation":"equipped","attunement_requirement":"Жрец, друид или паладин"}'::jsonb),
  (192, 'Ковёр-самолёт', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (193, 'Скарабей защиты', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (194, 'Том лидерства и влияния', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (195, 'Подковы скорости', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (196, 'Сапоги ходьбы и прыжков', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (197, 'Молот громовых ударов', '{"type":"оружие","attunement":"required","activation":"equipped","attunement_requirement":"Носить пояс силы великана и рукавицы силы огра. Снятие любого из них прекращает настройку."}'::jsonb),
  (198, 'Ворпальный меч', '{"type":"оружие","attunement":"required","activation":"equipped"}'::jsonb),
  (199, 'Верёвка опутывания', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (200, 'Топор берсерка', '{"type":"оружие","attunement":"required","activation":"equipped"}'::jsonb),
  (201, 'Рукавицы силы огра', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (202, 'Лук клятвы', '{"type":"оружие","attunement":"required","activation":"equipped"}'::jsonb),
  (204, 'Сфера аннигиляции', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (205, 'Плащ эльфийского рода', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (206, 'Колодец многих миров', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (207, 'Чудесные краски', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (208, 'Крылья полёта', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (210, 'Руководство телесного здоровья', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (211, 'Доспех', '{"type":"броня","attunement":"none","activation":"equipped"}'::jsonb),
  (212, 'Меч ранения', '{"type":"оружие","attunement":"required","activation":"equipped"}'::jsonb),
  (213, 'Ожерелье адаптации', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (214, 'Волшебная палочка страха', '{"type":"волшебная палочка","attunement":"required","activation":"equipped"}'::jsonb),
  (216, 'Ожерелье огненных шаров', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (217, 'Аппарат краба', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (218, 'Верёвка лазания', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (219, 'Веер ветра', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (220, 'Восстанавливающая мазь', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (222, 'Мифриловый доспех', '{"type":"броня","attunement":"none","activation":"equipped"}'::jsonb),
  (223, 'Оружие', '{"type":"оружие","attunement":"none","activation":"equipped"}'::jsonb),
  (224, 'Перчатки ловли снарядов', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (225, 'Графин бесконечной воды', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (226, 'Перьевой талисман', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (227, 'Пояс силы великана', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (228, 'Доспех сопротивления', '{"type":"броня","attunement":"required","activation":"equipped"}'::jsonb),
  (229, 'Плащ ската манта', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (230, 'Волшебная палочка секретов', '{"type":"волшебная палочка","attunement":"none","activation":"equipped"}'::jsonb),
  (231, 'Очки детального зрения', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (232, 'Адамантиновый доспех', '{"type":"броня","attunement":"none","activation":"equipped"}'::jsonb),
  (233, 'Защитник', '{"type":"оружие","attunement":"required","activation":"equipped"}'::jsonb),
  (234, 'Том понимания', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (235, 'Волшебная палочка паутины', '{"type":"волшебная палочка","attunement":"required","activation":"equipped","attunement_requirement":"Заклинатель"}'::jsonb),
  (236, 'Волшебная палочка боевого мага', '{"type":"волшебная палочка","attunement":"required","activation":"equipped","attunement_requirement":"Заклинатель"}'::jsonb),
  (237, 'Камень управления земляными элементалями', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (238, 'Кольцо трёх желаний', '{"type":"кольцо","attunement":"none","activation":"carried"}'::jsonb),
  (240, 'Стрела убийства', '{"type":"оружие","attunement":"none","activation":"equipped"}'::jsonb),
  (241, 'Амулет здоровья', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (242, 'Хрустальный шар', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (243, 'Очки ночи', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (244, 'Волшебная палочка паралича', '{"type":"волшебная палочка","attunement":"required","activation":"equipped","attunement_requirement":"Заклинатель"}'::jsonb),
  (245, 'Пояс силы великана', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (246, 'Волшебная палочка боевого мага', '{"type":"волшебная палочка","attunement":"required","activation":"equipped","attunement_requirement":"Заклинатель"}'::jsonb),
  (247, 'Одеяние мерцающих цветов', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (249, 'Посох магов', '{"type":"посох","attunement":"required","activation":"equipped","attunement_requirement":"Чародей, колдун или волшебник"}'::jsonb),
  (250, 'Волшебная палочка молний', '{"type":"волшебная палочка","attunement":"required","activation":"equipped","attunement_requirement":"Заклинатель"}'::jsonb),
  (251, 'Рог разрушения', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (252, 'Кольцо хранения заклинаний', '{"type":"кольцо","attunement":"required","activation":"equipped"}'::jsonb),
  (253, 'Кольцо рентгеновского зрения', '{"type":"кольцо","attunement":"required","activation":"equipped"}'::jsonb),
  (254, 'Хрустальный шар', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (255, 'Кольцо уклонения', '{"type":"кольцо","attunement":"required","activation":"equipped"}'::jsonb),
  (256, 'Шлем телепатии', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (257, 'Одеяние глаз', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (258, 'Оружие', '{"type":"оружие","attunement":"none","activation":"equipped"}'::jsonb),
  (259, 'Пыль исчезновения', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (260, 'Волшебная палочка обнаружения врагов', '{"type":"волшебная палочка","attunement":"required","activation":"equipped"}'::jsonb),
  (261, 'Дварфийский метатель', '{"type":"оружие","attunement":"required","activation":"equipped","attunement_requirement":"Дварф"}'::jsonb),
  (262, 'Демонический доспех', '{"type":"броня","attunement":"required","activation":"equipped"}'::jsonb),
  (263, 'Солнечный клинок', '{"type":"оружие","attunement":"required","activation":"equipped"}'::jsonb),
  (264, 'Шлем телепортации', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (265, 'Свиток заклинания', '{"type":"свиток","attunement":"none","activation":"carried","consumable":true}'::jsonb),
  (266, 'Доспех', '{"type":"броня","attunement":"none","activation":"equipped"}'::jsonb),
  (267, 'Плащ смещения', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (268, 'Плащ шарлатана', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (269, 'Метла полёта', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (270, 'Сапоги зимних земель', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (271, 'Чаша управления водными элементалями', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (272, 'Кольцо хождения по воде', '{"type":"кольцо","attunement":"none","activation":"equipped"}'::jsonb),
  (273, 'Булава ужаса', '{"type":"оружие","attunement":"required","activation":"equipped"}'::jsonb),
  (274, 'Вечнодымящаяся бутылка', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (275, 'Кольцо отражения заклинаний', '{"type":"кольцо","attunement":"required","activation":"equipped"}'::jsonb),
  (276, 'Эффективный колчан', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (277, 'Кольцо защиты разума', '{"type":"кольцо","attunement":"required","activation":"equipped"}'::jsonb),
  (278, 'Кольцо падающих звёзд', '{"type":"кольцо","attunement":"required","activation":"equipped","attunement_requirement":"Настройка на открытом воздухе ночью"}'::jsonb),
  (279, 'Волшебная палочка превращения', '{"type":"волшебная палочка","attunement":"required","activation":"equipped","attunement_requirement":"Заклинатель"}'::jsonb),
  (280, 'Колода иллюзий', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (281, 'Рог Валгаллы', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (282, 'Кадило управления воздушными элементалями', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (283, 'Очки очарования', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (284, 'Метательное копьё молнии', '{"type":"оружие","attunement":"none","activation":"equipped"}'::jsonb),
  (286, 'Жестокое оружие', '{"type":"оружие","attunement":"none","activation":"equipped"}'::jsonb),
  (287, 'Свиток заклинания', '{"type":"свиток","attunement":"none","activation":"carried","consumable":true}'::jsonb),
  (288, 'Фигурка чудесной силы', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (289, 'Латы эфирности', '{"type":"броня","attunement":"required","activation":"equipped"}'::jsonb),
  (290, 'Пояс дварфийского рода', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (291, 'Туфли паучьего лазания', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (292, 'Руководство полезных упражнений', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (293, 'Меч похищения жизни', '{"type":"оружие","attunement":"required","activation":"equipped"}'::jsonb),
  (295, 'Руководство быстроты действий', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (296, 'Кольцо плавного падения', '{"type":"кольцо","attunement":"required","activation":"equipped"}'::jsonb),
  (297, 'Посох мороза', '{"type":"посох","attunement":"required","activation":"equipped","attunement_requirement":"Друид, чародей, колдун или волшебник"}'::jsonb),
  (298, 'Жезл безопасности', '{"type":"жезл","attunement":"none","activation":"equipped"}'::jsonb),
  (299, 'Кубические врата', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (301, 'Железные ленты сковывания', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (303, 'Удобный рюкзак', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (304, 'Щит +3', '{"type":"броня","attunement":"none","activation":"equipped","category":"shield","armor":{"shield":true,"shield_bonus":5}}'::jsonb),
  (305, 'Свирели страха', '{"type":"чудесный предмет","attunement":"none","activation":"equipped"}'::jsonb),
  (306, 'Универсальный растворитель', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (307, 'Камень Иoun', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (308, 'Пыль сухости', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (309, 'Амулет затягивания ран', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (310, 'Сумка бобов', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (312, 'Наручи стрельбы из лука', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (313, 'Боеприпасы', '{"type":"оружие","attunement":"none","activation":"equipped"}'::jsonb),
  (314, 'Кольцо прыжков', '{"type":"кольцо","attunement":"required","activation":"equipped"}'::jsonb),
  (315, 'Свирели канализации', '{"type":"чудесный предмет","attunement":"required","activation":"carried"}'::jsonb),
  (317, 'Камень Иoun', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (318, 'Сапоги скорости', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (319, 'Плащ летучей мыши', '{"type":"чудесный предмет","attunement":"required","activation":"equipped"}'::jsonb),
  (320, 'Жаровня управления огненными элементалями', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (321, 'Убийца драконов', '{"type":"оружие","attunement":"none","activation":"equipped"}'::jsonb),
  (323, 'Свеча призыва', '{"type":"чудесный предмет","attunement":"required","activation":"carried"}'::jsonb),
  (324, 'Волшебная палочка чудес', '{"type":"волшебная палочка","attunement":"required","activation":"equipped","attunement_requirement":"Заклинатель"}'::jsonb),
  (325, 'Скимитар скорости', '{"type":"оружие","attunement":"required","activation":"equipped"}'::jsonb),
  (326, 'Одеяние полезных предметов', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (327, 'Колокольчик открывания', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (330, 'Кольцо тепла', '{"type":"кольцо","attunement":"required","activation":"equipped"}'::jsonb),
  (331, 'Кольцо регенерации', '{"type":"кольцо","attunement":"required","activation":"equipped"}'::jsonb),
  (332, 'Оживлённый щит', '{"type":"броня","attunement":"required","activation":"equipped"}'::jsonb),
  (333, 'Кольцо тарана', '{"type":"кольцо","attunement":"required","activation":"equipped"}'::jsonb),
  (334, 'Наручи защиты', '{"type":"чудесный предмет","attunement":"required","activation":"equipped","derived_effects":[{"kind":"armor_bonus","value":2,"requires_no_armor":true,"allow_shield":false,"label":"Наручи защиты"}]}'::jsonb),
  (335, 'Свиток заклинания', '{"type":"свиток","attunement":"none","activation":"carried","consumable":true}'::jsonb),
  (336, 'Фигурка чудесной силы', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (337, 'Самоцвет зрения', '{"type":"чудесный предмет","attunement":"required","activation":"carried"}'::jsonb),
  (338, 'Дварфийские латы', '{"type":"броня","attunement":"none","activation":"equipped"}'::jsonb),
  (339, 'Иллюзорный клёпаный кожаный доспех', '{"type":"броня","attunement":"none","activation":"equipped"}'::jsonb),
  (340, 'Неподвижный жезл', '{"type":"жезл","attunement":"none","activation":"carried"}'::jsonb),
  (341, 'Жезл власти', '{"type":"жезл","attunement":"required","activation":"equipped"}'::jsonb),
  (342, 'Кольцо защиты', '{"type":"кольцо","attunement":"required","activation":"equipped","derived_effects":[{"kind":"armor_bonus","value":1,"label":"Защита +1"},{"kind":"save_bonus","value":1,"label":"Спасброски +1"}]}'::jsonb),
  (343, 'Межпространственные кандалы', '{"type":"чудесный предмет","attunement":"none","activation":"carried"}'::jsonb),
  (1423, 'Кожанная броня (+1)', '{"type":"броня","attunement":"none","activation":"equipped","rarity":2,"category":"light","armor":{"ac":12,"use_dex":true}}'::jsonb)
)
UPDATE dndshare.item i SET type_id=19, data=i.data::jsonb || a.properties
FROM audited a WHERE i.id=a.id AND i.name=a.expected_name AND i.type_id=2 AND i.user_id IS NULL;

UPDATE dndshare.item_type t SET count_items=(SELECT count(*) FROM dndshare.item i WHERE i.type_id=t.id AND i.user_id IS NULL) WHERE t.id IN (2,19);
SELECT setval(pg_get_serial_sequence('dndshare.item_type','id'), GREATEST(19,(SELECT max(id) FROM dndshare.item_type)), true);

-- Resolve proficiency by semantic name, not deployment-specific suggest IDs.
UPDATE dndshare.item i SET data=jsonb_set(i.data, '{required_armor_proficiency}', to_jsonb(s.id), true)
FROM dndshare.suggest s
WHERE i.type_id=19 AND i.user_id IS NULL AND i.id IN (92,112,304,1423)
AND s.type_id=3 AND s.user_id IS NULL
AND lower(s.value)=CASE WHEN i.id=1423 THEN lower('Лёгкие доспехи') ELSE lower('Щиты') END;

-- Each magical object has its own attunement and charges. Expand existing stacks
-- once while preserving item IDs, total quantity, placement and instance params.
CREATE FUNCTION dndshare.split_magic_item_stack(entries jsonb) RETURNS jsonb LANGUAGE sql AS $split$
  SELECT COALESCE(jsonb_agg(CASE WHEN i.id IS NULL THEN e ELSE
    e || jsonb_build_object('count',1,'uid',COALESCE(e->>'uid','magic-' || md5(e::text)) || CASE WHEN copy=1 THEN '' ELSE '-magic-' || copy::text END) END ORDER BY ord,copy), '[]'::jsonb)
  FROM jsonb_array_elements(CASE WHEN jsonb_typeof(entries)='array' THEN entries ELSE '[]'::jsonb END) WITH ORDINALITY rows(e,ord)
  LEFT JOIN dndshare.item i ON i.type_id=19 AND i.id::text=e->>'item_id'
  CROSS JOIN LATERAL generate_series(1, CASE WHEN i.id IS NOT NULL THEN GREATEST(1,COALESCE((e->>'count')::int,1)) ELSE 1 END) copy;
$split$;
UPDATE dndshare.char c SET data=jsonb_set(c.data,'{values,items}',
  (c.data#>'{values,items}') || jsonb_build_object(
    'equipped',dndshare.split_magic_item_stack(c.data#>'{values,items,equipped}'),
    'sections',COALESCE((SELECT jsonb_agg(s || jsonb_build_object('items',dndshare.split_magic_item_stack(s->'items')) ORDER BY ord)
      FROM jsonb_array_elements(COALESCE(c.data#>'{values,items,sections}','[]'::jsonb)) WITH ORDINALITY rows(s,ord)), '[]'::jsonb)))
WHERE jsonb_typeof(c.data#>'{values,items}')='object'
  AND EXISTS (SELECT 1 FROM jsonb_path_query(c.data#>'{values,items}', '$.**.item_id') refs(item_id) JOIN dndshare.item i ON i.id::text=refs.item_id#>>'{}' AND i.type_id=19);
DROP FUNCTION dndshare.split_magic_item_stack(jsonb);
