-- Equipment is a capability of a magic item, not a duplicate catalogue entry.
UPDATE dndshare.item_type SET fields=fields || '[{"key": "treasure", "name": "Участвует в генераторе сокровищ", "type": "object", "optional": true, "hint": "Включайте только предметы, которые мастер может получить случайным подбором. Не влияет на стартовый магазин.", "fields": [{"key": "weight", "name": "Вес выпадения", "type": "int", "min": 1, "max": 1000, "default": 10, "required": true, "hint": "Относительный вес среди подходящих предметов: 20 выпадает вдвое чаще 10. Это не процент."}, {"key": "min_level", "name": "С уровня группы", "type": "int", "min": 1, "max": 20, "default": 1, "required": true}, {"key": "max_level", "name": "До уровня группы", "type": "int", "min": 1, "max": 20, "default": 20, "required": true}]}]'::jsonb WHERE id IN (1,2,10,12,13,14,19);

UPDATE dndshare.item_type SET fields=fields || '[{"key": "weapon", "name": "Используется как оружие", "type": "object", "optional": true, "hint": "Экипированный предмет появится в оружии. Основа задаёт урон и владение; магические зависимости остаются у этого экземпляра.", "fields": [{"key": "base_item_id", "name": "Фиксированная основа", "type": "item", "item_type": 1, "hint": "Выберите, если предмет всегда имеет один вид: например, кинжал. Пусто — игрок выбирает основу экземпляра."}, {"key": "allowed_base_item_ids", "name": "Допустимые основы на выбор", "type": "item_array", "item_type": 1, "hint": "Пустой список разрешает любой вид оружия. Показывается, если фиксированная основа не задана."}, {"key": "magic_bonus", "name": "Бонус к атаке и урону", "type": "int", "min": 0, "max": 3, "default": 0, "hint": "Прибавка только этого оружия. Не нужно повторять её в зависимостях."}, {"key": "bonus_without_attunement", "name": "Бонус действует без настройки", "type": "bool", "hint": "Отметьте только если правило предмета отдельно разрешает этот бонус до настройки."}, {"key": "damage_type", "name": "Заменить основной тип урона", "type": "suggest", "suggest_id": 12, "optional": true}, {"key": "extra_tags", "name": "Добавить свойства оружия", "type": "suggest_array", "suggest_id": 14, "optional": true}, {"key": "extra_proficiencies", "name": "Дополнительные владения", "type": "suggest_array", "suggest_id": 4, "optional": true}, {"key": "range_min", "name": "Изменить обычную дистанцию, фт.", "type": "int", "min": 0, "optional": true}, {"key": "range_max", "name": "Изменить предельную дистанцию, фт.", "type": "int", "min": 0, "optional": true}]}]'::jsonb WHERE id IN (19);

UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 0, "allowed_base_item_ids": [48, 49, 50, 51, 1457]}}'::jsonb WHERE id=85 AND type_id=19 AND user_id IS NULL AND name='Танцующий меч';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 0, "base_item_id": 37}}'::jsonb WHERE id=86 AND type_id=19 AND user_id IS NULL AND name='Посох иссушения';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 2, "base_item_id": 37}}'::jsonb WHERE id=88 AND type_id=19 AND user_id IS NULL AND name='Посох грома и молнии';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 3, "allowed_base_item_ids": [48, 49, 50, 51, 1457]}}'::jsonb WHERE id=104 AND type_id=19 AND user_id IS NULL AND name='Святой мститель';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 0, "base_item_id": 37}}'::jsonb WHERE id=108 AND type_id=19 AND user_id IS NULL AND name='Посох лечения';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 0, "base_item_id": 37}}'::jsonb WHERE id=131 AND type_id=19 AND user_id IS NULL AND name='Посох огня';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 0, "base_item_id": 37}}'::jsonb WHERE id=132 AND type_id=19 AND user_id IS NULL AND name='Посох очарования';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 2, "allowed_base_item_ids": [48, 49, 50, 51, 1457]}}'::jsonb WHERE id=134 AND type_id=19 AND user_id IS NULL AND name='Похититель девяти жизней';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 0, "allowed_base_item_ids": [48, 49, 50, 51, 1457]}}'::jsonb WHERE id=136 AND type_id=19 AND user_id IS NULL AND name='Пламенный язык';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 1, "base_item_id": 1447}}'::jsonb WHERE id=137 AND type_id=19 AND user_id IS NULL AND name='Булава сокрушения';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 0, "allowed_base_item_ids": [48, 49, 50, 51, 1457]}}'::jsonb WHERE id=148 AND type_id=19 AND user_id IS NULL AND name='Морозная марка';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 1, "base_item_id": 36}}'::jsonb WHERE id=149 AND type_id=19 AND user_id IS NULL AND name='Кинжал яда';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 3}}'::jsonb WHERE id=157 AND type_id=19 AND user_id IS NULL AND name='Оружие';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 0, "allowed_base_item_ids": [48, 49, 1457]}}'::jsonb WHERE id=160 AND type_id=19 AND user_id IS NULL AND name='Меч остроты';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 2, "base_item_id": 37}}'::jsonb WHERE id=164 AND type_id=19 AND user_id IS NULL AND name='Посох силы';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 2, "base_item_id": 37}}'::jsonb WHERE id=168 AND type_id=19 AND user_id IS NULL AND name='Посох лесов';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 0, "base_item_id": 37}}'::jsonb WHERE id=169 AND type_id=19 AND user_id IS NULL AND name='Посох питона';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 1, "allowed_base_item_ids": [48, 49, 50, 51, 1457]}}'::jsonb WHERE id=171 AND type_id=19 AND user_id IS NULL AND name='Клинок удачи';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 0, "base_item_id": 37}}'::jsonb WHERE id=176 AND type_id=19 AND user_id IS NULL AND name='Посох роя насекомых';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 0, "base_item_id": 58}}'::jsonb WHERE id=178 AND type_id=19 AND user_id IS NULL AND name='Трезубец управления рыбами';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 1, "allowed_base_item_ids": [46, 1450, 1456, 48, 49, 50, 51, 1457]}}'::jsonb WHERE id=182 AND type_id=19 AND user_id IS NULL AND name='Убийца великанов';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 3, "base_item_id": 37}}'::jsonb WHERE id=189 AND type_id=19 AND user_id IS NULL AND name='Посох ударов';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 0, "base_item_id": 1447}}'::jsonb WHERE id=190 AND type_id=19 AND user_id IS NULL AND name='Булава разрушения';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 1, "base_item_id": 1455, "bonus_without_attunement": true}}'::jsonb WHERE id=197 AND type_id=19 AND user_id IS NULL AND name='Молот громовых ударов';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 3, "allowed_base_item_ids": [48, 49, 1457]}}'::jsonb WHERE id=198 AND type_id=19 AND user_id IS NULL AND name='Ворпальный меч';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 1, "allowed_base_item_ids": [46, 1450, 1456]}}'::jsonb WHERE id=200 AND type_id=19 AND user_id IS NULL AND name='Топор берсерка';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 0, "base_item_id": 61}}'::jsonb WHERE id=202 AND type_id=19 AND user_id IS NULL AND name='Лук клятвы';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 0, "allowed_base_item_ids": [48, 49, 50, 51, 1457]}}'::jsonb WHERE id=212 AND type_id=19 AND user_id IS NULL AND name='Меч ранения';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 1}}'::jsonb WHERE id=223 AND type_id=19 AND user_id IS NULL AND name='Оружие';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 3, "allowed_base_item_ids": [48, 49, 50, 51, 1457]}}'::jsonb WHERE id=233 AND type_id=19 AND user_id IS NULL AND name='Защитник';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 2, "base_item_id": 37}}'::jsonb WHERE id=249 AND type_id=19 AND user_id IS NULL AND name='Посох магов';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 2}}'::jsonb WHERE id=258 AND type_id=19 AND user_id IS NULL AND name='Оружие';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 3, "base_item_id": 53, "extra_tags": [6], "range_min": 20, "range_max": 60}}'::jsonb WHERE id=261 AND type_id=19 AND user_id IS NULL AND name='Дварфийский метатель';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 2, "base_item_id": 49, "damage_type": 7, "extra_tags": [11], "extra_proficiencies": [17]}}'::jsonb WHERE id=263 AND type_id=19 AND user_id IS NULL AND name='Солнечный клинок';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 0, "base_item_id": 1447}}'::jsonb WHERE id=273 AND type_id=19 AND user_id IS NULL AND name='Булава ужаса';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 0, "base_item_id": 1448}}'::jsonb WHERE id=284 AND type_id=19 AND user_id IS NULL AND name='Метательное копьё молнии';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 0}}'::jsonb WHERE id=286 AND type_id=19 AND user_id IS NULL AND name='Жестокое оружие';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 0, "allowed_base_item_ids": [48, 49, 50, 51, 1457]}}'::jsonb WHERE id=293 AND type_id=19 AND user_id IS NULL AND name='Меч похищения жизни';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 0, "base_item_id": 37}}'::jsonb WHERE id=297 AND type_id=19 AND user_id IS NULL AND name='Посох мороза';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 1, "allowed_base_item_ids": [48, 49, 50, 51, 1457]}}'::jsonb WHERE id=321 AND type_id=19 AND user_id IS NULL AND name='Убийца драконов';
UPDATE dndshare.item SET data=data || '{"weapon": {"magic_bonus": 2, "base_item_id": 1457}}'::jsonb WHERE id=325 AND type_id=19 AND user_id IS NULL AND name='Скимитар скорости';

-- Initial editorial pool. Level bands and weights are application presets, not DMG tables.
-- Existing personal items opt in explicitly; artifacts and vehicles are not random defaults.
UPDATE dndshare.item SET data=data || jsonb_build_object('treasure',jsonb_build_object(
 'weight',CASE WHEN type_id=19 OR type_id=10 THEN CASE COALESCE(data->>'rarity','0') WHEN '0' THEN 20 WHEN '1' THEN 10 WHEN '2' THEN 4 WHEN '3' THEN 2 ELSE 1 END ELSE 10 END,
 'min_level',CASE WHEN type_id=19 OR type_id=10 THEN CASE COALESCE(data->>'rarity','0') WHEN '2' THEN 5 WHEN '3' THEN 11 WHEN '4' THEN 17 ELSE 1 END ELSE 1 END,'max_level',20))
WHERE user_id IS NULL AND ((type_id IN (19,10) AND COALESCE(data->>'rarity','0') IN ('0','1','2','3','4'))
 OR (type_id IN (1,2,12,14) AND data->>'available_in_starting_shop'='true'));
