package web

func mcpToolDefs() []map[string]any {

	defs := []map[string]any{
		mcpDefinition("sessions_list",
			"List active sessions owned by one exact user login. Returns session metadata without participants or character sheets.",
			mcpObjectSchema(map[string]any{"ownerLogin": mcpStringProperty("Exact owner login")}, "ownerLogin")),
		mcpDefinition("session_adventure_get",
			"Read the complete authored campaign projection for one session owned by the supplied login: arcs, chapters, scenarios, blocks, world entities, materials and graph edges. Does not expose participants or character sheets.",
			mcpObjectSchema(map[string]any{
				"ownerLogin":  mcpStringProperty("Exact owner login"),
				"sessionUuid": mcpStringProperty("Session UUID"),
			}, "ownerLogin", "sessionUuid")),
		mcpDefinition("session_adventure_import",
			"Atomically create a session and import a portable adventure for one existing user. The document is a JSON string with stable local keys for arcs, chapters, scenarios, blocks, locations, NPCs, quests, text/note materials and their edges/relations. System catalogue images are selected by imageKey. Any invalid reference rolls back the whole session. Requires MCP write operations to be enabled.",
			mcpObjectSchema(map[string]any{
				"ownerLogin": mcpStringProperty("Exact existing user login that will own the session"),
				"document":   mcpStringProperty("Portable SessionAdventureDocument encoded as one JSON object string"),
			}, "ownerLogin", "document")),
		mcpDefinition("handbook_sources",
			"List handbook systems. Returns id, name, versions [{id, sourceId, version}], countItems.",
			mcpObjectSchema(map[string]any{})),
		mcpDefinition("handbook_item_types",
			"List item types (handbook object categories such as enemies, weapons). Each type's `fields` array describes handbook item `data`; `instanceFields` describes typed `params` stored on owned or granted item references. Read this before creating or updating items.",
			mcpObjectSchema(map[string]any{"sourceId": mcpIntegerProperty("Optional source id to filter by")})),
		mcpDefinition("handbook_items",
			"List base (shared) items of a given type, paginated.",
			mcpObjectSchema(map[string]any{
				"typeId": mcpIntegerProperty("Item type id"),
				"limit":  mcpIntegerProperty("Max rows, 1..500 (default 50)"),
				"offset": mcpIntegerProperty("Offset for pagination (default 0)"),
			}, "typeId")),
		mcpDefinition("handbook_items_search",
			"Search base (shared) items of a type by Russian or English name/nameEn (case-insensitive substring).",
			mcpObjectSchema(map[string]any{
				"typeId": mcpIntegerProperty("Item type id"),
				"q":      mcpStringProperty("Name query"),
				"limit":  mcpIntegerProperty("Max rows, 1..500 (default 20)"),
			}, "typeId", "q")),
		mcpDefinition("handbook_items_get",
			"Fetch items by their ids (any owner).",
			mcpObjectSchema(map[string]any{
				"ids": map[string]any{"type": "array", "items": map[string]any{"type": "integer"}, "description": "Item ids"},
			}, "ids")),
		mcpDefinition("handbook_suggest_types",
			"List suggest types (dictionary categories). Returns id, name, source, color, countItems.",
			mcpObjectSchema(map[string]any{"sourceId": mcpIntegerProperty("Optional source id to filter by")})),
		mcpDefinition("handbook_suggests",
			"List base (shared) suggests (dictionary values) of a given type.",
			mcpObjectSchema(map[string]any{"typeId": mcpIntegerProperty("Suggest type id")}, "typeId")),
		mcpDefinition("handbook_suggests_search",
			"Search base (shared) suggests across all types by value (case-insensitive substring).",
			mcpObjectSchema(map[string]any{
				"q":     mcpStringProperty("Value query"),
				"limit": mcpIntegerProperty("Max rows, 1..100 (default 20)"),
			}, "q")),
		mcpDefinition("handbook_item_create",
			"Create a base (shared, user_id=null) item. Use handbook_item_types first to learn the `data` schema for the given typeId.",
			mcpObjectSchema(map[string]any{
				"compatibility":             itemCompatibilityToolSchema(),
				"derivedFromItemId":         mcpIntegerProperty("Original item of the same type; use with derivationKind"),
				"derivationKind":            map[string]any{"type": "string", "enum": []string{"revision", "adaptation"}},
				"automationStatus":          map[string]any{"type": "string", "enum": []string{"unreviewed", "full", "partial", "none", "not_applicable"}, "description": "Site mechanics coverage; omitted on update preserves status. Explicit review, never infer from dependency count."},
				"automationNote":            mcpStringProperty("Optional explanation of coverage or limitations, up to 1000 characters. Empty string clears it."),
				"hidden":                    map[string]any{"type": "boolean", "description": "Hide from catalogue lists, search and character creation. Direct ID reads remain available. Omitted on update preserves visibility."},
				"requiresPlayerInteraction": map[string]any{"type": "boolean", "description": "Requires another player's character; independent of coverage status."},
				"typeId":                    mcpIntegerProperty("Item type id"),
				"name":                      mcpStringProperty("Display name (Russian)"),
				"nameEn":                    mcpStringProperty("English name"),
				"data":                      mcpStringProperty("JSON object string with the item data matching the type's fields schema"),
				"parentId":                  mcpIntegerProperty("Normalized parent item id for a type-16 subrace or type-17 subclass. The server keeps data.race/data.class and the reverse base-item list synchronized. Omit for base items."),
			}, "typeId", "name", "nameEn", "data")),
		mcpDefinition("handbook_item_update",
			"Update an item by id (admin: works for any owner including base items).",
			mcpObjectSchema(map[string]any{
				"compatibility":             itemCompatibilityToolSchema(),
				"derivedFromItemId":         mcpIntegerProperty("Original item of the same type; use with derivationKind"),
				"derivationKind":            map[string]any{"type": "string", "enum": []string{"revision", "adaptation"}},
				"automationStatus":          map[string]any{"type": "string", "enum": []string{"unreviewed", "full", "partial", "none", "not_applicable"}, "description": "Site mechanics coverage; omitted on update preserves status. Explicit review, never infer from dependency count."},
				"automationNote":            mcpStringProperty("Optional explanation of coverage or limitations, up to 1000 characters. Empty string clears it."),
				"hidden":                    map[string]any{"type": "boolean", "description": "Hide from catalogue lists, search and character creation. Direct ID reads remain available. Omitted on update preserves visibility."},
				"requiresPlayerInteraction": map[string]any{"type": "boolean", "description": "Requires another player's character; independent of coverage status."},
				"id":                        mcpIntegerProperty("Item id"),
				"name":                      mcpStringProperty("Display name (Russian)"),
				"nameEn":                    mcpStringProperty("English name"),
				"data":                      mcpStringProperty("JSON object string with the full item data"),
				"parentId":                  mcpIntegerProperty("Normalized parent item id. Pass -1 to clear only for item types that allow it; type-16 subraces and type-17 subclasses require a base parent. Omit to derive/keep the origin relation from data.race or data.class."),
			}, "id", "name", "data")),
		mcpDefinition("handbook_item_set_content_sources",
			"Set the handbook book/source links of an item. Replaces only source links, preserves item data.",
			mcpObjectSchema(map[string]any{
				"id":               mcpIntegerProperty("Item id"),
				"contentSourceIds": map[string]any{"type": "array", "items": map[string]any{"type": "integer"}},
			}, "id", "contentSourceIds")),
		mcpDefinition("handbook_item_delete",
			"Delete an item by id (admin: works for any owner including base items).",
			mcpObjectSchema(map[string]any{"id": mcpIntegerProperty("Item id")}, "id")),
		mcpDefinition("handbook_item_reuse_icon", "Assign the exact same icon image/SVG ID from another system item. Does not copy files or inherit future changes. Both items must be public system entries; source must have an icon.", mcpObjectSchema(map[string]any{"itemId": mcpIntegerProperty("Target system item"), "sourceItemId": mcpIntegerProperty("System item whose icon to reuse")}, "itemId", "sourceItemId")),
		mcpDefinition("handbook_item_set_system_image",
			"Upload and assign an icon or cover to a base system handbook item. Accepts plain standard base64, stores the image in S3 under a content-addressed key, and replaces the selected slot. By default an unreferenced previous asset is removed; preservePrevious=true keeps its storage row and S3 object for later reuse. Icons allow PNG/WebP up to 5 MB; covers allow JPEG/PNG/WebP up to 10 MB. Requires MCP write operations to be enabled and never changes user-owned items.",
			mcpObjectSchema(map[string]any{
				"itemId":           mcpIntegerProperty("Positive id of a base system item (user_id must be null)"),
				"slot":             map[string]any{"type": "string", "enum": []string{"icon", "cover"}, "description": "Image slot"},
				"fileName":         mcpStringProperty("Original file name stored as metadata"),
				"mimeType":         mcpStringProperty("Exact image MIME type matching the bytes"),
				"dataBase64":       mcpStringProperty("Plain standard base64 without a data URL prefix"),
				"preservePrevious": mcpBooleanProperty("Keep the replaced storage row and S3 object instead of deleting an unreferenced asset (default false)"),
			}, "itemId", "slot", "fileName", "mimeType", "dataBase64")),
		mcpDefinition("handbook_item_type_set_system_image",
			"Upload and assign an icon or fallback cover to a handbook item type. Item-level media keeps priority over the type fallback. Accepts plain standard base64, stores the image in S3 under a content-addressed key, and replaces the selected slot. By default an unreferenced previous asset is removed; preservePrevious=true keeps it. Icons allow PNG/WebP up to 5 MB; covers allow JPEG/PNG/WebP up to 10 MB. Requires MCP write operations to be enabled.",
			mcpObjectSchema(map[string]any{
				"typeId":           mcpIntegerProperty("Positive handbook item type id"),
				"slot":             map[string]any{"type": "string", "enum": []string{"icon", "cover"}, "description": "Image slot"},
				"fileName":         mcpStringProperty("Original file name stored as metadata"),
				"mimeType":         mcpStringProperty("Exact image MIME type matching the bytes"),
				"dataBase64":       mcpStringProperty("Plain standard base64 without a data URL prefix"),
				"preservePrevious": mcpBooleanProperty("Keep the replaced storage row and S3 object instead of deleting an unreferenced asset (default false)"),
			}, "typeId", "slot", "fileName", "mimeType", "dataBase64")),
		mcpDefinition("handbook_bestiary_migrate_icons_to_covers",
			"Audit or migrate legacy raster icons of base bestiary items into their cover slot without uploading or deleting S3 objects. Existing covers are never overwritten. Pass kobold or other protected item ids in excludeItemIds. The default apply=false is a dry-run; apply=true requires MCP write operations and an expectedCandidateCount equal to the preceding dry-run result.",
			mcpObjectSchema(map[string]any{
				"excludeItemIds":         map[string]any{"type": "array", "items": map[string]any{"type": "integer"}, "description": "Base bestiary item ids to leave unchanged (default empty)"},
				"apply":                  mcpBooleanProperty("Apply the migration; default false performs a dry-run"),
				"expectedCandidateCount": mcpIntegerProperty("Required with apply=true; must match candidateCount from the latest dry-run"),
			})),
		mcpDefinition("handbook_suggest_create",
			"Create a base (shared, user_id=null) suggest in the given type.",
			mcpObjectSchema(map[string]any{
				"typeId": mcpIntegerProperty("Suggest type id"),
				"value":  mcpStringProperty("Display value"),
				"code":   mcpStringProperty("Optional code/key"),
				"color":  mcpStringProperty("Optional hex color"),
				"desc":   mcpStringProperty("Optional description/tooltip"),
			}, "typeId", "value")),
		mcpDefinition("handbook_suggest_update",
			"Update a suggest by id+typeId (admin: works for any owner including base). Preserves the existing svg icon.",
			mcpObjectSchema(map[string]any{
				"typeId": mcpIntegerProperty("Suggest type id"),
				"id":     mcpIntegerProperty("Suggest id"),
				"value":  mcpStringProperty("Display value"),
				"code":   mcpStringProperty("Optional code/key"),
				"color":  mcpStringProperty("Optional hex color"),
				"desc":   mcpStringProperty("Optional description/tooltip"),
			}, "typeId", "id", "value")),
		mcpDefinition("handbook_suggest_set_svg",
			"Set or replace the svg icon of a suggest by id+typeId (admin: works for any owner including base). Pass raw <svg> markup; an empty string clears the icon. Stores the markup in svg_storage, repoints the suggest, and removes the previous svg row.",
			mcpObjectSchema(map[string]any{
				"typeId": mcpIntegerProperty("Suggest type id"),
				"id":     mcpIntegerProperty("Suggest id"),
				"svg":    mcpStringProperty("Raw SVG markup (e.g. <svg ...>...</svg>); empty string clears the icon"),
			}, "typeId", "id", "svg")),
		mcpDefinition("handbook_suggest_delete",
			"Delete a suggest by id+typeId (admin: works for any owner including base).",
			mcpObjectSchema(map[string]any{
				"typeId": mcpIntegerProperty("Suggest type id"),
				"id":     mcpIntegerProperty("Suggest id"),
			}, "typeId", "id")),
	}
	for _, definition := range defs {
		if name := definition["name"]; name == "handbook_items" || name == "handbook_items_search" || name == "handbook_item_types" {
			properties := definition["inputSchema"].(map[string]any)["properties"].(map[string]any)
			properties["sourceVersionId"] = mcpIntegerProperty("Rules edition; omitted lists every edition")
			properties["allowLegacy"] = mcpBooleanProperty("Include browse-only legacy and requires_adaptation records")
			properties["contentSourceIds"] = map[string]any{"type": "array", "items": map[string]any{"type": "integer"}, "description": "Selected publications; omitted means all"}
		}
	}
	return append(defs, compatibilityBatchDefinition(), editionImportDefinition())

}
