import { expect, test } from '@playwright/test'

for (const mobile of [false, true]) test(`karmic settings and long character name ${mobile ? 'mobile' : 'desktop'}`, async ({ page }) => {
  page.on('pageerror', error => { throw error })
  await page.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1400, height: 1000 })
  await page.goto('/tests/tutorials/fixtures/karmic-dice.html')
  const name = page.getByTestId('long-name')
  const text = await name.locator('.input-text-view').boundingBox(), pencil = await name.getByRole('button', { name: 'Редактировать', exact: true }).boundingBox()
  expect(pencil.y).toBeGreaterThanOrEqual(text.y + text.height)
  expect(await name.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await name.getByRole('button', { name: 'Редактировать', exact: true }).click()
  await expect(name.locator('input')).toBeFocused()
  await name.locator('input').fill('Короткое имя')
  await name.locator('input').press('Tab')
  await expect(name.locator('.input-text-view')).toHaveText('Короткое имя')
  const enabled = page.getByRole('switch', { name: 'Кармические кубы', exact: true })
  await expect(enabled).not.toBeChecked()
  await expect(page.getByRole('figure', { name: 'Распределение вероятностей d20: Общая шкала', exact: true })).toBeVisible()
  await expect(page.locator('.distribution-extremes').first()).toContainText('5%')
  await enabled.click()
  await expect(enabled).toBeChecked()
  await expect(page.getByRole('meter')).toHaveAttribute('aria-valuenow', '0')
  await page.getByRole('button', { name: 'Бросить атаку', exact: true }).click()
  await expect(page.getByRole('meter')).toHaveAttribute('aria-valuenow', '0.7', { timeout: 6000 })
  await expect(page.getByRole('meter')).toHaveAttribute('aria-valuetext', 'К высоким · 0,7 из 6')
  await page.getByRole('combobox', { name: 'Шкала кармических кубов', exact: true }).click()
  await page.getByRole('option', { name: 'Для каждого своя', exact: true }).click()
  await expect(page.getByRole('meter')).toHaveCount(0)
  await page.getByRole('button', { name: 'Бросить атаку', exact: true }).click()
  await expect(page.getByRole('meter', { name: 'Сдвиг вероятности: Герой', exact: true })).toHaveAttribute('aria-valuenow', '0.7', { timeout: 6000 })
  const avatar = page.locator('.karmic-scale .transfer-person img')
  await expect(avatar).toBeVisible()
  const avatarBox = await avatar.boundingBox(), meterBox = await page.getByRole('meter').boundingBox()
  expect(avatarBox.x + avatarBox.width).toBeLessThan(meterBox.x)
  expect(await avatar.evaluate(el => el.naturalWidth)).toBeGreaterThan(0)
  await page.evaluate(() => { window.failedRead = true })
  await expect(page.getByRole('alert')).toContainText('Не удалось обновить шкалы', { timeout: 6000 })
  await expect(page.getByRole('meter')).toHaveCount(0)
  await page.evaluate(() => { window.failedRead = false })
  await page.getByRole('button', { name: 'Повторить', exact: true }).click()
  await expect(page.getByRole('meter')).toBeVisible()
  await enabled.click()
  expect(await page.evaluate(() => window.requests.filter(row => row.key).map(row => [row.key, row.value]))).toEqual([
    ['karmicDice.enabled', true], ['karmicDice.separate', true], ['karmicDice.enabled', false],
  ])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

for (const mobile of [false, true]) test(`d20 probability chart supports extremes and keyboard ${mobile ? 'mobile' : 'desktop'}`, async ({ page }) => {
  page.on('pageerror', error => { throw error })
  await page.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1400, height: 1000 })
  await page.goto('/tests/tutorials/fixtures/karmic-dice.html')
  await page.getByRole('switch', { name: 'Кармические кубы', exact: true }).click()
  await page.evaluate(() => { window.scales = [{ key: 'shared', name: 'Общая шкала', balance: 6 }] })
  await expect(page.getByRole('meter')).toHaveAttribute('aria-valuenow', '6', { timeout: 6000 })
  const figure = page.getByRole('figure', { name: 'Распределение вероятностей d20: Общая шкала', exact: true })
  await expect(figure.locator('.distribution-bars rect')).toHaveCount(20)
  await expect(figure.locator('.distribution-extremes')).toContainText('0,75%')
  await expect(figure.locator('.distribution-extremes')).toContainText('9,25%')
  const plot = figure.locator('svg')
  await plot.focus()
  await page.keyboard.press('Home')
  await expect(figure.locator('output')).toHaveText('1 · 0,75%')
  await page.keyboard.press('End')
  await expect(figure.locator('output')).toHaveText('20 · 9,25%')
  await page.keyboard.press('ArrowLeft')
  await expect(figure.locator('output')).toContainText('19')
  const heights = await figure.locator('.distribution-bars rect').evaluateAll(rows => rows.map(row => Number(row.getAttribute('height'))))
  expect(heights.every(height => height > 0)).toBe(true)
  expect(heights[19]).toBeGreaterThan(heights[0])
  await page.evaluate(() => { window.scales = [{ key: 'shared', name: 'Общая шкала', balance: -6 }] })
  await expect(page.getByRole('meter')).toHaveAttribute('aria-valuenow', '-6', { timeout: 6000 })
  await page.keyboard.press('Home')
  await expect(figure.locator('output')).toHaveText('1 · 9,25%')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
