import { test, expect } from '@playwright/test'

for (const mobile of [false, true]) {
  test(`money display integrates currency and flashes real balance changes (${mobile ? 'mobile' : 'desktop'})`, async ({ page }) => {
    page.on('pageerror', error => { throw error })
    await page.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1280, height: 1000 })
    await page.goto('/tests/tutorials/fixtures/money-calculator.html')
    await expect(page.locator('.money-amount--gain, .money-amount--spend')).toHaveCount(0)
    await page.locator('.money-tile').click()
    const editor = page.locator('.mes-editor')
    const preview = page.locator('.mes-view')
    const selector = editor.getByRole('combobox', { name: 'Валюта калькулятора' })
    const display = editor.locator('.cp-display')
    await expect(display.getByRole('combobox')).toBeVisible()
    const [selectorBox, displayBox, expressionBox, backspaceBox] = await Promise.all([
      selector.boundingBox(), display.boundingBox(), editor.locator('.cp-expr').boundingBox(), editor.getByRole('button', { name: 'Удалить последнюю цифру' }).boundingBox(),
    ])
    expect(selectorBox.x).toBeGreaterThanOrEqual(displayBox.x)
    expect(selectorBox.x + selectorBox.width).toBeLessThan(expressionBox.x)
    expect(displayBox.x + displayBox.width).toBeLessThan(backspaceBox.x)

    await selector.click()
    await page.getByRole('option', { name: 'мм', exact: true }).click()
    await editor.getByRole('button', { name: '5', exact: true }).click()
    await editor.getByRole('button', { name: 'Взять', exact: true }).click()
    let coin = preview.locator('[data-money-id="1"]')
    await expect(coin.locator('.ma-value')).toHaveText('15')
    await expect(coin).toHaveClass(/money-amount--gain/)
    await expect(coin.locator('.ma-change')).toHaveText('+5')
    expect(await coin.evaluate(el => getComputedStyle(el).animationName)).toContain('money-balance-pulse')
    await expect(coin).not.toHaveClass(/money-amount--gain/)

    await editor.getByRole('button', { name: '1', exact: true }).click()
    await editor.getByRole('button', { name: '5', exact: true }).click()
    await editor.getByRole('button', { name: 'Дать', exact: true }).click()
    await expect(coin.locator('.ma-value')).toHaveText('0')
    await expect(coin).toHaveClass(/money-amount--spend/)
    await expect(coin.locator('.ma-change')).toHaveText('−15')
    await expect(coin).toHaveCount(0)

    // Rejected spending must keep both the balance and preview unchanged.
    await editor.getByRole('button', { name: '1', exact: true }).click()
    await editor.getByRole('button', { name: 'Дать', exact: true }).click()
    await expect(editor.locator('.mc-error')).toBeVisible()
    expect(await page.evaluate(() => window.writes.length)).toBe(2)
    await expect(preview.locator('.money-amount--spend, .money-amount--gain')).toHaveCount(0)

    // Keyboard choice changes the currency without applying the expression.
    await selector.focus()
    await page.keyboard.press('ArrowDown')
    await page.keyboard.press('ArrowDown')
    await page.keyboard.press('Enter')
    await expect(selector).toContainText('см')
    expect(await page.evaluate(() => window.writes.length)).toBe(2)
    await editor.getByRole('button', { name: 'Взять', exact: true }).click()
    coin = preview.locator('[data-money-id="2"]')
    await expect(coin.locator('.ma-value')).toHaveText('1')
    await expect(coin).toHaveClass(/money-amount--gain/)
    const firstAnimation = await coin.evaluate(el => { window.firstMoneyAnimation = el.getAnimations()[0]; return !!window.firstMoneyAnimation })
    expect(firstAnimation).toBe(true)
    await editor.getByRole('button', { name: '2', exact: true }).click()
    await editor.getByRole('button', { name: 'Взять', exact: true }).click()
    await expect(coin.locator('.ma-value')).toHaveText('3')
    expect(await coin.evaluate(el => el.getAnimations()[0] !== window.firstMoneyAnimation)).toBe(true)
    expect(await page.evaluate(() => window.writes.length)).toBe(4)
    await page.keyboard.press('Escape')
    await expect(editor).toHaveCount(0)
    await expect(page.locator('.money-tile [data-money-id="2"] .ma-value')).toHaveText('3')

    const plain = page.getByTestId('plain-calculator')
    await expect(plain.locator('.cp-display-leading')).toHaveCount(0)
    await plain.getByRole('button', { name: '7', exact: true }).click()
    await plain.getByRole('button', { name: 'Удалить последнюю цифру' }).click()
    await expect(plain.locator('.cp-expr')).toHaveText('0')
  })
}

test('read-only balances update with static color feedback for reduced motion', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/tests/tutorials/fixtures/money-calculator.html?readonly')
  await page.locator('.money-tile').click()
  await expect(page.locator('.mes-editor')).toHaveCount(0)
  await page.evaluate(() => { window.moneyState.money.amounts[1] += 7 })
  const coin = page.locator('[data-money-id="1"]')
  await expect(coin.locator('.ma-value')).toHaveText('17')
  await expect(coin).toHaveClass(/money-amount--gain/)
  await expect(coin).toHaveCSS('animation-name', 'none')
  await expect(coin).toHaveCSS('transform', 'none')
  await expect(coin.locator('.ma-change')).toHaveText('+7')
  expect(await page.evaluate(() => window.writes)).toEqual([])
})
