import { test, expect } from '@playwright/test'
for (const mobile of [false, true]) test(`shared morph heading and independent aside on ${mobile ? 'mobile' : 'desktop'}`, async ({ page }) => {
  page.on('pageerror', error => { throw error })
  await page.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1400, height: 1000 })
  await page.goto('/tests/tutorials/fixtures/stat-rolls.html')
  await page.getByRole('button', { name: 'Ловкость — спасбросок', exact: true }).click()
  await expect(page.getByRole('menu')).toBeVisible()
  await expect(page.locator('.mes-editor')).toHaveCount(0)
  await page.keyboard.press('Escape')
  const heading = page.getByRole('button', { name: 'Редактировать: Ловкость', exact: true })
  await heading.focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('.mes-editor')).toBeVisible()
  await expect(page.locator('.mes-view .morph-tile-header')).toBeVisible()
  await expect(page.locator('.mes-view .morph-tile-heading')).toBeDisabled()
  await page.keyboard.press('Escape')
  await expect(page.locator('.mes-editor')).toHaveCount(0)
  expect(await page.evaluate(() => window.writes)).toEqual([])
})
