import { test, expect } from '@playwright/test'
for (const mobile of [false, true]) test(`participant menu and Ctrl selection ${mobile ? 'mobile' : 'desktop'}`, async ({ page }) => {
  page.on('pageerror', error => { throw error })
  await page.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1200, height: 900 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/tests/tutorials/fixtures/participant-controls.html')
  const card = page.locator('.p-card')
  await expect(card).not.toContainText('Эльф')
  await expect(card).not.toContainText('Плут')
  await expect(card.getByLabel('Инициатива')).toHaveCount(0)
  await expect(card.locator('.ecc-ac')).toHaveCount(0)
  const tileBox = await card.boundingBox(), hpBox = await card.locator('.hp-numbers').boundingBox()
  expect(tileBox.x + tileBox.width - hpBox.x - hpBox.width).toBeGreaterThanOrEqual(13)
  await card.locator('.p-name').click({ modifiers: ['Meta'] })
  await expect(card.getByRole('checkbox')).toBeChecked()
  await expect(page.getByText('Открыть лист', { exact: true })).not.toBeVisible()
  await card.locator('.p-name').click({ modifiers: ['Control'] })
  await expect(card.getByRole('checkbox')).not.toBeChecked()
  await card.getByRole('checkbox').click({ modifiers: ['Control'] })
  await expect(card.getByRole('checkbox')).toBeChecked()
  expect(await page.evaluate(() => window.controls.state.drags)).toBe(0)
  await card.locator('.p-name').click()
  await expect(page.getByLabel('Защита и пассивные навыки')).toContainText('Пассивная внимательность16')
  await expect(page.getByLabel('Защита и пассивные навыки')).toContainText('Пассивное расследование18')
  await expect(page.getByLabel('Защита и пассивные навыки')).toContainText('Класс доспеха12')
  await page.getByText('Инициатива', { exact: true }).click()
  await page.getByText('Бросить инициативу', { exact: true }).click()
  expect(await page.evaluate(() => window.controls.player.initiative)).toBe(17)
  await page.keyboard.press('Escape')
  await page.evaluate(() => { window.controls.state.drags = 0 })
  const npc = page.locator('.enc-row')
  await npc.locator('.enc-name').click({ modifiers: ['Meta'] })
  await expect(npc.getByRole('checkbox')).toBeChecked()
  await npc.locator('.enc-avatar').click({ modifiers: ['Control'] })
  await expect(npc.getByRole('checkbox')).not.toBeChecked()
  expect(await page.evaluate(() => window.controls.state.drags)).toBe(0)
  await page.evaluate(() => { window.controls.encounter.encounter.active = true })
  await card.locator('.p-name').click()
  await expect(page.getByText('Инициатива', { exact: true })).not.toBeVisible()
})
