import { test, expect } from '@playwright/test'
for (const mobile of [false, true]) test(`participant menu and Ctrl selection ${mobile ? 'mobile' : 'desktop'}`, async ({ page }) => {
  page.on('pageerror', error => { throw error })
  await page.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1200, height: 900 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/tests/tutorials/fixtures/participant-controls.html')
  const card = page.locator('.p-card')
  await expect(card).not.toContainText('Эльф')
  await expect(card).not.toContainText('Плут')
  await expect(card.getByLabel('Инициатива')).toHaveCount(0)
  await expect(card.locator('.ecc-ac')).toHaveCount(0)
  const combatInfoWidth = (await card.locator('.p-info').boundingBox()).width
  const combatWidth = (await card.boundingBox()).width
  await page.evaluate(() => { window.controls.state.combat = false })
  const normalInfoWidth = (await card.locator('.p-info').boundingBox()).width
  expect(combatInfoWidth).toBeCloseTo(normalInfoWidth, 1)
  expect(combatWidth - (await card.boundingBox()).width).toBe(45)
  await page.evaluate(() => { window.controls.state.combat = true })
  const tileBox = await card.boundingBox(), hpBox = await card.locator('.hp-numbers').boundingBox()
  expect(tileBox.x + tileBox.width - hpBox.x - hpBox.width).toBeGreaterThanOrEqual(13)
  await card.locator('.p-name').click({ modifiers: ['Meta'] })
  await expect(card.getByRole('checkbox')).toBeChecked()
  await expect(page.getByText('Открыть лист', { exact: true })).not.toBeVisible()
  await card.locator('.p-name').click({ modifiers: ['Control'] })
  await expect(card.getByRole('checkbox')).not.toBeChecked()
  await card.getByRole('checkbox').click({ modifiers: ['Control'] })
  await expect(card.getByRole('checkbox')).toBeChecked()
  expect(await page.evaluate(() => window.controls.state.drags)).toBe(0)
  await card.locator('.p-name').click()
  const indicators = page.locator('.participant-menu-stat')
  await expect(indicators).toHaveText(['12', '16', '18'])
  const boxes = await indicators.evaluateAll(nodes => nodes.map(node => node.getBoundingClientRect().top))
  expect(new Set(boxes).size).toBe(1)
  await page.getByLabel('Пассивная внимательность: 16', { exact: true }).hover()
  await expect(page.locator('.itt-title')).toHaveText('Пассивная внимательность')
  await expect(page.locator('.itt-desc')).toContainText('10 + 6')
  const layers = await page.evaluate(() => ({ tooltip: Number(getComputedStyle(document.querySelector('[role=tooltip]')).zIndex), menu: Number(getComputedStyle(document.querySelector('.ram-popover')).zIndex) }))
  expect(layers.tooltip).toBeGreaterThan(layers.menu)
  await page.getByLabel('Класс доспеха: 12', { exact: true }).focus()
  await expect(page.locator('.itt-title')).toHaveText('Класс доспеха')
  await page.getByText('Инициатива', { exact: true }).click()
  await page.getByText('Бросить инициативу', { exact: true }).click()
  expect(await page.evaluate(() => window.controls.player.initiative)).toBe(17)
  await page.keyboard.press('Escape')
  await page.evaluate(() => { window.controls.state.drags = 0 })
  const npc = page.locator('.enc-row')
  await expect(npc.locator('.ram-trigger')).not.toBeVisible()
  const npcBox = await npc.boundingBox(), avatarBox = await npc.locator('.enc-avatar').boundingBox(), acBox = await npc.locator('.enc-ac').boundingBox()
  expect(npcBox.height - avatarBox.height).toBeLessThanOrEqual(12)
  expect(acBox.x).toBeGreaterThanOrEqual(avatarBox.x + avatarBox.width)
  for (const row of [card, npc]) {
    const size = await row.getByRole('checkbox').evaluate(node => getComputedStyle(node, '::before').width)
    expect(size).toBe('24px')
  }
  await npc.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByText('История урона и эффектов', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await npc.locator('.enc-name').click({ modifiers: ['Meta'] })
  await expect(npc.getByRole('checkbox')).toBeChecked()
  await npc.locator('.enc-avatar').click({ modifiers: ['Control'] })
  await expect(npc.getByRole('checkbox')).not.toBeChecked()
  expect(await page.evaluate(() => window.controls.state.drags)).toBe(0)
  await page.evaluate(() => { window.controls.state.challenge = true })
  await expect(npc.locator('.ecr-result')).toBeVisible()
  await expect(npc.locator('.ecr-title')).toContainText('Спасбросок')
  const resultBox = await npc.locator('.ecr-result').boundingBox(), rowWithResult = await npc.boundingBox()
  expect(resultBox.x + resultBox.width).toBeLessThanOrEqual(rowWithResult.x + rowWithResult.width)
  if (!mobile) expect(rowWithResult.height).toBe(npcBox.height)
  await page.evaluate(() => { window.controls.encounter.encounter.active = true })
  await card.locator('.p-name').click()
  await expect(page.getByText('Инициатива', { exact: true })).not.toBeVisible()
})
