import { test, expect } from '@playwright/test'
for (const mobile of [false, true]) test(`group saves and retry ${mobile ? 'mobile' : 'desktop'}`, async ({ page }) => {
  page.on('pageerror', error => { throw error })
  await page.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1200, height: 900 })
  await page.goto('/tests/tutorials/fixtures/session-saves.html')
  await expect(page.getByText('Ловкость · Сл 15', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Бросить', exact: true }).click()
  const heroTarget = page.locator('.session-target-option').filter({ hasText: 'Тиф' })
  await expect(heroTarget.locator('.stat-bar--medium')).toBeVisible()
  await expect(heroTarget.locator('.armor-class-chip')).toContainText('13')
  await expect(heroTarget.locator('.save-formula')).toHaveAttribute('aria-label', 'Спасбросок: d20 + 6')
  await expect(heroTarget.getByRole('checkbox')).toHaveCSS('--checkbox-size', '20px')
  await page.locator('.session-target-option').filter({ hasText: 'Тиф' }).getByRole('checkbox').check()
  await page.locator('.session-target-option').filter({ hasText: 'Гоблин' }).getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Бросить · 2', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Ошибка связи')
  await page.getByRole('button', { name: 'Сохранить результаты', exact: true }).click()
  await expect(page.locator('.event-save-result')).toHaveCount(2)
  expect(await page.evaluate(() => window.requests[0])).toEqual(await page.evaluate(() => window.requests[1]))
  await expect(page.locator('.event-save-result').filter({ hasText: 'Гоблин' })).toContainText('Б')
  await expect(page.locator('.event-row')).toHaveCount(1)
  const roll = await page.locator('.event-roll').boundingBox(), save = await page.locator('.event-save').boundingBox()
  expect(save.y).toBeGreaterThan(roll.y)
  const goblin = page.locator('.event-save-result').filter({ hasText: 'Гоблин' })
  await expect(goblin.getByRole('button', { name: 'Применить успех' })).toBeVisible()
  await expect(goblin.getByRole('button', { name: 'Применить провал' })).toBeVisible()
  await goblin.getByRole('button', { name: 'Применить успех' }).click()
  await page.getByRole('button', { name: 'Применить · 1', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Повторите запрос')
  await page.getByRole('button', { name: 'Повторить применение', exact: true }).click()
  await expect(goblin.locator('.damage-impact')).toContainText('Урон 7')
  await expect(goblin.locator('.impact-hp')).toContainText('15')
  await expect(goblin.getByRole('button')).toHaveCount(0)
  expect(await page.evaluate(() => window.impactRequests[0])).toEqual(await page.evaluate(() => window.impactRequests[1]))
  await page.getByRole('button', { name: 'Применить к целям' }).click()
  await expect(page.locator('.session-target-option').filter({ hasText: 'Гоблин' }).getByRole('checkbox')).toBeDisabled()
  await page.locator('.session-target-option').filter({ hasText: 'Тиф' }).getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Применить · 1', exact: true }).click()
  await expect(page.locator('.damage-impact')).toHaveCount(2)
})

for (const mobile of [false, true]) test(`attack targets persist and can be changed ${mobile ? 'mobile' : 'desktop'}`, async ({ page }) => {
  page.on('pageerror', error => { throw error })
  await page.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1200, height: 900 })
  await page.goto('/tests/tutorials/fixtures/session-saves.html?attack')
  const chooseButton = page.getByRole('button', { name: 'Выбрать цели', exact: true })
  await expect(chooseButton).toHaveCSS('border-top-style', 'dashed')
  const buttonBox = await chooseButton.boundingBox(), rollBox = await page.locator('.event-roll').boundingBox()
  expect(buttonBox.y).toBeLessThan(rollBox.y + 15)
  await chooseButton.click()
  const hero = page.locator('.session-target-option').filter({ hasText: 'Тиф' })
  const goblin = page.locator('.session-target-option').filter({ hasText: 'Гоблин' })
  await expect(hero.locator('.hp-row')).toBeVisible()
  await expect(goblin.locator('.hp-row')).toBeVisible()
  await expect(hero.locator('.save-target-placeholder')).toHaveCSS('width', '56px')
  await hero.click({ modifiers: ['Meta'] })
  await expect(hero.getByRole('checkbox')).toBeChecked()
  await hero.click({ modifiers: ['Control'] })
  await expect(hero.getByRole('checkbox')).not.toBeChecked()
  await hero.getByRole('checkbox').click({ modifiers: ['Control'] })
  await expect(hero.getByRole('checkbox')).toBeChecked()
  await goblin.getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Сохранить · 2', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Ошибка сохранения целей')
  await expect(hero.getByRole('checkbox')).toBeDisabled()
  await page.getByRole('button', { name: 'Повторить сохранение', exact: true }).click()
  await expect(page.getByLabel('Цели атаки').locator('.save-target-name')).toHaveCount(2)
  expect(await page.evaluate(() => window.attackRequests[0])).toEqual(await page.evaluate(() => window.attackRequests[1]))
  expect(await page.evaluate(() => window.attackRequests[1].targets.every(target => !target.snapshot && !target.hp))).toBe(true)
  expect(await page.evaluate(() => window.attackEvent.data.result.total)).toBe(18)
  await page.getByRole('button', { name: 'Изменить цели', exact: true }).click()
  await expect(hero.getByRole('checkbox')).toBeChecked()
  await expect(goblin.getByRole('checkbox')).toBeChecked()
  await hero.getByRole('checkbox').uncheck()
  await goblin.getByRole('checkbox').uncheck()
  await page.getByRole('button', { name: 'Сохранить · 0', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Выбрать цели', exact: true })).toBeVisible()
  await expect(page.getByLabel('Цели атаки')).toHaveCount(0)
  await expect(page.locator('.event-row')).toHaveCount(1)
})
