import { test, expect } from '@playwright/test'

for (const mobile of [false, true]) {
  test.describe(`spell menu ${mobile ? 'mobile' : 'desktop'}`, () => {
    test.beforeEach(async ({ page }) => {
      page.on('pageerror', error => { throw error })
      await page.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1400, height: 1000 })
      await page.goto('/tests/tutorials/fixtures/spell-rolls.html')
      await expect(page.locator('.spell-row')).toHaveCount(4)
    })

    test('all metrics open one menu; attack overrides and critical damage preserve formulas', async ({ page }) => {
      const row = page.locator('.spell-row').filter({ hasText: 'Леденящее прикосновение' })
      await expect(row.locator('button')).toHaveCount(0)
      await expect(row.getByRole('img', { name: /^d8:/ })).toHaveCount(1)
      await row.locator('.ad-atk').click()
      expect(await page.evaluate(() => window.rolls)).toEqual([])
      await page.getByRole('menuitem', { name: 'Бросить на атаку', exact: true }).click()
      const disadvantage = page.getByRole('switch', { name: 'Помеха' })
      await expect(disadvantage).toHaveAttribute('aria-checked', 'true')
      await disadvantage.click()
      await page.getByRole('switch', { name: 'Преимущество' }).click()
      await page.getByRole('menuitem', { name: 'Бросить на атаку', exact: true }).last().click()
      expect(await page.evaluate(() => window.rolls)).toEqual([{ title: 'Атака: Леденящее прикосновение', bonus: 7, mode: 'advantage' }])
      expect(await page.evaluate(() => window.attackContext)).toMatchObject({ kind: 'attack', abilitySuggestId: 4, weaponAttack: false })
      await row.locator('.ad-dmg').click()
      await page.getByRole('menuitem', { name: 'Бросить на урон', exact: true }).click()
      await page.getByRole('switch', { name: 'Критическое попадание' }).click()
      await page.getByRole('menuitem', { name: 'Бросить на урон', exact: true }).last().click()
      expect(await page.evaluate(() => window.rolls.at(-1))).toEqual({ title: 'Критический урон: Леденящее прикосновение', expression: '4d8{Некротический}+3' })
      await row.locator('.sp-name').click()
      await page.getByRole('menuitem', { name: 'Бросить на урон', exact: true }).click()
      await expect(page.getByRole('switch', { name: 'Критическое попадание' })).toHaveAttribute('aria-checked', 'false')
      await page.getByRole('menuitem', { name: 'Бросить на урон', exact: true }).last().click()
      expect(await page.evaluate(() => window.rolls.at(-1).expression)).toBe('2d8{Некротический}+3')
      expect(await page.evaluate(() => window.writes)).toEqual([])
      expect(await page.evaluate(() => window.events)).toEqual([])
    })

    test('save, healing and utility spells offer only relevant rolls; casting restrictions block confirmation', async ({ page }) => {
      const save = page.locator('.spell-row').filter({ hasText: 'Урон со спасброском' })
      await save.click()
      await expect(page.getByRole('menuitem', { name: 'Бросить на атаку', exact: true })).toHaveCount(0)
      await expect(page.getByRole('menuitem', { name: 'Бросить на лечение', exact: true })).toHaveCount(0)
      await page.getByRole('menuitem', { name: 'Бросить на урон', exact: true }).click()
      await expect(page.getByRole('switch', { name: 'Критическое попадание' })).toHaveCount(0)
      await page.getByRole('menuitem', { name: 'Бросить на урон', exact: true }).last().click()
      expect(await page.evaluate(() => window.rolls.at(-1).expression)).toBe('2d6')
      const heal = page.locator('.spell-row').filter({ hasText: 'Лечение' })
      await heal.locator('.ad-heal').click()
      await expect(page.getByRole('menuitem', { name: /Бросить на (атаку|урон)/ })).toHaveCount(0)
      await page.getByRole('menuitem', { name: 'Бросить на лечение', exact: true }).click()
      await expect(page.getByText('Итоговое лечение', { exact: true })).toBeVisible()
      await page.getByRole('menuitem', { name: 'Бросить на лечение', exact: true }).last().click()
      expect(await page.evaluate(() => window.rolls.at(-1).expression)).toBe('1d8')
      await page.locator('.spell-row').filter({ hasText: 'Свет' }).click()
      await expect(page.getByRole('menuitem', { name: /Бросить/ })).toHaveCount(0)
      await expect(page.getByRole('menuitem', { name: 'Потратить ячейку', exact: true })).toHaveCount(0)
      await page.keyboard.press('Escape')
      await page.evaluate(() => { window.spellCtx.characterArmor.state.castingBlocked = true })
      await save.click()
      await page.getByRole('menuitem', { name: 'Бросить на урон', exact: true }).click()
      await expect(page.getByRole('menuitem', { name: 'Бросить на урон', exact: true }).last()).toBeDisabled()
      expect(await page.evaluate(() => window.rolls.length)).toBe(2)
      expect(await page.evaluate(() => window.writes)).toEqual([])
    })

    test('spending a slot is separate from rolling and absent for cantrips', async ({ page }) => {
      await page.locator('.spell-row').filter({ hasText: 'Лечение' }).click()
      await page.getByRole('menuitem', { name: 'Потратить ячейку', exact: true }).click()
      expect(await page.evaluate(() => window.rolls)).toEqual([])
      const writes = await page.evaluate(() => window.writes)
      expect(writes).toHaveLength(1)
      expect(writes[0].slot_pools.long_rest).toEqual([{ level: 1, total: 2, used: 1 }])
      expect(await page.evaluate(() => window.events[0].type)).toBe('spell_used')
    })
  })
}
