import { test, expect } from '@playwright/test'
for (const mobile of [false, true]) test(`structured spell editor ${mobile ? 'mobile' : 'desktop'}`, async ({ page }) => {
  page.on('pageerror', error => { throw error })
  await page.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1000, height: 900 })
  await page.goto('/tests/tutorials/fixtures/spell-presentation-editor.html')
  await page.getByRole('combobox', { name: 'Время сотворения', exact: true }).selectOption('reaction')
  await page.getByRole('textbox', { name: 'Условие реакции', exact: true }).fill('Когда попадает атака')
  await page.getByRole('combobox', { name: 'Время сотворения', exact: true }).selectOption('minutes')
  await expect(page.getByRole('textbox', { name: 'Условие реакции', exact: true })).toHaveCount(0)
  await page.getByRole('spinbutton', { name: 'Количество времени' }).fill('10')
  await page.getByRole('combobox', { name: 'Дистанция', exact: true }).selectOption('ranged')
  await page.getByRole('spinbutton', { name: 'Дальность', exact: true }).fill('60')
  await page.getByRole('combobox', { name: 'Форма области', exact: true }).selectOption('sphere')
  await page.getByRole('spinbutton', { name: 'Размер области', exact: true }).fill('20')
  await page.getByRole('switch', { name: 'Можно выбирать себя', exact: true }).click()
  expect(await page.evaluate(() => window.editorState.data)).toMatchObject({ time: { kind: 'minutes', value: 10 }, range: { kind: 'ranged', distance: 60, shape: 'sphere', size: 20, can_self: true } })
  await page.getByRole('combobox', { name: 'Дистанция', exact: true }).selectOption('custom')
  await expect(page.getByRole('spinbutton', { name: 'Дальность', exact: true })).toHaveCount(0)
  await expect(page.getByRole('spinbutton', { name: 'Размер области', exact: true })).toHaveCount(0)
  await page.getByRole('textbox', { name: 'Своя дистанция', exact: true }).fill('Весь план')
  await page.getByRole('combobox', { name: 'Тип действия', exact: true }).selectOption('timed')
  await page.getByRole('combobox', { name: 'Время выполнения', exact: true }).selectOption('hours')
  expect(await page.evaluate(() => window.editorState.actions[0])).toMatchObject({ action_type: 'timed', time: { kind: 'hours', value: 1 } })
})
