import { test, expect } from '@playwright/test'
async function openSpell(page, name) {
  const row = page.locator('.spell-row').filter({ hasText: name })
  await row.scrollIntoViewIfNeeded()
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))
  const box = await row.boundingBox(); await page.mouse.click(box.x + box.width / 2, box.y + box.height / 2)
  await expect(page.getByRole('menuitem').first()).toHaveText('Использовать на…')
  await page.getByRole('menuitem', { name: 'Использовать на…', exact: true }).click()
}
for (const mobile of [false, true]) test(`spell application selects disjoint slot levels and multiple targets on ${mobile ? 'mobile' : 'desktop'}`, async ({ page }) => {
  page.on('pageerror', error => { throw error })
  await page.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1400, height: 1000 })
  await page.route('**/api/**', route => new URL(route.request().url()).pathname.startsWith('/api/') ? route.fulfill({ json: {} }) : route.continue())
  await page.goto('/tests/tutorials/fixtures/spell-applications.html')
  await openSpell(page, 'Благословение')
  const slider = page.getByRole('slider', { name: 'Круг ячейки' })
  await expect(slider.locator('.spell-level-sector')).toHaveCount(9)
  await expect(slider.locator('[data-level="2"]')).toHaveClass(/unavailable/)
  await slider.focus(); await slider.press('ArrowRight')
  await expect(slider).toHaveAttribute('aria-valuenow', '3')
  await slider.press('ArrowLeft'); await expect(slider).toHaveAttribute('aria-valuenow', '1')
  const start = await slider.locator('[data-level="1"]').boundingBox(), end = await slider.locator('[data-level="3"]').boundingBox()
  await page.mouse.move(start.x + start.width / 2, start.y + start.height / 2); await page.mouse.down()
  await page.mouse.move(end.x + end.width / 2, end.y + end.height / 2, { steps: 5 }); await page.mouse.up()
  await expect(slider).toHaveAttribute('aria-valuenow', '3')
  await page.getByRole('checkbox', { name: 'На себя' }).check()
  await page.getByRole('checkbox', { name: 'Торин' }).check()
  await page.getByRole('group', { name: 'Целей мастеру' }).getByRole('spinbutton').fill('2')
  await page.getByRole('group', { name: 'Целей мастеру' }).getByRole('spinbutton').press('Tab')
  await page.getByRole('button', { name: 'Применить · 4 / 5' }).click()
  expect(await page.evaluate(() => window.casts[0])).toMatchObject({ id: 548, castLevel: 3, spendSlot: true, pool: 'short_rest', targets: ['self', 'ally'], dmCount: 2, optionKey: 'bless' })
  await expect(page.getByRole('menuitem', { name: 'Использовать на…', exact: true })).toHaveCount(0)
  await openSpell(page, 'Лечащее слово')
  await expect(page.getByRole('menuitem', { name: 'Бросить на лечение', exact: true })).toHaveCount(0)
  await expect(page.getByRole('combobox', { name: 'Источник ячейки' })).toHaveCount(0)
  await page.getByRole('slider').locator('[data-level="3"]').click()
  await page.getByRole('menuitem', { name: 'На себя', exact: true }).click()
  expect(await page.evaluate(() => window.casts[1])).toMatchObject({ id: 601, castLevel: 3, spendSlot: true, pool: 'long_rest' })
  await page.goto('/tests/tutorials/fixtures/spell-applications.html?offline')
  await openSpell(page, 'Лечащее слово')
  await expect(page.getByRole('menuitem', { name: 'На себя', exact: true })).toBeVisible()
  await expect(page.getByRole('menuitem', { name: 'Мастер — выберет цель' })).toHaveCount(0)
  await page.getByRole('slider').focus(); await page.getByRole('slider').press('ArrowRight')
  await expect(page.locator('.damage-preview')).toContainText('Лечение')
  await page.getByRole('switch', { name: 'Потратить ячейку', exact: true }).click()
  await page.getByRole('menuitem', { name: 'На себя', exact: true }).click()
  expect(await page.evaluate(() => window.casts[0])).toMatchObject({ id: 601, castLevel: 3, spendSlot: false, targets: ['self'] })
})
