import { test, expect } from '@playwright/test'

async function clickRow(locator) {
  await locator.scrollIntoViewIfNeeded()
  await locator.page().evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))
  await locator.click()
}

for (const mobile of [false, true]) {
  test.describe(`spell menu ${mobile ? 'mobile' : 'desktop'}`, () => {
    test.beforeEach(async ({ page }) => {
      page.on('pageerror', error => { throw error })
      await page.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1400, height: 1000 })
      await page.goto('/tests/tutorials/fixtures/spell-rolls.html')
      await expect(page.locator('.spell-row')).toHaveCount(7)
    })

    test('all metrics open one menu; attack overrides and critical damage preserve formulas', async ({ page }) => {
      const row = page.locator('.spell-row').filter({ hasText: 'Леденящее прикосновение' })
      await expect(row.locator('button')).toHaveCount(0)
      await expect(row.getByRole('img', { name: /^d8:/ })).toHaveCount(1)
      await clickRow(row.locator('.ad-atk'))
      expect(await page.evaluate(() => window.rolls)).toEqual([])
      await page.getByRole('menuitem', { name: 'Бросить на атаку', exact: true }).click()
      const disadvantage = page.getByRole('switch', { name: 'Помеха' })
      await expect(disadvantage).toHaveAttribute('aria-checked', 'true')
      await disadvantage.click()
      await page.getByRole('switch', { name: 'Преимущество' }).click()
      await page.getByRole('menuitem', { name: 'Бросить на атаку', exact: true }).last().click()
      expect(await page.evaluate(() => window.rolls)).toEqual([{ title: 'Атака: Леденящее прикосновение', bonus: 7, mode: 'advantage' }])
      expect(await page.evaluate(() => window.attackContext)).toMatchObject({ kind: 'attack', abilitySuggestId: 4, weaponAttack: false })
      await clickRow(row.locator('.ad-dmg'))
      await page.getByRole('menuitem', { name: 'Бросить на урон', exact: true }).click()
      await page.getByRole('switch', { name: 'Критическое попадание' }).click()
      await page.getByRole('menuitem', { name: 'Бросить на урон', exact: true }).last().click()
      expect(await page.evaluate(() => window.rolls.at(-1))).toEqual({ title: 'Критический урон: Леденящее прикосновение', expression: '4d8{Некротический}+3' })
      await clickRow(row.locator('.sp-name'))
      await page.getByRole('menuitem', { name: 'Бросить на урон', exact: true }).click()
      await expect(page.getByRole('switch', { name: 'Критическое попадание' })).toHaveAttribute('aria-checked', 'false')
      await page.getByRole('menuitem', { name: 'Бросить на урон', exact: true }).last().click()
      expect(await page.evaluate(() => window.rolls.at(-1).expression)).toBe('2d8{Некротический}+3')
      expect(await page.evaluate(() => window.writes)).toEqual([])
      expect(await page.evaluate(() => window.events)).toEqual([])
    })

    test('save, healing and utility spells offer only relevant rolls; casting restrictions block confirmation', async ({ page }) => {
      const save = page.locator('.spell-row').filter({ hasText: 'Урон со спасброском' })
      await clickRow(save)
      await expect(page.getByRole('menuitem', { name: 'Бросить на атаку', exact: true })).toHaveCount(0)
      await expect(page.getByRole('menuitem', { name: 'Бросить на лечение', exact: true })).toHaveCount(0)
      await page.getByRole('menuitem', { name: 'Бросить на урон', exact: true }).click()
      await expect(page.getByRole('switch', { name: 'Критическое попадание' })).toHaveCount(0)
      await page.getByRole('switch', { name: 'Потратить ячейку' }).click()
      await page.getByRole('menuitem', { name: 'Бросить на урон', exact: true }).last().click()
      expect(await page.evaluate(() => window.rolls.at(-1).expression)).toBe('2d6')
      const heal = page.locator('.spell-row').filter({ hasText: 'Лечение' })
      await clickRow(heal.locator('.ad-heal'))
      await expect(page.getByRole('menuitem', { name: /Бросить на (атаку|урон)/ })).toHaveCount(0)
      await page.getByRole('menuitem', { name: 'Бросить на лечение', exact: true }).click()
      await expect(page.getByText('Итоговое лечение', { exact: true })).toBeVisible()
      await page.getByRole('switch', { name: 'Потратить ячейку' }).click()
      await page.getByRole('menuitem', { name: 'Бросить на лечение', exact: true }).last().click()
      expect(await page.evaluate(() => window.rolls.at(-1).expression)).toBe('1d4+3')
      await clickRow(page.locator('.spell-row').filter({ hasText: 'Свет' }))
      await expect(page.getByRole('menuitem', { name: /Бросить/ })).toHaveCount(0)
      await expect(page.getByRole('menuitem', { name: 'Потратить ячейку', exact: true })).toHaveCount(0)
      await page.keyboard.press('Escape')
      await page.evaluate(() => { window.spellCtx.characterArmor.state.castingBlocked = true })
      await clickRow(save)
      await page.getByRole('menuitem', { name: 'Бросить на урон', exact: true }).click()
      await expect(page.getByRole('menuitem', { name: 'Бросить и потратить ячейку', exact: true })).toBeDisabled()
      expect(await page.evaluate(() => window.rolls.length)).toBe(2)
      expect(await page.evaluate(() => window.writes)).toEqual([])
    })

    test('spending a slot is separate from rolling and absent for cantrips', async ({ page }) => {
      await clickRow(page.locator('.spell-row').filter({ hasText: 'Лечение' }))
      await page.getByRole('menuitem', { name: 'Потратить ячейку', exact: true }).click()
      await page.getByRole('menuitem', { name: /Долгий отдых · 1 круг/ }).click()
      expect(await page.evaluate(() => window.rolls)).toEqual([])
      const writes = await page.evaluate(() => window.writes)
      expect(writes).toHaveLength(1)
      expect(writes[0].slot_pools.long_rest[0]).toEqual({ level: 1, total: 2, used: 1 })
      expect(await page.evaluate(() => window.events[0].type)).toBe('spell_used')
    })
    test('healing uses the selected slot and modifier and spends the selected pool once', async ({ page }) => {
      const row = page.locator('.spell-row').filter({ hasText: 'Лечение' })
      const scaling = row.locator('.ad-heal .spell-scaling-formula')
      await expect(scaling).toHaveAttribute('aria-label', '+1к4 за каждый круг ячейки выше 1-го')
      await expect(scaling.locator('.system-die')).toHaveCount(1)
      await expect(scaling.locator('.ss-ro')).toHaveCount(1)
      await expect(scaling.locator('.scaling-caption')).toHaveText('за кругсвыше 1-го')
      await expect(row.locator('.sp-scaling-hint')).toHaveCount(0)
      await clickRow(row)
      await page.getByRole('menuitem', { name: 'Бросить на лечение', exact: true }).click()
      await page.getByRole('slider', { name: 'Круг ячейки' }).locator('[data-level=\"3\"]').click()
      await page.getByRole('combobox', { name: 'Источник ячейки' }).selectOption('short_rest')
      await page.getByRole('menuitem', { name: 'Бросить и потратить ячейку', exact: true }).click()
      expect(await page.evaluate(() => window.rolls.at(-1).expression)).toBe('3d4+3')
      expect(await page.evaluate(() => window.writes)).toHaveLength(1)
      expect(await page.evaluate(() => window.writes[0].slot_pools.short_rest[0].used)).toBe(1)
      expect(await page.evaluate(() => window.writes[0].slot_pools.long_rest.map(s => s.used))).toEqual([0, 0])
    })

    test('upcast preview requires a higher slot in either pool, including spent slots', async ({ page }) => {
      await page.goto('/tests/tutorials/fixtures/spell-rolls.html?slots=base-only')
      await expect(page.locator('.spell-row')).toHaveCount(7)
      await expect(page.locator('.spell-scaling-formula')).toHaveCount(0)
      await page.goto('/tests/tutorials/fixtures/spell-rolls.html?slots=pact-spent&long-type=1')
      const row = page.locator('.spell-row').filter({ hasText: 'Лечение' })
      await expect(row.locator('.spell-scaling-formula')).toBeVisible()
      await expect(row.locator('.spell-scaling-formula')).toHaveCSS('border-top-style', 'dashed')
      const baseDie = await row.locator('.ad-heal > .dd .system-die').boundingBox()
      const bonusDie = await row.locator('.spell-scaling-formula .system-die').boundingBox()
      expect(bonusDie.width).toBeLessThan(baseDie.width)
      const label = page.locator('.spell-row').filter({ hasText: 'Леденящее прикосновение' }).locator('.dd-type')
      const layout = await label.evaluate(node => ({ width: node.getBoundingClientRect().width, height: node.getBoundingClientRect().height, line: parseFloat(getComputedStyle(node).lineHeight) }))
      expect(layout.width).toBeLessThan(110)
      expect(layout.height).toBeGreaterThan(layout.line * 1.5)
    })

    test('rest refreshes visible slots immediately and the next cast preserves recovery', async ({ page }) => {
      await page.goto('/tests/tutorials/fixtures/spell-rolls.html?slots=rest')
      const spent = page.locator('.sp-slots-panel .ss-off')
      await expect(spent).toHaveCount(4)
      await page.getByRole('button', { name: 'Отдых и рассвет' }).click()
      await page.getByRole('menuitem', { name: 'Короткий отдых', exact: true }).click()
      await page.getByRole('button', { name: 'Завершить отдых' }).click()
      await expect(spent).toHaveCount(3)
      expect(await page.evaluate(() => window.sheetValues.spells.slot_pools.short_rest[0].used)).toBe(0)
      await page.getByRole('button', { name: 'Отдых и рассвет' }).click()
      await page.getByRole('menuitem', { name: 'Длинный отдых', exact: true }).click()
      await page.getByRole('button', { name: 'Отдохнуть', exact: true }).click()
      await expect(spent).toHaveCount(0)
      await clickRow(page.locator('.spell-row').filter({ hasText: 'Лечение' }))
      await page.getByRole('menuitem', { name: 'Бросить на лечение', exact: true }).click()
      await page.getByRole('slider', { name: 'Круг ячейки' }).locator('[data-level=\"1\"]').click()
      await page.getByRole('menuitem', { name: 'Бросить и потратить ячейку', exact: true }).click()
      await expect(spent).toHaveCount(1)
      expect(await page.evaluate(() => window.sheetValues.spells.slot_pools)).toEqual({ long_rest: [{ level: 1, total: 2, used: 1 }, { level: 3, total: 1, used: 0 }], short_rest: [{ level: 3, total: 1, used: 0 }] })
    })

    test('upcast attack remembers its level for damage without spending twice', async ({ page }) => {
      const row = page.locator('.spell-row').filter({ hasText: 'Луч атаки' })
      await clickRow(row)
      await page.getByRole('menuitem', { name: 'Бросить на атаку', exact: true }).click()
      await page.getByRole('slider', { name: 'Круг ячейки' }).locator('[data-level=\"3\"]').click()
      await page.getByRole('menuitem', { name: 'Бросить и потратить ячейку', exact: true }).click()
      await clickRow(row)
      await page.getByRole('menuitem', { name: 'Бросить на урон', exact: true }).click()
      await expect(page.getByRole('slider', { name: 'Круг ячейки' })).toHaveAttribute('aria-valuenow', '3')
      await expect(page.getByRole('switch', { name: 'Потратить ячейку' })).toHaveAttribute('aria-checked', 'false')
      await page.getByRole('menuitem', { name: 'Бросить на урон', exact: true }).last().click()
      expect(await page.evaluate(() => window.rolls.at(-1).expression)).toBe('4d6')
      expect(await page.evaluate(() => window.writes)).toHaveLength(1)
      expect(await page.evaluate(() => window.events)).toHaveLength(1)
    })

    test('conditional damage scales separately and unavailable slots block spending', async ({ page }) => {
      const row = page.locator('.spell-row').filter({ hasText: 'Ледяной кинжал' })
      await clickRow(row)
      await page.getByRole('menuitem', { name: 'Бросить: Взрыв', exact: true }).click()
      await page.getByRole('slider', { name: 'Круг ячейки' }).locator('[data-level=\"3\"]').click()
      await expect(page.getByRole('switch', { name: 'Критическое попадание' })).toHaveCount(0)
      await page.getByRole('menuitem', { name: 'Бросить: Взрыв', exact: true }).last().click()
      expect(await page.evaluate(() => window.rolls.at(-1).expression)).toBe('4d6')
      expect(await page.evaluate(() => window.writes)).toHaveLength(0)
      await clickRow(page.locator('.spell-row').filter({ hasText: 'Лечение' }))
      await page.getByRole('menuitem', { name: 'Бросить на лечение', exact: true }).click()
      await page.getByRole('slider', { name: 'Круг ячейки' }).locator('[data-level=\"4\"]').click()
      await expect(page.getByRole('slider', { name: 'Круг ячейки' })).toHaveAttribute('aria-valuenow', '1')
      await expect(page.getByRole('slider').locator('[data-level="4"]')).toHaveClass(/unavailable/)
    })

    test('innate spell keeps its fixed second level without spending a spell slot', async ({ page }) => {
      const row = page.locator('.spell-row').filter({ hasText: 'Расовое возмездие' })
      await expect(row.locator('.dd-count')).toHaveText('3')
      await expect(row.locator('.sp-scaling-hint')).toHaveCount(0)
      await clickRow(row)
      await page.getByRole('menuitem', { name: 'Бросить на урон', exact: true }).click()
      await expect(page.getByRole('slider', { name: 'Круг ячейки' })).toHaveCount(0)
      await page.getByRole('menuitem', { name: 'Бросить на урон', exact: true }).last().click()
      expect(await page.evaluate(() => window.rolls.at(-1).expression)).toBe('3d10')
      expect(await page.evaluate(() => window.writes)).toHaveLength(0)
    })
  })
}
