import { test, expect } from '@playwright/test'
for (const mobile of [false, true]) test(`poison follows damage/save phases and oil binds one weapon on ${mobile ? 'mobile' : 'desktop'}`, async ({ page }) => {
  page.on('pageerror', error => { throw error })
  await page.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1440, height: 1000 })
  await page.goto('/tests/tutorials/fixtures/status-mechanics.html')
  await page.evaluate(() => { Math.random = () => 0.49 })
  await page.getByRole('button', { name: 'Яд из зелья', exact: true }).click()
  await page.getByRole('menuitem', { name: 'При употреблении: 3d6', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Яд из зелья' })).toContainText('Урон применён')
  expect(await page.evaluate(() => window.statusCtx.values.hp.current)).toBe(41)
  await page.getByRole('dialog').getByRole('button', { name: /^(Закрыть|Close)$/ }).click()
  await expect(page.getByRole('menu')).toHaveCount(0)
  await page.getByRole('button', { name: 'Яд из зелья', exact: true }).click()
  await page.getByRole('menuitem', { name: 'После употребления: спасбросок, Сл 13' }).click()
  await expect(page.getByRole('dialog')).toContainText('Спасбросок не пройден')
  expect(await page.evaluate(() => window.statusCtx.values.states[0].params.damage_phase)).toBe('turn_damage')
  await page.getByRole('dialog').getByRole('button', { name: /^(Закрыть|Close)$/ }).click()
  await expect(page.getByRole('menu')).toHaveCount(0)
  await page.getByRole('button', { name: 'Масло остроты', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Выбрать оружие', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Меч', exact: true }).click()
  expect(await page.evaluate(() => window.statusCtx.values.states[1].params.weapon_uid)).toBe('sword')
})
