import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const read = name => readFileSync(fileURLToPath(new URL(`./${name}.vue`, import.meta.url)), 'utf8')
const itemReference = readFileSync(fileURLToPath(new URL('../../../../items/components/ItemReferenceRow.vue', import.meta.url)), 'utf8')
const equipmentSelect = readFileSync(fileURLToPath(new URL('../EquipmentItemSelect.vue', import.meta.url)), 'utf8')

describe('starting equipment wizard flow', () => {
  it('uses handbook item rows for class options, fixed grants and any-item picks', () => {
    const source = read('StepClassEquipment')
    expect(source).toContain('Закупиться потом в магазине')
    expect(source).toContain('<ItemReferenceRow')
    expect(source).toContain('<EquipmentItemSelect')
    expect(source).toContain("'choice-options--paired': group.options.length === 2")
    expect(source).toContain('<ShieldCheck')
    expect(source).toContain('.choice-title::after')
    expect(source).toContain('.choice-options--paired .choice-option + .choice-option')
    expect(source).toContain('border-left: 1px solid var(--border)')
    expect(source).toContain('.choice-options:not(.choice-options--paired) .choice-option + .choice-option')
    expect(source).toContain('border-top: 1px solid var(--border)')
    expect(source).toContain('.choice-option-label { position: relative;')
    expect(source).toContain('inset: 0; width: 100%; height: 100%')
    expect(source).not.toContain('clip: rect(0 0 0 0)')
    const optionRule = source.match(/\.choice-option \{([^}]*)\}/)?.[1] || ''
    expect(optionRule).not.toContain('background:')
    expect(optionRule).not.toContain('border-radius:')
    expect(source).toContain('v-if="entry.picks?.length"')
    expect(source).not.toContain('optionSelected(group, entry) && entry.picks')
    expect(source).toContain('pickValue(group.id, entry.id, pick.id, index - 1)')
    expect(source).toContain('choice?.optionId !== optionId')
    expect(source).toContain(':selected="optionSelected(group, entry)"')
    expect(source).toContain('@activate="selectOptionFromItem(group, entry)"')
    expect(source).toContain('@details="viewItem = linked.item"')
    expect(source).toContain('if (!optionSelected(group, entry)) selectEquipmentOption(group.id, entry.id)')
    expect(source).toMatch(/:count="entry\.count"\s+selected/)
    expect(source).toContain(':placeholder="pickPlaceholder(pick, index)"')
    expect(source).not.toContain('<span>{{ pick.label }}')
    expect(source).toContain('Также получите')
    expect(source).toContain('<ItemViewModal')
  })

  it('uses taller 64px weapon rows with stacked facts on the class step', () => {
    const source = read('StepClassEquipment')
    expect(source).toContain('roomy-weapon')
    expect(source).toContain('roomy-weapons')
    expect(equipmentSelect).toContain(':roomy-weapon="roomyWeapons"')
    expect(itemReference).toContain(':size="isRoomyWeapon ? 64 : 34"')
    expect(itemReference).toContain('.item-reference--roomy-weapon .item-reference-body { min-height: 96px;')
    expect(itemReference).toContain('grid-template-columns: minmax(0, 1fr) minmax(0, 1.25fr); grid-template-rows: auto auto;')
    expect(itemReference).toMatch(/\.item-reference-damage \{[^}]*grid-column: 1; grid-row: 2;/)
    expect(itemReference).toMatch(/\.item-reference-properties \{[^}]*grid-column: 2; grid-row: 2;/)
    expect(itemReference).toMatch(/\.item-reference-properties \{[^}]*flex-direction: column; align-items: flex-end;/)
    expect(itemReference).toMatch(/\.item-reference-economy \{[^}]*grid-column: 2; grid-row: 1;/)
    expect(itemReference).toContain('class="item-reference-economy"')
    expect(itemReference).toContain("content: '·'")
    expect(itemReference).toContain('v-for="(property, propertyIndex) in weaponPropertyItems"')
    expect(itemReference).toContain('@mouseenter="showPropertyTooltip($event, property)"')
    expect(itemReference).toContain('<ItemTooltip')
    expect(itemReference).toContain(':title="propertiesTooltip.title"')
    expect(itemReference).toContain(':desc="propertiesTooltip.desc"')
    expect(itemReference).toContain('desc: entry.desc ||')
  })

  it('offers the PHB wealth roll, five catalogues and a budgeted cart', () => {
    const source = read('StepStartingShop')
    expect(source).toContain('Начальное богатство')
    expect(source).toContain('startingWealthFormulaLabel')
    expect(source).toContain("{ id: 13, label: 'Транспорт' }")
    expect(source).toContain('canBuyShopItem(item)')
    expect(source).toContain('<ConfirmDialog')
    expect(source).toContain('Останется в кошельке')
  })
})
