import { test, expect } from '@playwright/test'
const url = '/tests/weapon-charges/bonus-transfer.html'
async function menu(page, scope = 'Бросить на атаку') {
 await page.getByRole('button', { name: 'Оружие', exact: true }).click()
 await page.getByRole('menuitem', { name: scope, exact: true }).click()
}
for (const width of [1280, 390]) test(`transfer uses quantity cells, updates AC and persists until reset (${width})`, async ({ page }) => {
 await page.setViewportSize({ width, height: 844 }); await page.goto(url)
 await expect(page.getByRole('button', { name: 'Сбросить перенос' })).toHaveCount(0)
 await menu(page)
 const cells = page.getByRole('group', { name: 'Перенести в защиту', exact: true }).getByRole('button')
 await expect(cells).toHaveCount(3)
 await expect(cells.nth(0)).toHaveAttribute('aria-pressed', 'false')
 await cells.nth(1).click()
 await expect(cells.nth(1)).toHaveAttribute('aria-pressed', 'true')
 await expect(cells.nth(2)).toHaveAttribute('aria-pressed', 'false')
 await expect(page.getByText('+2 к КД · +1 к атаке и урону', { exact: true })).toBeVisible()
 await expect(page.getByTestId('ac')).toHaveText('КД: 12')
 await page.getByRole('menuitem', { name: 'Бросить на атаку', exact: true }).last().click()
 expect(await page.evaluate(() => window.attackBonus)).toBe(6)
 await page.reload()
 await expect(page.getByText('+2 к КД', { exact: true })).toBeVisible()
 await menu(page, 'Бросить на урон')
 await expect(page.getByRole('group', { name: 'Перенести в защиту', exact: true })).toHaveCount(0)
 await expect(page.getByLabel('Итоговая формула урона')).toContainText('4')
 await page.keyboard.press('Escape'); await page.keyboard.press('Escape')
 await page.getByRole('button', { name: 'Сбросить перенос' }).click()
 await expect(page.getByTestId('ac')).toHaveText('КД: 10')
 await expect(page.getByRole('button', { name: 'Сбросить перенос' })).toHaveCount(0)
})
test('readers see the bonus; stowing or losing attunement suspends it', async ({ page }) => {
 await page.goto(url); await menu(page)
 await page.getByRole('group', { name: 'Перенести в защиту', exact: true }).getByRole('button').nth(2).click()
 await page.keyboard.press('Escape'); await page.keyboard.press('Escape')
 await page.evaluate(() => window.ctx.ownerMode = false)
 await expect(page.getByText('+3 к КД', { exact: true })).toBeVisible()
 await expect(page.getByRole('button', { name: 'Сбросить перенос' })).toHaveCount(0)
 await page.evaluate(() => { window.ctx.ownerMode = true; window.ctx.values.weapon[0].params.magic.attuned = false })
 await expect(page.getByTestId('ac')).toHaveText('КД: 10')
 await expect(page.getByText('Перенос в защиту приостановлен', { exact: true })).toBeVisible()
 await page.getByRole('button', { name: 'Сбросить перенос' }).click()
 expect(await page.evaluate(() => window.ctx.values.weapon[0].params.magic.bonus_transfer)).toBe(0)
})
test('editor derives maximum from weapon and validates missing bonus', async ({ page }) => {
 await page.goto(`${url}?editor`)
 await expect(page.getByText(/До 3 пунктов/)).toBeVisible()
 expect(await page.evaluate(() => window.editorError)).toBe('')
 await page.evaluate(() => window.editorData.weapon.magic_bonus = 0)
 await expect.poll(() => page.evaluate(() => window.editorError)).toContain('от 1 до 3')
})
