import { test, expect } from '@playwright/test'
for (const width of [1280, 390]) test(`initial stock rolls once, can be corrected and only confirmed death spends (${width})`, async ({ page }) => {
 await page.setViewportSize({ width, height: 844 })
 await page.goto('/tests/weapon-charges/initial-charges.html')
 await page.getByRole('button', { name: 'Добавить', exact: true }).click()
 const number = page.getByLabel('Начальный запас зарядов', { exact: true })
 await expect(number).toHaveValue('')
 await expect(page.getByRole('button', { name: 'Добавить предмет', exact: true })).toBeDisabled()
 await expect(page.getByText('Оружейная основа', { exact: true })).toHaveCount(0)
 await page.getByRole('button', { name: 'Бросить 1к8+1' }).click()
 const rolled = Number(await number.inputValue()); expect(rolled).toBeGreaterThanOrEqual(2); expect(rolled).toBeLessThanOrEqual(9)
 await expect(page.getByLabel(`Результат броска: ${rolled}`)).toBeVisible()
 await number.fill('1')
 await page.getByRole('button', { name: 'Добавить предмет', exact: true }).click()
 await expect(page.getByRole('group', { name: /1 из 1/ })).toBeVisible()
 await page.getByRole('button', { name: 'Цель погибла · −1 заряд' }).click()
 await expect(page.getByRole('group', { name: /0 из 1/ })).toBeVisible()
 await expect(page.getByRole('button', { name: 'Цель погибла · −1 заряд' })).toBeDisabled()
 await page.getByRole('button', { name: 'Параметры экземпляра', exact: true }).click()
 await expect(page.getByText('Начальный запас: 1 · Осталось: 0')).toBeVisible()
 await expect(page.getByRole('button', { name: 'Бросить 1к8+1' })).toHaveCount(0)
 expect(await page.evaluate(() => window.rolls)).toBe(1)
 await page.reload()
 await expect(page.getByRole('group', { name: /0 из 1/ })).toBeVisible()
 await page.evaluate(() => window.ctx.ownerMode = false)
 await expect(page.getByRole('button', { name: 'Цель погибла · −1 заряд' })).toHaveCount(0)
 await expect(page.getByText('Критическое попадание этим оружием')).toBeVisible()
})
test('fixed stock remains adjustable; charge-only items configure; cancellation creates nothing', async ({ page }) => {
 await page.goto('/tests/weapon-charges/initial-charges.html?fixed&no-base')
 await page.getByRole('button', { name: 'Добавить', exact: true }).click()
 await expect(page.getByLabel('Начальный запас зарядов', { exact: true })).toHaveValue('4')
 await expect(page.getByRole('button', { name: /Бросить/ })).toHaveCount(0)
 await page.getByLabel('Начальный запас зарядов', { exact: true }).fill('0')
 await page.getByRole('button', { name: 'Добавить предмет', exact: true }).click()
 expect(await page.evaluate(() => window.ctx.values.weapon[0].params.magic)).toMatchObject({ max_use: 0, remaining: 0 })
 await page.getByRole('button', { name: 'Добавить', exact: true }).click()
 await page.keyboard.press('Escape')
 expect(await page.evaluate(() => window.ctx.values.weapon.length)).toBe(1)
})
test('resource editor hides unused calculations and validates stock rules', async ({ page }) => {
 await page.goto('/tests/weapon-charges/initial-charges.html?editor')
 await expect(page.getByLabel('Как считать использования', { exact: true })).toHaveValue('initial')
 await page.getByLabel('Как определить начальный запас', { exact: true }).selectOption('fixed')
 await expect(page.getByRole('textbox', { name: 'Формула начального запаса' })).toHaveCount(0)
 await page.getByLabel('Как считать использования', { exact: true }).selectOption('fixed')
 expect(await page.evaluate(() => window.editorData.initial_charges)).toBeUndefined()
 await page.getByLabel('Как считать использования', { exact: true }).selectOption('initial')
 expect(await page.evaluate(() => window.editorData.max_use)).toBeUndefined()
})
