import { test, expect } from '@playwright/test'
test.beforeEach(async ({ page }) => {
  await page.route('**/api/suggest/**', route => route.fulfill({ json: { items: {} } }))
  page.on('pageerror', error => { throw error })
})
for (const width of [1280, 390]) {
 test(`automation status persists and clears in the real editor (${width})`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 })
  let saved
  await page.route('**/api/items/4167', async route => { saved = route.request().postDataJSON(); await route.fulfill({ status: 204 }) })
  await page.route('**/api/item-types**', route => route.fulfill({ json: { types: [{ id: 2, name: 'Вещи', fields: [] }] } }))
  await page.goto('/tests/weapon-charges/item-automation.html')
  await expect(page.getByText('Автоматизация: не оценено', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Редактировать', exact: true }).click()
  await page.locator('summary').filter({ hasText: 'Поддержка механик' }).click()
  await page.getByRole('combobox', { name: 'Автоматизация', exact: true }).selectOption('full')
  await page.getByRole('switch', { name: 'Требует взаимодействия с другим игроком' }).click()
  await page.getByRole('textbox', { name: 'Комментарий к поддержке' }).fill('Эффект на союзнике отмечается вручную.')
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click()
  expect(saved.automationStatus).toBe('full')
  expect(saved.requiresPlayerInteraction).toBe(true)
  expect(saved.data.automationStatus).toBeUndefined()
  await expect(page.getByText('Автоматизация: полностью', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Другие игроки', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Поддержка механик' })).toContainText('Эффект на союзнике отмечается вручную.')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Редактировать', exact: true }).click()
  await page.locator('summary').filter({ hasText: 'Поддержка механик' }).click()
  await expect(page.getByRole('combobox', { name: 'Автоматизация', exact: true })).toHaveValue('full')
  await page.getByRole('combobox', { name: 'Автоматизация', exact: true }).selectOption('partial')
  await page.getByRole('switch', { name: 'Требует взаимодействия с другим игроком' }).click()
  await page.getByRole('textbox', { name: 'Комментарий к поддержке' }).fill('')
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click()
  expect(saved.requiresPlayerInteraction).toBe(false)
  expect(saved.automationNote).toBe('')
  await expect(page.getByText('Автоматизация: частично', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Другие игроки', exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
 })
 test(`reader can inspect status without editing (${width})`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 })
  await page.goto('/tests/weapon-charges/item-automation.html?reader')
  await expect(page.getByRole('button', { name: 'Редактировать', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Поддержка механик', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Поддержка механик' })).toContainText('ещё не проверена')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
 })
}
