import { test, expect } from '@playwright/test'
for (const viewport of [{ width: 1280, height: 800 }, { width: 390, height: 844 }]) {
  test(`last charge persists, resolves once and can be undone (${viewport.width})`, async ({ page }) => {
    await page.setViewportSize(viewport)
    await page.goto('/tests/weapon-charges/fixture.html')
    await expect(page.getByText('Проверка последнего заряда', { exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: 'Израсходовать последний заряд' }).click()
    await expect(page.getByText('Проверка последнего заряда', { exact: true })).toBeVisible()
    await page.reload()
    await expect(page.getByRole('button', { name: 'Проверить', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Проверить', exact: true }).dblclick()
    await expect(page.getByText('Магические свойства утрачены', { exact: true })).toBeVisible()
    expect(await page.evaluate(() => window.rolls)).toBe(1)
    expect(await page.evaluate(() => window.logged[0].type)).toBe('dice_roll')
    await page.reload()
    await expect(page.getByText('Магические свойства утрачены', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Отменить утрату магии' }).click()
    await page.getByRole('button', { name: 'Отменить проверку', exact: true }).click()
    await expect(page.getByText('Магические свойства утрачены', { exact: true })).toHaveCount(0)
    expect(await page.evaluate(() => window.ctx.values.weapon[0].params.magic.remaining)).toBe(0)
    expect(await page.evaluate(() => window.ctx.values.weapon[0].params.magic.lost)).toBe(false)
  })
}
test('owner success closes the check; a reader cannot roll', async ({ page }) => {
  await page.goto('/tests/weapon-charges/fixture.html')
  await page.getByRole('button', { name: 'Израсходовать последний заряд' }).click()
  await page.evaluate(() => { window.ctx.ownerMode = false })
  await expect(page.getByRole('button', { name: 'Проверить', exact: true })).toHaveCount(0)
  await expect(page.getByText('Ожидает броска владельца персонажа')).toBeVisible()
  await page.evaluate(() => { window.ctx.ownerMode = true; window.result = 2 })
  await page.getByRole('button', { name: 'Проверить', exact: true }).click()
  await expect(page.getByText('Проверка последнего заряда', { exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => window.ctx.values.weapon[0].params.magic)).toMatchObject({ lost: false, remaining: 0, last_charge_check: { status: 'resolved', result: 2 } })
})

test('editor labels numeric input, validates bounds and selects a sole resource automatically', async ({ page }) => {
  await page.goto('/tests/weapon-charges/fixture.html?editor')
  await expect(page.getByLabel('Ресурс последнего заряда', { exact: true })).toHaveCount(0)
  const max = page.getByLabel('Верхняя граница опасного результата')
  await max.fill('2')
  expect(await page.evaluate(() => window.editorData.last_charge.failure_max)).toBe(2)
  await max.fill('21')
  expect(await page.evaluate(() => window.editorError)).toContain('пределах кости')
  await max.fill('1')
  await page.evaluate(() => { window.editorData.use_resources = [{ key: 'power', title: 'Сила посоха', max_use: 3 }] })
  await expect.poll(() => page.evaluate(() => window.editorData.last_charge.resource_key)).toBe('power')
  await expect(page.getByLabel('Ресурс последнего заряда', { exact: true })).toHaveCount(0)
  await page.evaluate(() => { window.editorData.use_resources.push({ key: 'light', title: 'Свет', max_use: 1 }) })
  await expect(page.getByLabel('Ресурс последнего заряда', { exact: true })).toBeVisible()
  await page.getByLabel('Ресурс последнего заряда', { exact: true }).selectOption('light')
  expect(await page.evaluate(() => window.editorData.last_charge.resource_key)).toBe('light')
  expect(await page.evaluate(() => window.editorError)).toBe('')
})
