import { test, expect } from '@playwright/test'
async function add(page, count = '2') {
 await page.goto('/tests/weapon-charges/luck-blade.html')
 await page.getByRole('button', { name: 'Добавить', exact: true }).click()
 await expect(page.getByRole('button', { name: 'Бросить 1к4−1' })).toBeVisible()
 await page.getByRole('button', { name: 'Бросить 1к4−1' }).click()
 const rolled = Number(await page.getByLabel('Желания', { exact: true }).inputValue())
 expect(rolled).toBeGreaterThanOrEqual(0); expect(rolled).toBeLessThanOrEqual(3)
 await page.getByLabel('Желания', { exact: true }).fill(count)
 await page.getByRole('button', { name: 'Добавить предмет', exact: true }).click()
}
for (const width of [1280, 390]) test(`luck and wishes use separate inline resources and dawn rules (${width})`, async ({ page }) => {
 await page.setViewportSize({ width, height: 844 }); await add(page)
 await expect(page.getByRole('group', { name: 'Удача: 1 из 1' })).toBeVisible()
 await expect(page.getByRole('group', { name: 'Желания: 2 из 2' })).toBeVisible()
 await expect(page.getByRole('group')).toHaveCount(2)
 await page.getByRole('button', { name: 'Проверка', exact: true }).click()
 await page.getByRole('button', { name: 'Перебросить: Проверка силы' }).click()
 await expect(page.getByRole('group', { name: 'Удача: 0 из 1' })).toBeVisible()
 await expect(page.getByRole('button', { name: 'Перебросить: Проверка силы' })).toHaveCount(0)
 await page.getByRole('button', { name: 'Сотворить желание · −1 заряд' }).click()
 await expect(page.getByRole('group', { name: 'Желания: 1 из 2' })).toBeVisible()
 await expect(page.getByRole('button', { name: 'Сотворить желание · −1 заряд' })).toBeDisabled()
 await page.reload()
 await expect(page.getByRole('button', { name: 'Сотворить желание · −1 заряд' })).toBeDisabled()
 await page.getByRole('button', { name: 'Рассвет', exact: true }).click()
 await page.getByRole('button', { name: 'Встретить рассвет' }).click()
 await page.getByRole('button', { name: 'Готово', exact: true }).click()
 await expect(page.getByRole('group', { name: 'Удача: 1 из 1' })).toBeVisible()
 await expect(page.getByRole('group', { name: 'Желания: 1 из 2' })).toBeVisible()
 await expect(page.getByRole('button', { name: 'Сотворить желание · −1 заряд' })).toBeEnabled()
 expect(await page.evaluate(() => window.bonus())).toBe(1)
 await page.evaluate(() => { window.ctx.ownerMode = false })
 await expect(page.getByRole('button', { name: 'Сотворить желание · −1 заряд' })).toHaveCount(0)
})
test('zero wishes remain empty; stored blade still grants saves and rerolls', async ({ page }) => {
 await add(page, '0')
 await expect(page.getByRole('button', { name: 'Сотворить желание · −1 заряд' })).toBeDisabled()
 await page.evaluate(() => { window.ctx.updateValues({ items: { sections: [{ items: window.ctx.values.weapon }] }, weapon: [] }) })
 expect(await page.evaluate(() => window.bonus())).toBe(1)
 await page.getByRole('button', { name: 'Проверка', exact: true }).click()
 expect(await page.evaluate(() => window.dice.lastD20.actions[0].label)).toContain('Удача')
 await page.evaluate(() => window.dice.runAction(window.dice.lastD20.id, 'reroll'))
 expect(await page.evaluate(() => window.ctx.values.items.sections[0].items[0].params.magic.resource_counts)).toMatchObject({ wishes: 0, luck: 0 })
})
test('editor keeps initial resources, local activation and reroll link editable', async ({ page }) => {
 await page.goto('/tests/weapon-charges/luck-blade.html?editor')
 await expect(page.getByLabel('Как считать использования', { exact: true }).nth(1)).toHaveValue('initial')
 await expect(page.getByLabel('Расход при перебросе', { exact: true })).toHaveValue('luck')
 await page.getByLabel('Расход при перебросе', { exact: true }).selectOption('wish')
 expect(await page.evaluate(() => window.editorData.roll_triggers[0].use_key)).toBe('wish')
 await page.getByLabel('Как считать использования', { exact: true }).nth(1).selectOption('fixed')
 expect(await page.evaluate(() => window.editorData.use_resources[1].initial_charges)).toBeUndefined()
})
