import { test, expect } from '@playwright/test'
const url = '/tests/weapon-charges/selected-target.html'
async function declare(page, name = 'Орк') {
 await page.getByLabel('Имя противника', { exact: true }).fill(name)
 await page.getByRole('button', { name: 'Объявить цель', exact: true }).click()
 await expect(page.getByText(name, { exact: true })).toBeVisible()
}
async function menu(page, scope) {
 await page.getByRole('button', { name: 'Оружие', exact: true }).click()
 await page.getByRole('menuitem', { name: scope, exact: true }).click()
}
for (const width of [1280, 390]) test(`target shares selection between attacks and damage with one custom separator (${width})`, async ({ page }) => {
 await page.setViewportSize({ width, height: 844 }); await page.goto(url); await declare(page)
 await menu(page, 'Бросить на атаку')
 const target = page.getByRole('switch', { name: 'По выбранной цели: Орк', exact: true })
 await expect(target).toBeChecked()
 const thrown = await page.getByRole('switch', { name: 'Метнуть', exact: true }).boundingBox()
 const separator = await page.locator('[role="separator"][aria-orientation="horizontal"]').filter({ visible: true }).boundingBox()
 const box = await target.boundingBox()
 expect(separator.y).toBeGreaterThan(thrown.y + thrown.height)
 expect(box.y).toBeGreaterThan(separator.y)
 await page.getByRole('menuitem', { name: 'Бросить на атаку', exact: true }).last().click()
 expect(await page.evaluate(() => window.rolls.at(-1).mode)).toBe('advantage')
 await menu(page, 'Бросить на урон')
 await expect(target).toBeChecked(); await expect(page.getByLabel('Добавит +3к6')).toBeVisible()
 await page.getByLabel('Критическое попадание', { exact: true }).click()
 await expect(page.getByLabel('Добавит +6к6')).toBeVisible()
 await page.getByRole('menuitem', { name: 'Бросить на урон', exact: true }).last().click()
 expect(await page.evaluate(() => window.rolls.at(-1).expression)).toBe('2d8{Колющий}+3{Колющий}+6d6{Колющий}')
 await menu(page, 'Бросить на урон'); await target.click()
 await page.keyboard.press('Escape'); await page.keyboard.press('Escape'); await page.reload()
 await menu(page, 'Бросить на атаку'); await expect(target).not.toBeChecked()
 await page.getByRole('menuitem', { name: 'Бросить на атаку', exact: true }).last().click()
 expect(await page.evaluate(() => window.rolls.at(-1).mode)).toBe('normal')
 await page.getByRole('button', { name: 'Атака другим оружием' }).click()
 expect(await page.evaluate(() => window.rolls.at(-1).mode)).toBe('disadvantage')
})
test('death waits for an explicit dawn even without resources; readers cannot change the target', async ({ page }) => {
 await page.goto(url); await declare(page)
 await page.evaluate(() => window.ctx.ownerMode = false)
 await expect(page.getByText('Орк', { exact: true })).toBeVisible()
 await expect(page.getByRole('button', { name: 'Враг погиб', exact: true })).toHaveCount(0)
 await page.evaluate(() => window.ctx.ownerMode = true)
 await page.getByRole('button', { name: 'Враг погиб', exact: true }).click()
 await page.getByRole('button', { name: 'Подтвердить', exact: true }).click()
 await expect(page.getByLabel('Имя противника', { exact: true })).toHaveCount(0)
 await page.getByRole('button', { name: 'Атака другим оружием' }).click()
 expect(await page.evaluate(() => window.rolls.at(-1).mode)).toBe('normal')
 await page.getByRole('button', { name: 'Рассвет', exact: true }).click()
 await page.getByRole('button', { name: 'Встретить рассвет', exact: true }).click()
 await page.getByRole('button', { name: 'Готово', exact: true }).click()
 await declare(page, 'Дракон')
 await expect(page.getByText('Осталось рассветов: 7')).toBeVisible()
})
test('editor hides optional dice and validates the target duration', async ({ page }) => {
 await page.goto(`${url}?editor`)
 await expect(page.getByLabel('Добавляет урон по цели', { exact: true })).toBeChecked()
 await page.getByLabel('Добавляет урон по цели', { exact: true }).click()
 expect(await page.evaluate(() => window.editorData.selected_target.damage)).toBeUndefined()
 await page.evaluate(() => window.editorData.selected_target.duration_dawns = 0)
 await expect.poll(() => page.evaluate(() => window.editorError)).toContain('длительность 1–100')
})
