import { test, expect } from '@playwright/test'
const url = '/tests/weapon-charges/weapon-use.html'
const current = page => page.evaluate(() => window.ctx.values.weapon[0].params.magic)
async function menu(page, scope) {
 await page.getByRole('button', { name: 'Оружие', exact: true }).click()
 await page.getByRole('menuitem', { name: scope, exact: true }).click()
}
async function attack(page, natural = 10) {
 await page.evaluate(n => window.natural = n, natural)
 await menu(page, 'Бросить на атаку')
 await expect(page.getByRole('combobox')).toHaveCount(0)
 await page.getByLabel('Метнуть молнией', { exact: true }).click()
 expect((await current(page)).remaining).toBe(1)
 await page.getByRole('menuitem', { name: 'Бросить на атаку', exact: true }).last().click()
}
for (const width of [1280, 390]) test(`line is flat, rolls inline and survives reload or a missed target (${width})`, async ({ page }) => {
 await page.setViewportSize({ width, height: 844 }); await page.goto(url)
 await attack(page)
 expect((await current(page)).remaining).toBe(0)
 await expect(page.getByText('Урон по цели', { exact: true })).toHaveCount(0)
 await expect(page.getByText(/Бросок атаки:|Уже списано:/)).toHaveCount(0)
 await expect(page.locator('.item-use-panel .item-use-panel, .item-use-panel .base-tile')).toHaveCount(0)
 const button = await page.getByRole('button', { name: 'Бросить урон', exact: true }).boundingBox()
 const formula = await page.getByLabel('Итоговая формула урона').boundingBox()
 expect(button.x + button.width).toBeLessThan(formula.x)
 await page.getByRole('button', { name: 'Бросить урон', exact: true }).dblclick()
 await expect(page.getByLabel('Результат броска: 15')).toBeVisible()
 await expect(page.getByLabel('Результат броска: 15').getByRole('img')).toHaveCount(4)
 await expect(page.getByText('= 15', { exact: true })).toBeVisible()
 await expect(page.getByText(/^При успехе:/)).toHaveCount(0)
 expect(await page.evaluate(() => window.damageRolls)).toEqual(['4d6{Молния|#ff0}'])
 await page.reload()
 await expect(page.getByLabel('Результат броска: 15')).toBeVisible()
 await page.evaluate(() => window.ctx.updateValues({ items: { sections: [{ items: window.ctx.values.weapon }] }, weapon: [] }))
 await page.reload()
 await expect(page.getByLabel('Результат броска: 15')).toBeVisible()
 await page.getByRole('button', { name: 'Завершить применение', exact: true }).click()
 await page.getByRole('button', { name: 'Завершить', exact: true }).click()
 expect(await page.evaluate(() => window.ctx.values.items.sections[0].items[0].params.magic)).toMatchObject({ remaining: 0, weapon_use: { status: 'completed' } })
})
test('hit addition lives in the damage submenu and pays once; readers have no controls', async ({ page }) => {
 await page.goto(url); await attack(page, 20)
 await page.evaluate(() => window.ctx.ownerMode = false)
 await expect(page.getByRole('button', { name: 'Бросить урон', exact: true })).toHaveCount(0)
 await expect(page.getByRole('button', { name: 'Оружие', exact: true })).toHaveCount(0)
 await page.evaluate(() => window.ctx.ownerMode = true)
 await menu(page, 'Бросить на урон')
 await page.getByLabel('Урон по цели', { exact: true }).click()
 await page.getByLabel('Критическое попадание', { exact: true }).click()
 await expect(page.getByLabel('Добавит +8к6')).toBeVisible()
 await page.getByRole('menuitem', { name: 'Бросить на урон', exact: true }).last().click()
 expect((await current(page)).weapon_use.steps[1].status).toBe('rolled')
 expect((await current(page)).remaining).toBe(0)
 await page.getByRole('button', { name: 'Бросить урон', exact: true }).click()
 expect(await page.evaluate(() => window.damageRolls)).toEqual(['2d6{Колющий}+3{Колющий}+8d6{Молния|#ff0}', '4d6{Молния|#ff0}'])
 await menu(page, 'Бросить на урон')
 await expect(page.getByLabel('Урон по цели', { exact: true })).toHaveCount(0)
 await page.keyboard.press('Escape'); await page.keyboard.press('Escape')
 await page.getByRole('button', { name: 'Завершить применение', exact: true }).click()
 await menu(page, 'Бросить на атаку')
 await expect(page.getByLabel('Метнуть молнией', { exact: true })).toBeDisabled()
 await page.getByRole('menuitem', { name: 'Бросить на атаку', exact: true }).last().click()
 expect(await page.evaluate(() => window.attacks)).toBe(2)
 expect((await current(page)).remaining).toBe(0)
})
test('editor shows dependent fields only and saves independent named steps', async ({ page }) => {
 await page.goto(url + '?editor')
 expect(await page.evaluate(() => window.editorError)).toBe('')
 await expect(page.getByLabel('Ресурс особого применения', { exact: true })).toHaveCount(0)
 await expect(page.getByLabel('Есть спасбросок', { exact: true })).toHaveCount(1)
 await page.getByLabel('Есть спасбросок', { exact: true }).click()
 expect(await page.evaluate(() => window.editorData.weapon_uses[0].steps[0].save)).toBeUndefined()
 await page.getByRole('button', { name: 'Добавить шаг после атаки', exact: true }).click()
 expect(await page.evaluate(() => window.editorError)).toContain('название')
 await page.getByRole('button', { name: 'Удалить шаг 3', exact: true }).click()
 await page.getByRole('button', { name: 'Удалить', exact: true }).click()
 expect(await page.evaluate(() => window.editorData.weapon_uses[0].steps.length)).toBe(2)
 expect(await page.evaluate(() => window.editorError)).toBe('')
})

for (const width of [1280, 390]) test(`attack toggles share one row and are mutually blocking (${width})`, async ({ page }) => {
 await page.setViewportSize({ width, height: 844 }); await page.goto(url)
 await menu(page, 'Бросить на атаку')
 const minus = page.getByRole('switch', { name: 'Помеха', exact: true })
 const plus = page.getByRole('switch', { name: 'Преимущество', exact: true })
 const separator = page.getByRole('group', { name: 'Режим броска атаки' }).getByRole('separator')
 await expect(minus).not.toBeChecked(); await expect(plus).not.toBeChecked()
 const left = await minus.boundingBox(), right = await plus.boundingBox()
 expect(Math.abs(left.y - right.y)).toBeLessThan(2)
 expect(left.x + left.width).toBeLessThan(right.x)
 expect(right.x + right.width).toBeLessThanOrEqual(width)
 await expect(separator).toHaveAttribute('aria-orientation', 'vertical')
 await minus.click(); await expect(plus).toBeDisabled()
 await minus.click(); await expect(plus).toBeEnabled()
 await plus.click(); await expect(minus).toBeDisabled()
 await page.evaluate(() => { window.testRolls = [3, 17]; window.attackEffects = [{ mode: 'disadvantage' }] })
 await page.getByRole('menuitem', { name: 'Бросить на атаку', exact: true }).last().click()
 expect(await page.evaluate(() => window.attackResults.at(-1))).toMatchObject({ rollMode: 'advantage', total: 22 })
 await menu(page, 'Бросить на атаку')
 await expect(minus).not.toBeChecked(); await expect(plus).not.toBeChecked()
 await page.getByRole('menuitem', { name: 'Бросить на атаку', exact: true }).last().click()
 expect(await page.evaluate(() => window.attackResults.at(-1))).toMatchObject({ rollMode: 'disadvantage', total: 8 })
 await menu(page, 'Бросить на урон')
 await expect(minus).toHaveCount(0); await expect(plus).toHaveCount(0)
})
test('special use and preset attacks forward the selected d20 mode', async ({ page }) => {
 await page.goto(url)
 await menu(page, 'Бросить на атаку')
 await page.getByRole('switch', { name: 'Помеха', exact: true }).click()
 await page.getByRole('switch', { name: 'Метнуть молнией', exact: true }).click()
 await page.evaluate(() => window.testRolls = [20, 2])
 await page.getByRole('menuitem', { name: 'Бросить на атаку', exact: true }).last().click()
 expect((await current(page)).weapon_use.attack_result).toMatchObject({ rollMode: 'disadvantage', total: 7 })
 expect((await current(page)).weapon_use.critical).toBe(false)
 expect((await current(page)).remaining).toBe(0)
 await page.goto(url + '?preset')
 await page.getByText('Импровизированное оружие', { exact: true }).click()
 await page.getByRole('menuitem', { name: 'Бросить на атаку', exact: true }).click()
 await page.getByRole('switch', { name: 'Преимущество', exact: true }).click()
 await page.evaluate(() => window.testRolls = [2, 19])
 await page.getByRole('menuitem', { name: 'Бросить на атаку', exact: true }).last().click()
 expect(await page.evaluate(() => window.attackResults.at(-1))).toMatchObject({ rollMode: 'advantage', total: 24 })
})
