import { test, expect } from '@playwright/test'
for (const width of [1280, 390]) test(`weapon panels start closed and charges remain usable (${width})`, async ({ page }) => {
  await page.setViewportSize({ width, height: 844 }); await page.goto('/tests/weapon-charges/weapon-panels.html')
  const magic = page.getByTestId('magic'), plain = page.getByTestId('plain')
  for (const details of await page.locator('details').all()) await expect(details).toHaveJSProperty('open', false)
  await expect(page.getByText('Ресурс', { exact: true })).toHaveCount(0)
  const resource = magic.locator('.item-mechanic-panel--resource')
  await expect(resource.locator('.item-mechanic-icon')).toHaveCount(0)
  await expect(resource.getByRole('group', { name: /из/ })).toBeVisible()
  const title = await resource.getByText('Заряды', { exact: true }).boundingBox(), pips = await resource.getByRole('group', { name: /из/ }).boundingBox()
  expect(title.x + title.width).toBeLessThan(pips.x)
  await resource.getByRole('button', { name: 'Заряд 1', exact: true }).click()
  await expect(resource.getByRole('group', { name: /из/ })).toHaveAttribute('aria-label', /0 из 1/)
  await expect(resource.locator('details')).toHaveJSProperty('open', false)
  await expect(magic.getByText('Спасбросок Ловкости Сл 13.', { exact: false })).toBeHidden()
  const lightning = magic.locator('summary').filter({ hasText: 'Метнуть молнией' })
  await lightning.focus(); await lightning.press('Enter')
  await expect(magic.getByText(/Молния образует линию/)).toBeVisible()
  await lightning.press('Space'); await expect(magic.getByText(/Молния образует линию/)).toBeHidden()
  await plain.locator('summary').click(); await expect(plain.getByText('Обычная дистанция: 30 футов.')).toBeVisible()
  await page.evaluate(() => window.ctx.ownerMode = false)
  await expect(resource.getByRole('button', { name: 'Заряд 1', exact: true })).toBeDisabled()
  await lightning.click(); await expect(magic.getByText(/Молния образует линию/)).toBeVisible()
  await expect(resource.getByRole('group', { name: /из/ })).toHaveAttribute('aria-label', /0 из 1/)
})
