import { test, expect } from '@playwright/test'
const url = '/tests/weapon-charges/weapon-panels.html'
for (const width of [1280,390]) test(`only concrete mechanics host charges, and presses stay on the main row (${width})`, async ({ page }) => {
 await page.setViewportSize({ width, height: 1000 }); await page.goto(url)
 const javelin = page.getByTestId('javelin'), mace = page.getByTestId('mace'), plain = page.getByTestId('plain')
 await expect(javelin.locator('.item-mechanic-panel')).toHaveCount(1)
 await expect(mace.locator('.item-mechanic-panel')).toHaveCount(1)
 await expect(plain.locator('.item-mechanic-panel')).toHaveCount(0)
 await expect(page.getByText(/Просто описание копья|Общее описание магического оружия/)).toHaveCount(0)
 await expect(page.locator('.item-mechanic-panel--resource')).toHaveCount(0)
 for (const details of await page.locator('details').all()) await expect(details).toHaveJSProperty('open',false)
 await expect(javelin.getByRole('group',{name:/из/})).toHaveAttribute('aria-label',/1 из 1/)
 await expect(mace.getByRole('group',{name:/из/})).toHaveAttribute('aria-label',/3 из 3/)
 await mace.getByRole('button',{name:'Заряд 3',exact:true}).click()
 await expect(mace.getByRole('group',{name:/из/})).toHaveAttribute('aria-label',/2 из 3/)
 await expect(mace.locator('details')).toHaveJSProperty('open',false)
 await expect(page.getByRole('menu')).toHaveCount(0)
 const summary = javelin.locator('summary')
 await summary.click(); await expect(javelin.getByText('Урон по линии',{exact:true})).toBeVisible()
 await expect.poll(() => javelin.locator('details').evaluate(element => element.getAnimations().length)).toBe(0)
 await expect(javelin.getByRole('button',{name:'Бросить на атаку',exact:true})).toHaveCount(0)
 await javelin.locator('.w-card-main').click()
 await page.getByRole('menuitem',{name:'Бросить на атаку',exact:true}).click()
 await page.getByRole('switch',{name:'Метнуть молнией',exact:true}).click()
 await page.getByRole('menuitem',{name:'Бросить на атаку',exact:true}).last().click()
 await expect(javelin.getByRole('group',{name:/из/})).toHaveAttribute('aria-label',/0 из 1/)
 await expect(javelin.locator('details')).toHaveJSProperty('open',true)
 await expect(javelin.getByRole('button',{name:'Бросить урон',exact:true})).toBeVisible()
 const scale = locator => locator.evaluate(element => new DOMMatrixReadOnly(getComputedStyle(element).transform).a)
 const box = await mace.locator('summary').boundingBox()
 await page.mouse.move(box.x+20,box.y+box.height/2); await page.mouse.down()
 expect(await scale(mace)).toBe(1); await expect.poll(() => scale(mace.locator('.ram-custom-trigger'))).toBe(1)
 await page.mouse.up()
 await expect.poll(() => mace.locator('details').evaluate(element => element.getAnimations().length)).toBe(0)
 const row = await mace.locator('.w-card-main').boundingBox()
 await page.mouse.move(row.x+20,row.y+row.height/2); await page.mouse.down()
 await expect.poll(() => scale(mace.locator('.ram-custom-trigger'))).toBeLessThan(0.995)
 expect(await scale(mace)).toBe(1); await page.mouse.up(); await page.keyboard.press('Escape')
 await expect(mace).toHaveCSS('border-top-width','1px')
 const border = await mace.boundingBox(); await page.mouse.move(border.x+20,border.y+0.5); await page.mouse.down()
 expect(await scale(mace)).toBe(1); expect((await mace.boundingBox()).y).toBe(border.y); await page.mouse.up()
 await page.evaluate(() => window.ctx.ownerMode=false)
 await expect(mace.getByRole('button',{name:'Заряд 1',exact:true})).toBeDisabled()
})
