import { test, expect } from '@playwright/test'
const url = '/tests/weapon-charges/weapon-use.html'
const current = page => page.evaluate(() => window.ctx.values.weapon[0].params.magic)
async function attack(page, natural = 10) {
 await page.evaluate(n => window.natural = n, natural)
 await page.getByLabel('Режим атаки', { exact: true }).selectOption('lightning_throw')
 expect((await current(page)).remaining).toBe(1)
 await page.getByRole('menuitem', { name: 'Бросить на атаку', exact: true }).click()
}
for (const width of [1280, 390]) test(`paid attack keeps line on miss, survives reload and move (${width})`, async ({ page }) => {
 await page.setViewportSize({ width, height: 844 }); await page.goto(url)
 await attack(page)
 expect((await current(page)).remaining).toBe(0)
 await page.getByRole('button', { name: 'Промах', exact: true }).click()
 await page.reload()
 await expect(page.getByText('Промах — урон по цели не наносится.')).toBeVisible()
 await page.getByRole('button', { name: 'Бросить урон', exact: true }).dblclick()
 await expect(page.getByText('При провале: 15')).toBeVisible()
 await expect(page.getByText('· При успехе: 7')).toBeVisible()
 expect(await page.evaluate(() => window.damageRolls)).toHaveLength(1)
 await page.evaluate(() => window.ctx.updateValues({ items: { sections: [{ items: window.ctx.values.weapon }] }, weapon: [] }))
 await page.reload()
 await expect(page.getByText('При провале: 15')).toBeVisible()
 await page.getByRole('button', { name: 'Завершить применение', exact: true }).click()
 expect(await page.evaluate(() => window.ctx.values.items.sections[0].items[0].params.magic)).toMatchObject({ remaining: 0, weapon_use: { status: 'completed' } })
})
test('critical affects the hit only; reader controls and unavailable mode are disabled', async ({ page }) => {
 await page.goto(url); await attack(page, 20)
 await expect(page.getByLabel('Критическое попадание: Урон по цели')).toBeChecked()
 await page.evaluate(() => window.ctx.ownerMode = false)
 await expect(page.getByRole('button', { name: 'Бросить урон', exact: true })).toHaveCount(0)
 await expect(page.getByLabel('Режим атаки', { exact: true }).locator('option[value="lightning_throw"]')).toBeDisabled()
 await page.evaluate(() => window.ctx.ownerMode = true)
 await page.getByRole('button', { name: 'Бросить урон', exact: true }).last().click()
 await page.getByRole('button', { name: 'Бросить урон', exact: true }).click()
 expect(await page.evaluate(() => window.damageRolls)).toEqual(['2d6{Колющий}+3{Колющий}+8d6{Молния|#ff0}', '4d6{Молния|#ff0}'])
 expect((await current(page)).remaining).toBe(0)
 await page.getByRole('button', { name: 'Завершить применение', exact: true }).click()
 await page.getByLabel('Режим атаки', { exact: true }).selectOption('')
 await page.getByRole('menuitem', { name: 'Бросить на атаку', exact: true }).click()
 expect(await page.evaluate(() => window.attacks)).toBe(2)
 expect((await current(page)).remaining).toBe(0)
})
test('editor shows dependent fields only and saves independent named steps', async ({ page }) => {
 await page.goto(url + '?editor')
 expect(await page.evaluate(() => window.editorError)).toBe('')
 await expect(page.getByLabel('Ресурс особого применения', { exact: true })).toHaveCount(0)
 await expect(page.getByLabel('Есть спасбросок', { exact: true })).toHaveCount(1)
 await page.getByLabel('Есть спасбросок', { exact: true }).click()
 expect(await page.evaluate(() => window.editorData.weapon_uses[0].steps[0].save)).toBeUndefined()
 await page.getByRole('button', { name: 'Добавить шаг после атаки', exact: true }).click()
 expect(await page.evaluate(() => window.editorError)).toContain('название')
 await page.getByRole('button', { name: 'Удалить шаг 3', exact: true }).click()
 await page.getByRole('button', { name: 'Удалить', exact: true }).click()
 expect(await page.evaluate(() => window.editorData.weapon_uses[0].steps.length)).toBe(2)
 expect(await page.evaluate(() => window.editorError)).toBe('')
})
