import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import SessionGraphCanvas from './SessionGraphCanvas.vue'

const source = readFileSync(fileURLToPath(new URL('./SessionGraphCanvas.vue', import.meta.url)), 'utf8')
const canvasSource = readFileSync(fileURLToPath(new URL('./NestedGraphCanvas.vue', import.meta.url)), 'utf8')
const dockSource = readFileSync(fileURLToPath(new URL('./CanvasActionDock.vue', import.meta.url)), 'utf8')
const blockSource = readFileSync(fileURLToPath(new URL('./SceneBlockNode.vue', import.meta.url)), 'utf8')
const entityBlockSource = readFileSync(fileURLToPath(new URL('./SceneEntityBlockPreview.vue', import.meta.url)), 'utf8')
const blockMenuSource = readFileSync(fileURLToPath(new URL('./SceneBlockMenus.vue', import.meta.url)), 'utf8')
const sceneSource = readFileSync(fileURLToPath(new URL('./SceneGraphNode.vue', import.meta.url)), 'utf8')
const sceneMenuSource = readFileSync(fileURLToPath(new URL('./SceneGraphMenus.vue', import.meta.url)), 'utf8')
const edgeMenuSource = readFileSync(fileURLToPath(new URL('./NestedEdgeMenus.vue', import.meta.url)), 'utf8')
const blockEditorSource = readFileSync(fileURLToPath(new URL('./SceneBlockEditorModal.vue', import.meta.url)), 'utf8')
const referenceCreateSource = readFileSync(fileURLToPath(new URL('./SceneReferenceCreateModal.vue', import.meta.url)), 'utf8')
const combatEditorSource = readFileSync(fileURLToPath(new URL('./SceneCombatCreaturesEditor.vue', import.meta.url)), 'utf8')
const sessionPageSource = readFileSync(fileURLToPath(new URL('../pages/ViewSession.vue', import.meta.url)), 'utf8')
const edgeEditorSource = readFileSync(fileURLToPath(new URL('../composables/useNestedEdgeEditor.js', import.meta.url)), 'utf8')
const apiSource = readFileSync(fileURLToPath(new URL('../../../shared/api/scenesApi.js', import.meta.url)), 'utf8')
const sessionsApiSource = readFileSync(fileURLToPath(new URL('../../../shared/api/sessionsApi.js', import.meta.url)), 'utf8')
const narrativeCanvasSource = readFileSync(fileURLToPath(new URL('../lib/narrativeCanvas.js', import.meta.url)), 'utf8')
const navigationSource = readFileSync(fileURLToPath(new URL('../composables/useSessionGraphNavigation.js', import.meta.url)), 'utf8')
const blockWorkflowSource = readFileSync(fileURLToPath(new URL('../composables/useSessionGraphBlockEditor.js', import.meta.url)), 'utf8')
const stylesSource = readFileSync(fileURLToPath(new URL('./styles/SessionGraphCanvas.css', import.meta.url)), 'utf8')

describe('session graph canvas', () => {
  it('compiles one persistent canvas host', () => {
    expect(SessionGraphCanvas).toBeTruthy()
    expect(source.match(/<NestedGraphCanvas/g)).toHaveLength(1)
    expect(source).toContain(':nodes="activeNodes"')
    expect(source).toContain(':edges="activeEdges"')
  })

  it('drills through scenarios and blocks while keeping ancestors as cards', () => {
    expect(navigationSource).toContain("activateLevel('scenes')")
    expect(navigationSource).toContain("activateLevel('blocks')")
    expect(navigationSource).toContain("transitionSpotlight.value = { level: 'scenes', id: scene.id, offset: 252 }")
    expect(source).toContain('class="session-graph-ancestor session-graph-ancestor--chapter"')
    expect(source).toContain('class="session-graph-ancestor session-graph-ancestor--scene"')
  })

  it('offers one explicit contextual back button above the ancestor chain', () => {
    expect(source).toContain('class="session-graph-back"')
    expect(source).toContain("displayLevel.value === 'blocks' ? 'К сценариям' : 'К главам'")
    expect(source).toContain("if (displayLevel.value === 'blocks') returnToScenes()")
    expect(source).toContain('else returnToChapters()')
    expect(source).toContain(':spotlight-y="activeSpotlightTop"')
    expect(stylesSource).toMatch(/\.session-graph-back\s*\{[^}]*top:\s*14px;[^}]*left:\s*var\(--chapter-safe-left/s)
    expect(stylesSource).toMatch(/\.session-graph-ancestor\s*\{[^}]*top:\s*54px;/s)
  })

  it('opens chapter actions from the pinned ancestor preview', () => {
    expect(source).toContain('@click.stop="openChapterAncestorMenu"')
    expect(source).toContain('@keydown.enter.stop.prevent="openChapterAncestorMenu"')
    expect(source).toContain("emit('chapter-ancestor-click', activeChapter.value, event.currentTarget)")
    expect(source).toContain("'chapter-ancestor-click', 'scene-count'")
  })

  it('keeps chapter and scenario action menus available during combat', () => {
    expect(source).toContain(':role="isDm ? \'button\' : undefined"')
    expect(source).toContain('if (!props.isDm || !selectedScene.value) return')
    expect(source).not.toContain("props.workspaceMode === 'combat' || !selectedScene.value")
    expect(canvasSource).toContain('@click.stop="onLockedNodeClick($event, node)"')
    expect(canvasSource).toContain("if (props.locked) emit('node-click', node, event.currentTarget)")
    expect(source).not.toContain("if (props.workspaceMode === 'combat') return")
    expect(navigationSource).toContain("emit('open-scenes', activeChapter.value)")
    expect(navigationSource).toContain("emit('open-chapters')")
    expect(source).toContain('syncWorkspaceScene(updated)')
    expect(source).toContain("level: props.workspaceMode === 'combat' ? props.workspaceLevel : displayLevel.value")
  })

  it('switches graph identity and camera atomically without cross-level node reuse', () => {
    expect(navigationSource).toContain("? 0 : 420")
    expect(navigationSource).toContain("canvas.value?.prepareView(graphKeyFor(level), level === 'chapters' ? 80 : 210)")
    expect(source).toContain('transitionSpotlight.value?.level === displayLevel.value')
    expect(navigationSource).toContain('requestAnimationFrame(() => {\n      requestAnimationFrame(() =>')
    expect(canvasSource).toContain(':key="`${graphKey}:${node.id}`"')
    expect(canvasSource).toContain('function prepareView(graphKey, initialTop)')
  })

  it('places contextual creation actions at the top-right of the canvas', () => {
    expect(source).toContain('<CanvasActionDock')
    expect(narrativeCanvasSource).toContain("label: 'Новая глава'")
    expect(narrativeCanvasSource).toContain("label: 'Новый сценарий'")
	expect(narrativeCanvasSource).toContain("{ id: 'text', label: 'Описание', icon: 'text', group: 'content' }")
	expect(narrativeCanvasSource).toContain("groupLabel: 'Объекты сессии'")
    expect(narrativeCanvasSource).toContain("label: 'Бой'")
    expect(dockSource).toContain('top: 16px;')
    expect(dockSource).not.toContain('translateY(-50%)')
    expect(dockSource).toContain('right: calc(var(--chapter-safe-right, 0px) + 8px);')
  })

  it('recomputes the chapter anchor when the combat player rail widens', () => {
    expect(source).toContain(':layout-key="workspaceLayoutMode"')
    expect(sessionPageSource).toContain(':workspace-mode="workspaceMode"')
    expect(sessionPageSource).toContain(':workspace-layout-mode="workspaceMotionMode"')
    expect(canvasSource).toContain('watch(() => props.layoutKey, async () => {')
    expect(canvasSource).toContain("{ flush: 'post' }")
  })

  it('keeps the selected chapter and scenario mounted across combat mode', () => {
    expect(navigationSource).toContain("const preservedNestedContext = previousMode === 'combat'")
    expect(navigationSource).toContain("if (previousMode !== 'scenes') displayLevel.value = 'chapters'")
    expect(navigationSource).not.toContain("if (mode === 'combat') {\n      rememberedChapterId = props.workspaceChapterId\n      displayLevel.value = 'chapters'")
    expect(source).toContain("'session-graph-canvas__nested--combat-hidden': workspaceMode === 'combat' && displayLevel !== 'chapters'")
    expect(stylesSource).toMatch(/\.session-graph-canvas__nested--combat-hidden\s*\{[^}]*opacity:\s*0;[^}]*pointer-events:\s*none;/s)
    expect(stylesSource).toContain('transition: left 0.42s cubic-bezier(0.22, 1, 0.36, 1);')
  })

  it('supports server-backed positions and directed links at every level', () => {
    expect(source).toContain("? 'fromChapterId' : displayLevel.value === 'scenes' ? 'fromSceneId' : 'fromItemId'")
    expect(source).toContain('sceneGraph.setLocalPositions')
    expect(source).toContain('blockGraph.setLocalPositions')
    expect(canvasSource).toContain('class="nested-graph-edge-line"')
    expect(canvasSource).toContain('class="nested-graph-link-port"')
    expect(apiSource).toContain('getSceneGraph')
    expect(apiSource).toContain('getSceneBlockGraph')
    expect(apiSource).toContain('createSceneBlockEdge')
  })

  it('persists and deletes selected nodes atomically at every graph level', () => {
    expect(source).toContain('@preview-positions="previewPositions"')
    expect(source).toContain('@save-positions="savePositions"')
    expect(source).toContain('@delete-selection="requestSelectionDelete"')
    expect(source).toContain("emit('delete-nodes', ids)")
    expect(source).toContain('sceneGraph.deleteScenes(value.ids)')
    expect(source).toContain('blockGraph.deleteItems(value.ids)')
    expect(sessionsApiSource).toContain('/graph-nodes/positions')
    expect(sessionsApiSource).toContain('/graph-nodes/delete')
  })

  it('offers canonical bulk statuses for chapter and scenario nodes', () => {
    expect(source).toContain("displayLevel === 'scenes' ? SCENE_STATUSES : []")
    expect(source).toContain("emit('change-nodes-status', status, ids)")
    expect(source).toContain('sceneGraph.updateSceneStatuses(ids, status)')
    expect(sessionsApiSource).toContain('/graph-nodes/status')
  })

  it('creates scenario and block transitions directly while keeping label editing available', () => {
    expect(source).toContain('<ChapterEdgeModal')
    expect(source).toContain('await createNestedEdge(displayLevel.value, from, node)')
    expect(edgeEditorSource).toContain('await graph.createEdge(from.id, to.id, null)')
    expect(edgeEditorSource).toContain('await graph.updateEdge(edge.id, { label })')
    expect(edgeEditorSource).not.toContain('pendingEdge')
    expect(edgeMenuSource).toContain('>Изменить подпись</RowActionItem>')
    expect(edgeMenuSource).toContain("run('toggle-direction')")
    expect(edgeMenuSource).toContain("v-if=\"!edge.bidirectional\"")
    expect(edgeMenuSource).toContain("run('reverse')")
    expect(edgeMenuSource).toContain('>Удалить переход</RowActionItem>')
    expect(apiSource).toContain('updateSceneEdge')
    expect(apiSource).toContain('updateSceneBlockEdge')
    expect(source).toContain('@rewire-edge="rewireEdge"')
    expect(canvasSource).toContain("onEdgeEndpointDown($event, edge, 'to')")
    expect(canvasSource).toContain(':d="edge.reversePath"')
    expect(canvasSource).toContain('stroke-dasharray="30 70"')
    expect(canvasSource).toContain("emit('rewire-edge', active.edge, from, to)")
    expect(canvasSource).toContain(':marker-start="edge.bidirectional')
    expect(canvasSource).toContain('graphEdgeGeometry(props.linkingFrom, linkPreviewTarget.value, nodeDimensions).path')
    expect(canvasSource).toContain("'nested-graph-node--link-preview-target'")
  })

  it('derives block presentation from type and opens actions from the whole card', () => {
    expect(blockSource).toContain('sceneBlockColor(block.type)')
    expect(blockSource).toContain('background: var(--surface);')
    expect(blockSource).not.toContain('background: var(--surface-raised);')
    expect(blockSource).not.toContain('RowActionMenu')
    expect(blockSource).not.toContain('Двойной клик')
    expect(source).toContain('blockMenus.value?.openFor(node, anchor)')
    expect(blockMenuSource).toContain('>Копировать</RowActionItem>')
    expect(blockEditorSource).toContain('<ColorPresetPicker')
    expect(blockEditorSource).toContain('setDialogueColor(row, color)')
    expect(blockEditorSource).toContain('<SceneRewardItemsEditor v-model="draft.items"')
    expect(blockSource).not.toContain('scene-block-node-strip')
    expect(blockSource).toContain('scene-block-node-dialogue')
    expect(blockSource).toContain('scene-block-node-dialogue-line')
    expect(blockSource).toContain('text-align: right;')
    expect(blockSource).not.toContain('background: color-mix(in srgb, var(--dialogue-color) 9%')
    expect(blockSource).toContain('var(--block-color) 52%')
    expect(blockSource).toContain('scene-block-node-heading')
    for (const type of ['text', 'list', 'combat', 'reward', 'image', 'location', 'npc', 'quest']) {
      expect(blockSource).toContain(`${type}:`)
    }
    expect(blockSource).toContain("props.block.type === 'material'")
    expect(blockSource).toContain('materialMeta.value.icon')
    expect(blockSource).toContain('font-size: 18px;')
    expect(blockEditorSource).toContain('placeholder="Участник"')
    expect(blockEditorSource).toContain(':list="dialogueKeysListId"')
	expect(narrativeCanvasSource).toContain("{ id: 'list', label: 'Диалог', icon: 'dialogue', group: 'content' }")
	expect(narrativeCanvasSource).toContain("{ id: 'reward', label: 'Награда', icon: 'reward', group: 'content' }")
    expect(dockSource).toContain("action.icon === 'dialogue'")
    expect(dockSource).toContain("action.icon === 'reward'")
    expect(blockSource).toContain(':item="itemById(creature.itemId)"')
    expect(blockSource).toContain("block.type === 'reward'")
	expect(narrativeCanvasSource).toContain("{ id: 'material', label: 'Материал', icon: 'material', group: 'reference' }")
	expect(narrativeCanvasSource).toContain("{ id: 'location', label: 'Локация'")
	expect(narrativeCanvasSource).toContain("{ id: 'npc', label: 'NPC'")
	expect(narrativeCanvasSource).toContain("{ id: 'quest', label: 'Задание'")
    expect(blockEditorSource).toContain('<WorldRelationPickerModal')
    expect(blockEditorSource).toContain("blockType.value === 'material'")
    expect(blockSource).toContain("block.type === 'material'")
    expect(blockMenuSource).toContain("block.type === 'image' || block.type === 'material'")
  })

  it('renders complete domain-specific previews for referenced session objects', () => {
    expect(blockSource).toContain('<SceneEntityBlockPreview')
    expect(blockSource).toContain("['location', 'npc', 'quest', 'material'].includes(block.type)")
    expect(entityBlockSource).toContain("type === 'location'")
    expect(entityBlockSource).toContain("type === 'npc'")
    expect(entityBlockSource).toContain("type === 'quest'")
    expect(entityBlockSource).toContain("type === 'material'")
    for (const field of ['Цель', 'Условие', 'Награда', 'Последствия', 'Заметки']) {
      expect(entityBlockSource).toContain(field)
    }
    expect(entityBlockSource).toContain('resolvedRelations')
    expect(entityBlockSource).toContain('Заметка в сценарии')
    expect(blockSource).toContain('scene-block-node-heading-icon')
    expect(entityBlockSource).not.toContain('scene-entity-quest-head')
    expect(entityBlockSource).not.toContain('scene-entity-material-head')
  })

  it('selects or creates catalogue references before placing them on the canvas', () => {
    expect(blockWorkflowSource).toContain('referenceBlockTypes.has(type)')
    expect(source).toContain(':fixed-type="creatingBlockType"')
    expect(source).toContain('@select="createReferenceBlock"')
    expect(source).toContain('<SceneReferenceCreateModal')
    expect(referenceCreateSource).toContain('<LocationEditorModal')
    expect(referenceCreateSource).toContain('<NpcEditorModal')
    expect(referenceCreateSource).toContain('<QuestEditorModal')
    expect(referenceCreateSource).toContain('<MaterialEditorModal')
    expect(blockEditorSource).toContain('v-if="!isReferenceBlock" label="Название"')
    expect(blockEditorSource).toContain('label="Заметка на холсте"')
    expect(blockSource).toContain('referenceEntity.value?.name')
	expect(blockWorkflowSource).toContain('refreshScenarioUsages')
	expect(blockWorkflowSource).toContain('sessionWorld?.load(true)')
	expect(blockWorkflowSource).toContain('sessionMaterials?.load(true)')
  })

  it('opens scenario actions from the whole card without an ellipsis trigger', () => {
    expect(sceneSource).not.toContain('RowActionMenu')
    expect(source).toContain('sceneMenus.value?.openFor(node, anchor)')
    expect(sceneMenuSource).toContain('>Редактировать</RowActionItem>')
    expect(sceneMenuSource).toContain('>Открыть элементы</RowActionItem>')
    expect(sceneMenuSource).toContain('Изменить статус')
    expect(sceneMenuSource).toContain('>Удалить</RowActionItem>')
    expect(source).toContain("sceneMenus.value?.openFor(selectedScene.value, event.currentTarget, 'ancestor')")
    expect(sceneMenuSource).toContain('>Вернуться к сценариям</RowActionItem>')
    expect(sceneSource).not.toContain('<span>СЦЕНАРИЙ</span>')
    expect(sceneSource).toContain("scene.status !== 'none'")
    expect(sceneSource).toContain('.scene-graph-node-visual {\n  position: absolute;\n  inset: 0;')
  })

  it('closes node action menus when a drag crosses the movement threshold', () => {
    expect(canvasSource).toContain("'change-selection-status', 'drag-start'")
    expect(canvasSource).toContain("if (active.moved && !wasMoved) emit('drag-start', active.node)")
    expect(source).toContain('@drag-start="handleDragStart"')
    expect(source).toContain("closeGraphMenus()\n  emit('drag-start')")
  })

  it('measures content height and persists width dragged from the right edge', () => {
    expect(source).toContain(':dynamic-node-height="displayLevel === \'blocks\'"')
    expect(source).toContain(':resizable-nodes="displayLevel === \'blocks\'"')
    expect(source).toContain('blockGraph.saveWidth')
    expect(canvasSource).toContain('class="nested-graph-resize-handle"')
    expect(canvasSource).toContain('new ResizeObserver(entries =>')
  })

  it('builds combat blocks from handbook and simplified creatures', () => {
    expect(combatEditorSource).toContain(':item-type-ids="[6]"')
    expect(combatEditorSource).toContain('Создать упрощённо')
    expect(blockMenuSource).toContain('>В бой</RowActionItem>')
    expect(blockWorkflowSource).toContain("emit('send-block-to-combat', {")
    expect(blockWorkflowSource).toContain('chapter: activeChapter.value')
    expect(blockWorkflowSource).toContain('scene: combatSceneContext()')
    expect(sessionPageSource).toContain('itemsApi.byIds(handbookIds)')
    expect(sessionPageSource).toContain('encounter.addNpc(item, count)')
    expect(sessionPageSource).toContain('encounter.addSimpleNpc(creature)')
    expect(sessionPageSource).toContain('await toggleCombatWorkspace({ chapter, scene, level })')
  })
})
