package store

import (
	"context"
	"encoding/json"
	"errors"
	"os"
	"strings"
	"testing"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

func TestItemEditorMigrationAndCoverOwnership(t *testing.T) {
	dsn := os.Getenv("DNDSHARE_ITEM_EDITOR_TEST_DSN")
	if dsn == "" {
		t.Skip("set DNDSHARE_ITEM_EDITOR_TEST_DSN to an empty local disposable database")
	}
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(cfg.ConnConfig.Database, "dndshare_test_") || (cfg.ConnConfig.Host != "127.0.0.1" && cfg.ConnConfig.Host != "localhost") {
		t.Fatal("requires a local dndshare_test_* database")
	}
	cfg.ConnConfig.DefaultQueryExecMode = pgx.QueryExecModeSimpleProtocol
	ctx := context.Background()
	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		t.Fatal(err)
	}
	defer pool.Close()
	exec := func(sql string, args ...any) {
		t.Helper()
		if _, err := pool.Exec(ctx, sql, args...); err != nil {
			t.Fatal(err)
		}
	}
	exec(`CREATE SCHEMA dndshare;
 CREATE TABLE dndshare.item_type (id bigint PRIMARY KEY, fields jsonb);
 CREATE TABLE dndshare.storage_image (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint, key text, url text, type text, file_name text, mime_type text, file_size bigint);
 CREATE TABLE dndshare.item (id bigint PRIMARY KEY, user_id bigint, icon_svg_id bigint, icon_image_id bigint, cover_image_id bigint);
 INSERT INTO dndshare.item VALUES (1, 10, 123, 456, 789), (2, NULL, NULL, 321, NULL);`)
	original := strings.Split(schemaStoryAbilitiesSQL, "$abilities$")[1]
	exec(`INSERT INTO dndshare.item_type SELECT id, $1::jsonb FROM unnest(ARRAY[3,4,18]) id; INSERT INTO dndshare.item_type VALUES (7,'[{"key":"untouched"}]');`, original)
	exec(schemaAbilityDependencyEditorSQL)
	var result json.RawMessage
	if err := pool.QueryRow(ctx, `SELECT fields FROM dndshare.item_type WHERE id=4`).Scan(&result); err != nil {
		t.Fatal(err)
	}
	var fields []map[string]any
	if err := json.Unmarshal(result, &fields); err != nil {
		t.Fatal(err)
	}
	found := false
	for _, field := range fields {
		if field["key"] == "choices" {
			for _, raw := range field["fields"].([]any) {
				child := raw.(map[string]any)
				if child["key"] == "source" {
					for _, option := range child["options"].([]any) {
						if option.(map[string]any)["value"] == "suggest_union" {
							found = true
						}
					}
				}
			}
		}
	}
	if !found {
		t.Fatal("combined source must be available after migration")
	}
	var same bool
	if err := pool.QueryRow(ctx, `SELECT count(DISTINCT fields)=1 FROM dndshare.item_type WHERE id IN (3,4,18)`).Scan(&same); err != nil || !same {
		t.Fatalf("ability schemas diverged: %v", err)
	}
	if err := pool.QueryRow(ctx, `SELECT fields='[{"key":"untouched"}]'::jsonb FROM dndshare.item_type WHERE id=7`).Scan(&same); err != nil || !same {
		t.Fatal("unrelated catalogue changed")
	}
	s := &Store{pool: pool}
	if _, _, err := s.SetItemCoverImage(ctx, 1, 20, false, "bad", "bad", "bad", "image/png", 1); !errors.Is(err, ErrNotFound) {
		t.Fatalf("non-owner could change cover: %v", err)
	}
	id, refs, err := s.SetItemCoverImage(ctx, 1, 10, false, "cover", "/cover", "cover.jpg", "image/jpeg", 12)
	if err != nil || refs.CoverImageID == nil || *refs.CoverImageID != 789 || refs.ImageID != nil || refs.SVGID != nil {
		t.Fatalf("wrong replaced refs: %+v %v", refs, err)
	}
	var owner int64
	if err := pool.QueryRow(ctx, `SELECT user_id FROM dndshare.storage_image WHERE id=$1`, id).Scan(&owner); err != nil || owner != 10 {
		t.Fatal("cover must belong to item owner")
	}
	if _, err := s.ClearItemCover(ctx, 1, 20, false); !errors.Is(err, ErrNotFound) {
		t.Fatal("non-owner could clear cover")
	}
	refs, err = s.ClearItemCover(ctx, 1, 10, false)
	if err != nil || refs.CoverImageID == nil || *refs.CoverImageID != id {
		t.Fatalf("wrong cleared cover: %+v %v", refs, err)
	}
	var svg, icon int64
	var cover *int64
	if err := pool.QueryRow(ctx, `SELECT icon_svg_id,icon_image_id,cover_image_id FROM dndshare.item WHERE id=1`).Scan(&svg, &icon, &cover); err != nil || svg != 123 || icon != 456 || cover != nil {
		t.Fatal("cover edit must preserve icon")
	}
	if _, _, err = s.SetItemCoverImage(ctx, 2, 10, false, "system", "/system", "cover.png", "image/png", 10); !errors.Is(err, ErrNotFound) {
		t.Fatal("system image requires administrator")
	}
	id, _, err = s.SetItemCoverImage(ctx, 2, 20, true, "system", "/system", "cover.png", "image/png", 10)
	if err != nil {
		t.Fatal(err)
	}
	if err := pool.QueryRow(ctx, `SELECT user_id IS NULL FROM dndshare.storage_image WHERE id=$1`, id).Scan(&same); err != nil || !same {
		t.Fatal("system image must stay system-owned")
	}
}
