import { test, expect } from '@playwright/test'

for (const mobile of [false, true]) test(`character bag layouts and moves on ${mobile ? 'mobile' : 'desktop'}`, async ({ page }) => {
  await page.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1280, height: 1000 })
  page.on('pageerror', error => { throw error })
  await page.route('**/api/**', route => new URL(route.request().url()).pathname.startsWith('/api/') ? route.fulfill({ json: { types: [], items: [] } }) : route.continue())
  await page.goto('/tests/notifications/fixtures/inventory.html')
  const bag = page.locator('[data-sortable-container="sec_bag"]')
  const chest = page.locator('[data-sortable-container="sec_chest"]')
  const equipped = page.locator('[data-sortable-container="sec_equipped"]')
  await expect(bag.locator('.inventory-bag-cell')).toHaveCount(4)
  await expect(equipped.locator('.di-row')).toHaveCount(1)
  await expect(page.getByRole('radiogroup', { name: 'Вид секции Экипировано' })).toHaveCount(0)
  const cell = (container, index) => container.locator(`[data-sortable-slot="${index}"]`)
  async function drag(source, target) {
    await source.scrollIntoViewIfNeeded()
    const from = await source.boundingBox(), to = await target.boundingBox()
    await page.mouse.move(from.x + from.width / 2, from.y + from.height / 2)
    await page.mouse.down()
    await page.mouse.move(to.x + to.width / 2, to.y + to.height / 2, { steps: 8 })
    await page.mouse.up()
  }
  await drag(cell(bag, 0), cell(bag, 1))
  await expect(cell(bag, 0).getByRole('button', { name: 'Факел', exact: true })).toBeVisible()
  await expect(cell(bag, 1).getByRole('button', { name: 'Верёвка', exact: true })).toBeVisible()
  await drag(cell(bag, 1), cell(chest, 0))
  await expect(cell(bag, 1).getByRole('button', { name: 'Камень', exact: true })).toBeVisible()
  await expect(cell(chest, 0).getByRole('button', { name: 'Верёвка', exact: true })).toBeVisible()
  await drag(cell(bag, 0), cell(bag, 3))
  await expect(cell(bag, 0).locator('.inventory-bag-item')).toHaveCount(0)
  await expect(bag.locator('.inventory-bag-cell')).toHaveCount(4)
  const mode = page.getByRole('radiogroup', { name: 'Вид секции Рюкзак', exact: true })
  await mode.getByRole('radio', { name: 'Список', exact: true }).click()
  await expect(bag.locator('.di-row')).toHaveCount(2)
  await expect(bag.locator('.inventory-bag-cell')).toHaveCount(0)
  await page.reload()
  await expect(mode.getByRole('radio', { name: 'Список', exact: true })).toHaveAttribute('aria-checked', 'true')
  await mode.getByRole('radio', { name: 'Рюкзак', exact: true }).click()
  await expect(cell(bag, 3).getByRole('button', { name: 'Факел', exact: true })).toBeVisible()
  await expect(cell(bag, 1).getByRole('button', { name: 'Камень', exact: true })).toBeVisible()
  await drag(cell(bag, 1), equipped.locator('.di-row'))
  await expect(equipped.locator('.di-row')).toHaveCount(2)
  await expect(cell(bag, 1).locator('.inventory-bag-item')).toHaveCount(0)
  // Grid menus remain accessible after drag suppression ends.
  await cell(bag, 3).getByRole('button', { name: 'Факел', exact: true }).focus()
  await expect.poll(() => page.evaluate(() => document.querySelector('.ram-popover') != null)).toBe(false)
  await expect(cell(bag, 3).getByRole('button', { name: 'Факел', exact: true })).toHaveAttribute('aria-disabled', 'false')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('menuitem', { name: 'Добавить +1', exact: true })).toBeVisible()
})

test('character viewer can switch layouts but cannot drag items', async ({ page }) => {
  await page.route('**/api/**', route => new URL(route.request().url()).pathname.startsWith('/api/') ? route.fulfill({ json: { types: [], items: [] } }) : route.continue())
  await page.goto('/tests/notifications/fixtures/inventory.html?viewer')
  const bag = page.locator('[data-sortable-container="sec_bag"]')
  const source = await bag.locator('[data-sortable-slot="0"]').boundingBox()
  const target = await bag.locator('[data-sortable-slot="2"]').boundingBox()
  const before = await page.evaluate(() => window.readInventory())
  await page.mouse.move(source.x + 20, source.y + 20)
  await page.mouse.down()
  await page.mouse.move(target.x + 20, target.y + 20, { steps: 6 })
  await page.mouse.up()
  expect(await page.evaluate(() => window.readInventory())).toEqual(before)
  await page.getByRole('radiogroup', { name: 'Вид секции Рюкзак', exact: true }).getByRole('radio', { name: 'Список', exact: true }).click()
  await expect(bag.locator('.di-row')).toHaveCount(2)
})
