import { test, expect } from '@playwright/test'
import { inventoryCatalogue, inventoryTypes } from './fixtures/inventoryData'
const mockInventory = page => page.route('**/api/**', route => new URL(route.request().url()).pathname.startsWith('/api/') ? route.fulfill({ json: { types: inventoryTypes, items: inventoryCatalogue } }) : route.continue())

for (const mobile of [false, true]) test(`character bag layouts and moves on ${mobile ? 'mobile' : 'desktop'}`, async ({ page }) => {
  await page.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1280, height: 1000 })
  page.on('pageerror', error => { throw error })
  await mockInventory(page)
  await page.goto('/tests/notifications/fixtures/inventory.html')
  const bag = page.locator('[data-sortable-container="sec_bag"]')
  const chest = page.locator('[data-sortable-container="sec_chest"]')
  await expect(page.locator('.di-inventory.base-tile')).toHaveCount(1)
  await expect(page.locator('[data-sortable-container="sec_equipped"]')).toHaveCount(0)
  await expect(page.getByRole('radiogroup')).toHaveCount(0)
  await expect(bag.locator('[data-sortable-slot="2"]')).toHaveClass(/inventory-bag-cell--equipped/)
  await expect(bag.locator('.inventory-bag-cell')).toHaveCount(mobile ? 4 : 8)
  await bag.getByRole('button', { name: 'Верёвка', exact: true }).hover()
  await expect(page.getByRole('tooltip')).toContainText('Описание: Верёвка')
  const cell = (container, index) => container.locator(`[data-sortable-slot="${index}"]`)
  async function drag(source, target) {
    await source.scrollIntoViewIfNeeded()
    const from = await source.boundingBox(), to = await target.boundingBox()
    await page.mouse.move(from.x + from.width / 2, from.y + from.height / 2)
    await page.mouse.down()
    await page.mouse.move(to.x + to.width / 2, to.y + to.height / 2, { steps: 8 })
    await page.mouse.up()
  }
  await drag(cell(bag, 0), cell(bag, 1))
  await expect(cell(bag, 0).getByRole('button', { name: 'Факел', exact: true })).toBeVisible()
  await expect(cell(bag, 1).getByRole('button', { name: 'Верёвка', exact: true })).toBeVisible()
  await drag(cell(bag, 1), cell(chest, 0))
  await expect(cell(bag, 1).getByRole('button', { name: 'Камень', exact: true })).toBeVisible()
  await expect(cell(chest, 0).getByRole('button', { name: 'Верёвка', exact: true })).toBeVisible()
  await drag(cell(bag, 0), cell(bag, 3))
  await expect(cell(bag, 0).locator('.inventory-bag-item')).toHaveCount(0)
  await expect(bag.locator('.inventory-bag-cell')).toHaveCount(mobile ? 4 : 8)
  await page.reload()
  await expect(cell(bag, 3).getByRole('button', { name: 'Факел', exact: true })).toBeVisible()
  await expect(cell(bag, 1).getByRole('button', { name: 'Камень', exact: true })).toBeVisible()
  await drag(cell(bag, 2), cell(chest, 3))
  await expect(cell(chest, 3).getByRole('button', { name: 'Плащ', exact: true })).toBeVisible()
  await expect(cell(chest, 3)).toHaveClass(/inventory-bag-cell--equipped/)
  expect((await page.evaluate(() => window.readInventory())).equipped.map(entry => entry.uid)).toEqual(['worn'])
  // Grid menus remain accessible after drag suppression ends.
  await cell(bag, 3).getByRole('button', { name: 'Факел', exact: true }).focus()
  await expect.poll(() => page.evaluate(() => document.querySelector('.ram-popover') != null)).toBe(false)
  await expect(cell(bag, 3).getByRole('button', { name: 'Факел', exact: true })).toHaveAttribute('aria-disabled', 'false')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('menuitem', { name: 'Добавить +1', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  const beforeResize = await page.evaluate(() => window.readInventory())
  await page.setViewportSize(mobile ? { width: 1280, height: 1000 } : { width: 390, height: 844 })
  await expect(bag.locator('.inventory-bag-cell')).toHaveCount(mobile ? 8 : 4)
  expect(await page.evaluate(() => window.readInventory())).toEqual(beforeResize)
})

test('character viewer cannot drag or change equipment', async ({ page }) => {
  await mockInventory(page)
  await page.goto('/tests/notifications/fixtures/inventory.html?viewer')
  const bag = page.locator('[data-sortable-container="sec_bag"]')
  const source = await bag.locator('[data-sortable-slot="0"]').boundingBox()
  const target = await bag.locator('[data-sortable-slot="2"]').boundingBox()
  await expect(bag.getByRole('button', { name: /Добавить предмет в ячейку/ })).toHaveCount(0)
  const before = await page.evaluate(() => window.readInventory())
  await page.mouse.move(source.x + 20, source.y + 20)
  await page.mouse.down()
  await page.mouse.move(target.x + 20, target.y + 20, { steps: 6 })
  await page.mouse.up()
  expect(await page.evaluate(() => window.readInventory())).toEqual(before)
  await expect(page.getByRole('radiogroup')).toHaveCount(0)
  await bag.getByRole('button', { name: 'Плащ', exact: true }).click()
  await expect(page.getByRole('menuitem', { name: 'Снять', exact: true })).toHaveCount(0)
})


for (const mobile of [false, true]) test(`character empty cell opens add menu on ${mobile ? 'mobile' : 'desktop'}`, async ({ page }) => {
  await page.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1280, height: 1000 })
  page.on('pageerror', error => { throw error })
  await mockInventory(page)
  await page.goto('/tests/notifications/fixtures/inventory.html')
  const bag = page.locator('[data-sortable-container="sec_bag"]')
  await expect(bag.locator('..').locator('.di-add-row')).toHaveCount(0)
  const empty = bag.getByRole('button', { name: 'Добавить предмет в ячейку 4', exact: true })
  await empty.hover()
  await expect(empty.locator('.inventory-bag-add__plus')).toHaveCSS('opacity', '1')
  await expect(empty.locator('.inventory-bag-add__bag')).toHaveCSS('opacity', '0')
  await empty.click()
  await page.getByRole('menuitem', { name: 'Добавить из справочника', exact: true }).click()
  const picker = page.getByRole('dialog', { name: 'Предметы', exact: true })
  await expect(picker).toBeVisible()
  await picker.getByRole('button', { name: 'Close', exact: true }).click()
  await empty.focus()
  await page.keyboard.press('Enter')
  await page.getByRole('menuitem', { name: 'Добавить своё', exact: true }).click()
  const form = page.getByRole('dialog', { name: 'Новый предмет', exact: true })
  await expect(form).toBeVisible()
  await form.getByRole('textbox', { name: 'Название', exact: true }).fill('Мел')
  await form.getByRole('textbox', { name: 'Описание', exact: true }).fill('Белый мел для пометок')
  await form.getByRole('button', { name: 'Создать', exact: true }).click()
  const item = bag.getByRole('button', { name: 'Мел', exact: true })
  await expect(item).toBeVisible()
  await item.hover()
  await expect(page.getByRole('tooltip')).toContainText('Белый мел для пометок')
})


for (const mobile of [false, true]) test(`equipment stays in its cell with rounded purple frame on ${mobile ? 'mobile' : 'desktop'}`, async ({ page }) => {
  await page.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1280, height: 1000 })
  await mockInventory(page)
  await page.goto('/tests/notifications/fixtures/inventory.html')
  const chest = page.locator('[data-sortable-container="sec_chest"]')
  const cell = chest.locator('[data-sortable-slot="1"]')
  const item = cell.getByRole('button', { name: 'Кожаный доспех', exact: true })
  await expect(item).toBeVisible()
  const radius = await item.evaluate(element => getComputedStyle(element).borderRadius)
  expect(radius).not.toBe('0px')
  await item.click()
  const menu = page.getByRole('menu')
  await expect(menu.locator('.inventory-menu-name + [role="separator"]')).toHaveCount(1)
  expect(await item.evaluate(element => getComputedStyle(element).borderRadius)).toBe(radius)
  await page.getByRole('menuitem', { name: 'Экипировать', exact: true }).click()
  await expect(cell).toHaveClass(/inventory-bag-cell--equipped/)
  await expect(item).toHaveAttribute('aria-description', 'Экипировано')
  const frame = await cell.evaluate(element => ({ width: getComputedStyle(element, '::after').borderTopWidth, color: getComputedStyle(element, '::after').borderColor, accent: getComputedStyle(element).getPropertyValue('--accent').trim() }))
  expect(frame.width).toBe('2px')
  expect(frame.color).toBe('rgb(124, 92, 226)')
  let value = await page.evaluate(() => window.readInventory())
  expect(value.equipped.map(entry => entry.uid)).toContain('armor')
  expect(value.sections[1].slots.armor).toBe(1)
  await page.reload()
  await expect(cell).toHaveClass(/inventory-bag-cell--equipped/)
  await item.click()
  expect(await item.evaluate(element => getComputedStyle(element).borderRadius)).toBe(radius)
  await page.getByRole('menuitem', { name: 'Снять', exact: true }).click()
  await expect(cell).not.toHaveClass(/inventory-bag-cell--equipped/)
  value = await page.evaluate(() => window.readInventory())
  expect(value.equipped.map(entry => entry.uid)).not.toContain('armor')
  expect(value.sections[1].items.find(entry => entry.uid === 'armor')).toBeTruthy()
  await page.locator('[data-sortable-container="sec_bag"]').getByRole('button', { name: 'Верёвка', exact: true }).click()
  await expect(page.getByRole('menuitem', { name: 'Экипировать', exact: true })).toHaveCount(0)
})

test('empty cell has smooth enter/leave and supports reduced motion', async ({ page }) => {
  await mockInventory(page)
  await page.goto('/tests/notifications/fixtures/inventory.html')
  const empty = page.locator('[data-sortable-container="sec_bag"]').getByRole('button', { name: 'Добавить предмет в ячейку 4', exact: true })
  const plus = empty.locator('.inventory-bag-add__plus')
  const duration = await plus.evaluate(element => getComputedStyle(element).transitionDuration)
  expect(duration).toContain('0.18s')
  await empty.hover()
  await expect(plus).toHaveCSS('opacity', '1')
  await page.mouse.move(0, 0)
  await expect(plus).toHaveCSS('opacity', '0')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(plus).toHaveCSS('transition-duration', '0s')
})
