import { test, expect } from '@playwright/test'
test.beforeEach(async ({ page }) => {
  page.on('pageerror', error => { console.error('BROWSER ERROR:', error.message) })
  await page.route('**/api/**', route => new URL(route.request().url()).pathname.startsWith('/api/') ? route.fulfill({json: {items: []}}) : route.continue())
  await page.goto('/tests/performance/interactions.html')
})
test('search selection, limit, removal and creation work with keyboard and pointer', async ({page}) => {
  const input = page.getByRole('combobox', {name: 'Навыки'})
  await input.fill('Акро')
  await input.press('Enter')
  await expect(page.locator('[data-testid="search"] > output').first()).toHaveText('1')
  await input.fill('Маг')
  await page.getByRole('option', {name: 'Магия'}).click()
  await expect(input).toHaveCount(0)
  await page.getByRole('button', {name: 'Remove: Акробатика'}).click()
  await input.fill('Новое')
  await page.getByRole('button', {name: 'Add «Новое»'}).click()
  await expect(page.locator('[data-testid="search"] > output').first()).toHaveText('3,4')
  await page.getByRole('button', {name: 'Вариант', exact: true}).click()
  const suggest = page.getByRole('combobox', {name: 'Вариант'})
  await suggest.press('ArrowDown')
  await expect(suggest).toHaveAttribute('aria-activedescendant', /-1$/)
  await suggest.press('Enter')
  await expect(page.getByTestId('suggestion')).toHaveText('Второй')
})
test('tooltip clamps to viewport and restores anchor description', async ({page}) => {
  await page.setViewportSize({width: 390, height: 844})
  const anchor = page.getByRole('button', {name: 'Подсказка'})
  await anchor.click()
  const tooltip = page.getByRole('tooltip')
  await expect(tooltip).toBeVisible()
  const box = await tooltip.boundingBox()
  expect(box.x).toBeGreaterThanOrEqual(0); expect(box.y).toBeGreaterThanOrEqual(0)
  expect(box.x + box.width).toBeLessThanOrEqual(390)
  expect(box.y + box.height).toBeLessThanOrEqual(844)
  await expect(anchor).toHaveAttribute('aria-describedby', await tooltip.getAttribute('id'))
  await anchor.click()
  await expect(anchor).not.toHaveAttribute('aria-describedby')
})
test('variable-height virtual rows reach the end, preserve focus and survive filtering', async ({page}) => {
  const rows = page.locator('.list-row'), scroller = page.locator('.list-body')
  await expect(rows.first()).toBeVisible()
  expect(await rows.count()).toBeLessThan(50)
  await rows.first().focus()
  await page.keyboard.press('Enter')
  await expect(page.getByTestId('activated')).toHaveText('1')
  await scroller.evaluate(el => { el.scrollTop = el.scrollHeight })
  await expect(page.locator('.list-row').filter({hasText: /^Предмет 2000$/})).toBeVisible()
  expect(await rows.count()).toBeLessThan(50)
  expect(await page.evaluate(() => document.activeElement?.textContent)).toContain('Предмет 1')
  await page.getByRole('button', {name: 'Десять', exact: true}).click()
  await expect(rows).toHaveCount(10)
  await expect(rows.first()).toBeVisible()
})
test('grouped list preserves counts and all entries behind collapsed groups', async ({page}) => {
  await page.getByRole('button', {name: 'Группы', exact: true}).click()
  const groups = page.locator('.item-group-header')
  await expect(groups).toHaveCount(2)
  await expect(groups.first()).toContainText('1000')
  await expect(page.locator('.list-row')).toHaveCount(0)
  await groups.first().click()
  await expect(page.locator('.list-row').first()).toBeVisible()
  await expect(groups.first()).toHaveAttribute('aria-expanded', 'true')
  await groups.first().click()
  await expect(page.locator('.list-row')).toHaveCount(0)
})
