import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import DiceRollPopup from '../../../shared/ui/DiceRollPopup.vue'
import ViewSession from './ViewSession.vue'

const source = readFileSync(fileURLToPath(new URL('./ViewSession.vue', import.meta.url)), 'utf8')
const styles = readFileSync(fileURLToPath(new URL('./styles/ViewSession.css', import.meta.url)), 'utf8')
const selectionSource = readFileSync(fileURLToPath(new URL('../composables/useSessionSelection.js', import.meta.url)), 'utf8')
const workspaceSource = readFileSync(fileURLToPath(new URL('../composables/useSessionWorkspace.js', import.meta.url)), 'utf8')
const dicePanelSource = readFileSync(fileURLToPath(new URL('../components/DicePanel.vue', import.meta.url)), 'utf8')
const musicPanelSource = readFileSync(fileURLToPath(new URL('../components/MusicPanel.vue', import.meta.url)), 'utf8')
const musicWorkspaceSource = readFileSync(fileURLToPath(new URL('../components/SessionMusicWorkspace.vue', import.meta.url)), 'utf8')
const centerWorkspaceSource = readFileSync(fileURLToPath(new URL('../components/SessionCenterWorkspace.vue', import.meta.url)), 'utf8')
const encounterSource = readFileSync(fileURLToPath(new URL('../components/EncounterTab.vue', import.meta.url)), 'utf8')
const encounterComposableSource = readFileSync(fileURLToPath(new URL('../composables/useEncounter.js', import.meta.url)), 'utf8')
const graveyardSource = readFileSync(fileURLToPath(new URL('../components/EncounterGraveyardMenu.vue', import.meta.url)), 'utf8')
const encounterRowSource = readFileSync(fileURLToPath(new URL('../components/EncounterRow.vue', import.meta.url)), 'utf8')
const encounterAvatarSource = readFileSync(fileURLToPath(new URL('../components/EncounterAvatar.vue', import.meta.url)), 'utf8')
const encounterControlsSource = readFileSync(fileURLToPath(new URL('../components/EncounterCombatControls.vue', import.meta.url)), 'utf8')
const encounterMarkerSource = readFileSync(fileURLToPath(new URL('../components/EncounterMarkerMenu.vue', import.meta.url)), 'utf8')
const encounterMenuSource = readFileSync(fileURLToPath(new URL('../components/EncounterRowMenu.vue', import.meta.url)), 'utf8')
const encounterFlowSource = readFileSync(fileURLToPath(new URL('../composables/useEncounterFlow.js', import.meta.url)), 'utf8')
const encounterHpSource = readFileSync(fileURLToPath(new URL('../composables/useEncounterHp.js', import.meta.url)), 'utf8')
const reviveModalSource = readFileSync(fileURLToPath(new URL('../components/EncounterReviveModal.vue', import.meta.url)), 'utf8')
const encounterStatesSource = readFileSync(fileURLToPath(new URL('../composables/useEncounterStates.js', import.meta.url)), 'utf8')
const encounterTransitionSource = readFileSync(fileURLToPath(new URL('../composables/useEncounterCombatTransition.js', import.meta.url)), 'utf8')
const encounterChallengeSource = readFileSync(fileURLToPath(new URL('../composables/useEncounterChallenge.js', import.meta.url)), 'utf8')
const encounterChallengeMenuSource = readFileSync(fileURLToPath(new URL('../components/EncounterChallengeMenu.vue', import.meta.url)), 'utf8')
const encounterChallengeResultSource = readFileSync(fileURLToPath(new URL('../components/EncounterChallengeResult.vue', import.meta.url)), 'utf8')
const encounterOrderSource = readFileSync(fileURLToPath(new URL('../components/EncounterOrderMarker.vue', import.meta.url)), 'utf8')
const sessionGraphSource = readFileSync(fileURLToPath(new URL('../components/SessionGraphCanvas.vue', import.meta.url)), 'utf8')
const nestedGraphSource = readFileSync(fileURLToPath(new URL('../components/NestedGraphCanvas.vue', import.meta.url)), 'utf8')
const createModalSource = readFileSync(fileURLToPath(new URL('../../character-list/components/CharacterCreateWizardModal.vue', import.meta.url)), 'utf8')
const createWizardSource = readFileSync(fileURLToPath(new URL('../../character-list/pages/ViewCreateCharacter.vue', import.meta.url)), 'utf8')
const participantSyncSource = readFileSync(fileURLToPath(new URL('../composables/useParticipantSync.js', import.meta.url)), 'utf8')
const sessionLiveSource = readFileSync(fileURLToPath(new URL('../composables/useSessionLive.js', import.meta.url)), 'utf8')
const participantRailSource = readFileSync(fileURLToPath(new URL('../composables/useSessionParticipantRail.js', import.meta.url)), 'utf8')
const sessionSettingsSource = readFileSync(fileURLToPath(new URL('../composables/useSessionSettings.js', import.meta.url)), 'utf8')
const sessionSettingsControlSource = readFileSync(fileURLToPath(new URL('../components/SessionSettingsControl.vue', import.meta.url)), 'utf8')
const encounterNpcsSource = readFileSync(fileURLToPath(new URL('../composables/useEncounterNpcs.js', import.meta.url)), 'utf8')
const encounterStylesSource = readFileSync(fileURLToPath(new URL('../components/styles/EncounterTab.css', import.meta.url)), 'utf8')
const dicePopupSource = readFileSync(fileURLToPath(new URL('../../../shared/ui/DiceRollPopup.vue', import.meta.url)), 'utf8')
const sessionHotkeysSource = readFileSync(fileURLToPath(new URL('../composables/useSessionHotkeys.js', import.meta.url)), 'utf8')
const shortcutHelpSource = readFileSync(fileURLToPath(new URL('../components/SessionShortcutHelp.vue', import.meta.url)), 'utf8')

describe('ViewSession participant rail', () => {
  it('compiles the page component', () => {
    expect(ViewSession).toBeTruthy()
  })

  it('keeps player actions in the heading menu instead of a bottom invite tile', () => {
    expect(source).toContain('<div class="players-actions">')
    expect(source).toContain('<RowActionMenu>')
    expect(source).toContain('class="players-actions-trigger"')
    expect(source).toContain('<RowActionItem action="join"')
    expect(source).toContain('Присоединить своего персонажа')
    expect(source).toContain('<RowActionItem action="create"')
    expect(source).toContain('<RowActionItem action="copy"')
    expect(source).toContain('<RowActionItem action="copy-link"')
    expect(source).not.toContain('invite-section')
  })

  it('attaches an existing owned character without leaving the session workspace', () => {
    expect(source).toContain('<SessionJoinModal')
    expect(source).toContain(':redirect-on-join="false"')
    expect(source).toContain('@joined="handleOwnCharacterJoined"')
    expect(source).toContain('await refreshParticipants()')
  })

  it('creates a character through the full modal wizard and attaches it without opening the sheet', () => {
    expect(source).toContain('<CharacterCreateWizardModal')
    expect(createModalSource).toContain('<AppModal fullscreen')
    expect(createModalSource).toContain('<CharacterCreateWizardWorkspace')
    expect(createWizardSource).toContain("if (props.embedded) {\n    emit('create', payload)")
    expect(source).toContain('await joinSession(sessionUuid, res.charId)')
    expect(source).toContain('participants.value = fresh.participants')
    expect(source).toContain('createModalRef.value?.clearDraft()')
    expect(source).not.toContain('if (res?.uuid) sheetUuid.value = res.uuid')
    expect(participantSyncSource).toContain('pendingCharacterIds')
    expect(participantSyncSource).toContain('await refreshParticipants()')
    expect(participantSyncSource).not.toContain('setInterval')
    expect(sessionLiveSource).toContain('new EventSource')
    expect(sessionLiveSource).toContain('runCatchUp()')
  })

  it('uses the chapter canvas as the full workspace with tools floating above it', () => {
    expect(source).toContain('class="campaign-workspace"')
    expect(source).toContain('class="campaign-graph"')
    expect(source).toContain('workspace-dock workspace-dock--left')
    expect(source).toContain('workspace-dock workspace-dock--right')
    expect(styles).toContain('.campaign-workspace {')
    expect(styles).toContain('position: absolute;')
    expect(styles).toContain('--chapter-safe-left: 306px;')
    expect(styles).toContain('.campaign-workspace--right-dock .campaign-graph')
    expect(styles).toContain('--chapter-safe-right: 350px;')
    expect(source).not.toContain('campaign-workspace--hotkeys')
    expect(styles).not.toContain('.campaign-workspace--hotkeys .workspace-dock--left')
    expect(source).not.toContain('<SlidingTabs')
    expect(source).not.toContain('<SessionTopBar')
  })

  it('limits the left rail hit area to its player content', () => {
    expect(styles).toMatch(/\.workspace-dock--left\s*\{[^}]*bottom:\s*auto;[^}]*max-height:\s*calc\(100% - 84px\);/s)
  })

  it('moves the player rail through compact, normal and combat states without losing the saved preference', () => {
    expect(source).toContain("'campaign-workspace--players-collapsed': playersRailMode === 'compact'")
    expect(source).toContain('useSessionParticipantRail({ sessionUuid, workspaceMotionMode: visibleWorkspaceMotionMode })')
    expect(participantRailSource).toContain('dnd-share:session-players-rail:v1:')
    expect(participantRailSource).toContain("localStorage.setItem(storageKey, value ? 'collapsed' : 'normal')")
    expect(participantRailSource).toContain("const mode = computed(() => workspaceMotionMode.value === 'combat'")
    expect(participantRailSource).toContain("? 'combat'\n    : collapsed.value ? 'compact' : 'normal'")
    expect(participantRailSource).toContain("if (mode.value === 'combat') return")
    expect(source).toContain(':compact="playersRailMode === \'compact\'"')
    expect(source).toContain('<PanelLeftOpen v-if="playersRailMode === \'compact\'"')
    expect(source).toContain(':disabled="playersRailMode === \'combat\'"')
    expect(source).toContain('@click="togglePlayersRail"')
    expect(source).toContain("'players-rail-toggle--error': kickError || colorError || participantOrderError")
    expect(styles).toMatch(/\.campaign-workspace--players-collapsed \.campaign-graph\s*\{[^}]*--chapter-safe-left:\s*94px;/s)
    expect(styles).toMatch(/\.campaign-workspace--players-collapsed \.workspace-dock--left\s*\{[^}]*width:\s*52px;/s)
    expect(styles).toMatch(/\.workspace-dock--left\s*\{[^}]*width:\s*264px;/s)
    expect(styles).toMatch(/\.campaign-workspace--combat \.workspace-dock--left\s*\{[^}]*width:\s*360px;/s)
  })

  it('keeps session dice purple and controls all right-dock panels from the header', () => {
    expect(dicePanelSource).toContain('color="var(--accent)"')
    expect(styles).toMatch(/\.workspace-dock--right\s*\{[^}]*width:\s*328px;/s)
    expect(source).not.toContain('class="workspace-tool-toggles"')
    expect(source).toContain("const SESSION_TOOL_PANELS_STORAGE_KEY = 'dnd-share:session-tool-panels:v1'")
    expect(source).toContain('localStorage.getItem(SESSION_TOOL_PANELS_STORAGE_KEY)')
    expect(source).toContain('localStorage.setItem(SESSION_TOOL_PANELS_STORAGE_KEY')
    expect(source).toContain('@toggle-dice="diceOpen = !diceOpen"')
    expect(source).toContain('@toggle-music="musicOpen = !musicOpen"')
    expect(source).toContain('@toggle-events="eventsOpen = !eventsOpen"')
    expect(source).toContain('<BaseTile v-show="diceOpen"')
    expect(source).toContain('<BaseTile v-show="musicOpen"')
    expect(source).toContain('<BaseTile v-show="eventsOpen"')
    expect(dicePanelSource).not.toContain('dice-panel-collapse')
    expect(musicPanelSource).not.toContain('music-panel-collapse')
    expect(musicPanelSource).not.toContain('music-panel-album')
    expect(musicPanelSource).not.toContain('open-library')
    expect(source).toContain('<SessionMusicWorkspace v-if="primaryView === \'music\'"')
    expect(source).not.toContain('MusicLibraryModal')
    expect(source).not.toContain('musicLibraryOpen')
    expect(musicWorkspaceSource).toContain('musicStore.ensureLibrary()')
  })

  it('moves hotkey help out of settings and keeps handbook HP rolling as the local preference', () => {
    expect(source).toContain('useSessionSettings({ sessionUuid })')
    expect(source).toContain('autoRollNpcHp: computed(() => sessionSettings.autoRollNpcHp)')
    expect(sessionSettingsSource).toContain('dnd-share:session-settings:v1:')
    expect(sessionSettingsControlSource).not.toContain('Спрятать легенду на холсте')
    expect(sessionSettingsControlSource).toContain('Автоматически бросать HP существ')
    expect(source).toContain('<SessionShortcutHelp :active="showShortcutHints"')
    expect(shortcutHelpSource).toContain('<kbd>?</kbd>')
    expect(sessionGraphSource).toContain("workspaceMode !== 'combat' && showHotkeyLegend")
    expect(encounterNpcsSource).toContain('resolveStartHp(item, unref(autoRollHp) === true)')
    expect(encounterNpcsSource).toContain('rollDiceExpression')
  })

  it('switches session sections and tool panels and rolls dice while their panel is closed', () => {
    expect(source).toContain('useSessionHotkeys({')
    expect(source).toContain('rollDie: sides => dicePanel.value?.rollDie(sides)')
    expect(source).toContain('<DicePanel ref="dicePanel"')
    expect(dicePanelSource).toContain('defineExpose({ rollDie })')
    expect(dicePanelSource).toContain('class="dice-panel-shortcut"')
    expect(sessionHotkeysSource).toContain("command.type === 'select-view'")
    expect(sessionHotkeysSource).toContain("command.type === 'toggle-panel'")
    expect(sessionHotkeysSource).toContain("command.type === 'roll-die'")
    expect(sessionHotkeysSource).toContain('event.target?.closest?.(EDITABLE_TARGET)')
    expect(sessionHotkeysSource).toContain('document.querySelector(FLOATING_UI)')
  })

  it('provides contextual combat hotkeys without bypassing combat transitions', () => {
    expect(source).toContain('ref="chapterGraphTab"')
    expect(source).toContain('ref="combatWorkspace"')
    expect(source).toContain(':encounter-active="encounter.encounter.active"')
    expect(source).toContain('toggleCombatWorkspace: toggleCombatWorkspaceFromHotkey')
    expect(source).toContain('@open-combat="openCombatTab"')
    expect(source).toContain('@select-view="selectSessionView"')
    expect(source).toContain("if (workspaceMode.value === 'combat' && !workspaceClosing.value) {")
    expect(source).toContain('selectView: selectSessionView')
    expect(source).toContain("combatMode: computed(() => workspaceMode.value === 'combat')")
    expect(source).toContain('canControlCombat: isDm')
    expect(source).toContain('combatWorkspace.value?.toggleCombat()')
    expect(centerWorkspaceSource).toContain('defineExpose({ toggleCombat: () => encounterTab.value?.toggleCombat() })')
    expect(encounterSource).toContain('defineExpose({ toggleCombat })')
    expect(encounterSource).toContain('aria-keyshortcuts="Shift+Enter"')
    expect(encounterSource).toContain('aria-keyshortcuts="ArrowLeft"')
    expect(encounterSource).toContain('aria-keyshortcuts="ArrowRight"')
    expect(encounterSource).toContain('aria-keyshortcuts="Backspace"')
    expect(encounterSource).toContain('aria-keyshortcuts="Shift+A"')
    expect(encounterSource).toContain('aria-keyshortcuts="Shift+N"')
    expect(source).toContain('aria-keyshortcuts="Shift+P"')
    expect(source).toContain('removeSelectedNpcs: () => encounter.removeSelectedNpcs()')
    expect(sessionHotkeysSource).toContain("command.type === 'toggle-encounter' && event.target?.closest?.(NATIVE_ACTIVATION_TARGET)")
  })

  it('lets the canvas use the empty part of the right rail and moves actions right when every panel is closed', () => {
    expect(source).toContain("'campaign-workspace--right-dock': rightDockOpen")
    expect(source).toContain('<aside class="workspace-dock workspace-dock--right">')
    expect(source).toContain('const rightDockOpen = computed(() => diceOpen.value || musicOpen.value || eventsOpen.value)')
    expect(styles).toMatch(/\.workspace-dock--right\s*\{[^}]*pointer-events:\s*none;/s)
    expect(styles).toMatch(/\.workspace-dock--right > \.workspace-tool-tile\s*\{[^}]*pointer-events:\s*auto;/s)
    expect(styles).toMatch(/\.campaign-graph\s*\{[^}]*--chapter-safe-right:\s*0px;/s)
    expect(styles).toMatch(/\.campaign-workspace--combat \.campaign-graph\s*\{[^}]*--chapter-safe-right:\s*350px;/s)
  })

  it('places the event log below the music panel', () => {
    expect(source.indexOf('<MusicPanel'))
      .toBeLessThan(source.indexOf('<SessionEventsPanel'))
  })

  it('uses the opened character sheet as the actor for session dice rolls', () => {
    expect(source).toContain('watch(sheetUuid, actorUuid => {')
    expect(source).toContain('sessionEventsStore.setActor(actorUuid, sessionUuid)')
  })

  it('shows critical success and failure visuals for master d20 rolls', () => {
    expect(dicePanelSource).toContain("{ crit_mode: sides === 20 }")
    expect(dicePanelSource).toContain('outcome: d20Outcome(sides, winner)')
    expect(dicePanelSource).toContain("if (value === 20) return { kind: 'crit', sides, value }")
    expect(dicePanelSource).toContain("if (value === 1) return { kind: 'fumble', sides, value }")
  })

  it('asks for HP before reviving players and NPCs', () => {
    expect(source).toContain('<EncounterReviveModal')
    expect(source).toContain('@revive="encounter.requestRevive(encounterPlayer(p.charId))"')
    expect(reviveModalSource).toContain('Укажите количество HP после воскрешения')
    expect(reviveModalSource).toContain('submit-text="Воскресить"')
    expect(encounterComposableSource).toContain('async function confirmRevive(hpAmount)')
    expect(encounterComposableSource).toContain("if (target.type === 'player') await hp.revivePlayer(target, hpAmount)")
    expect(encounterFlowSource).toContain('function reviveCombatant(c, hpAmount)')
    expect(encounterHpSource).toContain('async function revivePlayer(c, hpAmount)')
    expect(graveyardSource).toContain('enc.requestRevive(combatant)')
    expect(encounterMenuSource).toContain('enc.requestRevive(combatant); close()')
  })

  it('animates displayed rolls on every viewport and cleans up popup timers', () => {
    expect(DiceRollPopup).toBeTruthy()
    expect(dicePopupSource).not.toContain("'(max-width: 640px)'")
    expect(dicePopupSource).toContain("'(prefers-reduced-motion: reduce)'")
    expect(dicePopupSource).toContain('displayedRoll(entry, i, ri, r)')
    expect(dicePopupSource).toContain('displayedTotal(entry)')
    expect(dicePopupSource).toContain("p.color || entry.color || 'var(--accent)'")
    expect(dicePopupSource).toContain('isTotalRolling(entry.id)')
    expect(dicePopupSource).toContain("entry.outcome && !isRolling(entry.id)")
    expect(dicePopupSource).toContain('p.dropped && p.dropped.includes(ri) && !isRolling(entry.id)')
    expect(dicePopupSource).toContain('dice-pop-crit-settle')
    expect(dicePopupSource).toContain('clearEntryAnimation')
    expect(dicePopupSource).not.toContain('part.rolls[rollIndex] =')
  })

  it('centers wrapped dice operators against the 38px dice', () => {
    expect(dicePopupSource).toMatch(/\.dice-pop-rolls-plus\s*\{[^}]*display:\s*inline-flex;[^}]*align-items:\s*center;[^}]*height:\s*38px;/s)
    expect(dicePopupSource).toMatch(/\.dice-pop-roll-wrap\s*\{[^}]*vertical-align:\s*middle;/s)
  })

  it('keeps combat in the overlay and scenario levels inside one persistent canvas', () => {
    expect(source).toContain('<SessionCenterWorkspace')
    expect(source).toContain('v-if="workspaceMode === \'combat\' && (workspaceRevealed || workspaceClosing)"')
    expect(source).toContain(':locked="!!workspaceMode"')
    expect(source).toContain(':workspace-chapter-id="workspaceChapter?.id ?? null"')
    expect(source).toContain(':workspace-scene="workspaceScene"')
    expect(source).toContain(':workspace-mode="workspaceMode"')
    expect(source).toContain(':workspace-layout-mode="workspaceMotionMode"')
    expect(source).toContain(':scene="workspaceScene"')
    expect(source).not.toContain('v-if="combatOpen"')
    expect(source).not.toContain('v-if="sceneWorkspaceChapter"')
    expect(centerWorkspaceSource).not.toContain('<SceneGraphWorkspace')
    expect(sessionGraphSource.match(/<NestedGraphCanvas/g)).toHaveLength(1)
    expect(sessionGraphSource).toContain(':spotlight-node-id="activeSpotlightId"')
    expect(nestedGraphSource).toContain("emit('node-double-click', active.node)")
    expect(centerWorkspaceSource).toContain('bottom: 0;')
    expect(centerWorkspaceSource).not.toContain('.session-center-workspace::after')
    expect(centerWorkspaceSource).not.toContain('backdrop-filter: blur(6px)')
    expect(encounterStylesSource).not.toContain('mask-image:')
    expect(centerWorkspaceSource).not.toContain('<BaseTile')
    expect(encounterSource).toContain("'enc-wrap--workspace': workspace")
    expect(centerWorkspaceSource).not.toContain('<SceneTab')
    expect(sessionGraphSource).toContain("emit('scene-count', activeChapterId.value, sceneGraph.scenes.value.length)")
    expect(sessionGraphSource).toContain("scene: displayLevel.value === 'blocks' ? combatSceneContext() : null")
    expect(sessionGraphSource).toContain("workspaceMode === 'combat') && selectedScene")
    expect(centerWorkspaceSource).toContain("scene ? '504px' : chapter ? '252px' : '0px'")
  })

  it('restores the open combat or chapter scenes workspace after a page reload', () => {
    expect(source).toContain('useSessionWorkspace({ sessionUuid, chapterGraph })')
    expect(source).toContain('const restoredWorkspace = await restoreWorkspace()')
    expect(workspaceSource).toContain("const WORKSPACE_MODES = new Set(['combat', 'scenes'])")
    expect(workspaceSource).toContain('localStorage.setItem(sessionWorkspaceKey(sessionUuid)')
    expect(workspaceSource).toContain('async function restoreWorkspace()')
    expect(workspaceSource).toContain('sceneId: sceneId ?? null')
    expect(workspaceSource).toContain('level,')
    expect(workspaceSource).toContain('await getSceneGraph(sessionUuid, chapter.id)')
    expect(workspaceSource).toContain("saved.level === 'blocks' && scene ? 'blocks' : 'scenes'")
    expect(workspaceSource).toContain('const returnToNested = !forceChapters')
    expect(workspaceSource).toContain('openChapters,')
    expect(source).toContain('@open-chapters="openChapters"')
    expect(source).toContain('@workspace-context-change="updateWorkspaceContext"')
    expect(workspaceSource).toContain('clearSavedWorkspace()')
    expect(source).toContain("restoredWorkspace && workspaceMode.value === 'combat'")
  })

  it('overlaps chapter movement with center content in its second half', () => {
    expect(workspaceSource).toContain('const CONTENT_REVEAL_DELAY_MS = 210')
    expect(workspaceSource).toContain("const workspaceRevealed = computed(() => state.phase === 'open')")
    expect(workspaceSource).toContain('const workspaceMotionMode = computed(() =>')
    expect(workspaceSource).toContain("if (state.phase === 'opening') state.phase = 'open'")
    expect(workspaceSource).toContain("state.phase = 'closing'")
    expect(workspaceSource).toContain('const delay = wasRevealed ? CLOSE_ANIMATION_MS : 0')
    expect(styles).toContain('transition: width 0.42s cubic-bezier(0.22, 1, 0.36, 1);')
    expect(centerWorkspaceSource).toContain('animation: session-workspace-in 0.21s cubic-bezier(0.22, 1, 0.36, 1) both;')
    expect(centerWorkspaceSource).toContain('left 0.42s cubic-bezier(0.22, 1, 0.36, 1);')
  })

  it('reuses one encounter in the combat workspace and the expanding player rail', () => {
    expect(source).toContain('const encounter = reactive(useEncounter({')
    expect(source).toContain('participants.value = res?.participants ?? []\n    syncVersions()\n    await encounter.load()')
    expect(encounterComposableSource).not.toContain('onMounted(() => {\n    load()')
    expect(encounterComposableSource).toContain('encounter,\n    load,')
    expect(source).toContain(':encounter="encounter"')
    expect(source).toContain(':combat-mode="playersRailMode === \'combat\'"')
    expect(styles).toContain('.campaign-workspace--combat .workspace-dock--left')
    expect(styles).toContain('width: 360px;')
    expect(styles).toContain('--chapter-safe-left: 402px;')
    expect(encounterSource).not.toContain('ЗАПАС ИГРОКОВ')
    expect(encounterSource).not.toContain('КЛАДБИЩЕ')
    expect(encounterSource).toContain('<EncounterGraveyardMenu')
    expect(encounterSource).toContain('class="enc-icon-btn enc-icon-btn--danger"')
    expect(encounterSource).not.toContain('>Убить</span>')
    expect(encounterSource).toContain("@click=\"enc.sendSelectedTo('dead')\"")
    expect(encounterSource).toContain('const deadMoveCount = computed(() => enc.selectedToMoveTo(\'dead\'))')
    expect(graveyardSource).toContain('aria-label="Кладбище погибших существ"')
    expect(graveyardSource).toContain('class="enc-icon-btn enc-icon-btn--danger enc-graveyard-trigger"')
    expect(graveyardSource).not.toContain('enc-graveyard-trigger-label')
    expect(graveyardSource).not.toContain('Переместить выбранных')
    expect(graveyardSource).toContain('Удалить всех')
  })

  it('selects or clears every player from the combat rail heading', () => {
    expect(source).toContain("v-if=\"playersRailMode === 'combat'\"")
    expect(source).toContain('<ListChecks :size="17" />')
    expect(source).not.toContain("<span>{{ allEncounterPlayersSelected ? 'Снять выбор' : 'Выбрать всех' }}</span>")
    expect(source).toContain('@click="toggleAllEncounterPlayers"')
    expect(source).toContain('const encounterPlayers = computed(() => participants.value')
    expect(source).toContain('encounterPlayers.value.every(combatant => encounter.isSelected(combatant))')
    expect(source).toContain('encounter.toggleSelected(combatant)')
  })

  it('keeps players in the combat scene and numbers every initiative row', () => {
    expect(encounterSource).toContain('<div v-if="enc.encounter.active" class="enc-combat-scene">')
    expect(encounterSource).toContain('<div class="enc-block enc-block--combat">')
    expect(encounterSource).toContain('class="enc-section-title-group"')
    expect(encounterSource).not.toContain('БОЙ ИДЁТ')
    expect(encounterSource).toContain("const combatItems = computed(() => enc.sortable.displayItems('combat'))")
    expect(encounterSource).toContain(':order="idx + 1"')
    expect(encounterRowSource).toContain('<EncounterOrderMarker')
    expect(encounterOrderSource).toContain('class="enc-row-order"')
    expect(encounterOrderSource).toContain("String(props.order).padStart(2, '0')")
    expect(encounterSource.match(/class="enc-section-title-group"/g)).toHaveLength(2)
  })

  it('uses shared combat stats, larger portraits and editable NPC letter markers', () => {
    expect(encounterRowSource).toContain('<EncounterCombatControls')
    expect(encounterRowSource).toContain('<EncounterMarkerMenu v-if="isNpc"')
    expect(encounterRowSource.indexOf('<EncounterMarkerMenu v-if="isNpc"')).toBeLessThan(encounterRowSource.indexOf('class="enc-name"'))
    expect(encounterRowSource).toContain('v-if="isNpc"\n          ref="badgeEl"')
    expect(encounterRowSource).not.toContain('.badge--pc')
    expect(encounterControlsSource).toContain('aria-label="Инициатива"')
    expect(encounterControlsSource).toContain('<Shield')
    expect(encounterAvatarSource).toContain("width: 62px;")
    expect(encounterAvatarSource).toContain("width: 64px;")
    expect(encounterAvatarSource).toContain("height: 64px;")
    expect(encounterAvatarSource).not.toContain('enc-avatar-letter')
    expect(encounterMarkerSource).toContain('v-for="letter in enc.ENCOUNTER_LETTERS"')
    expect(encounterMarkerSource).toContain('<ColorPresetPicker')
  })

  it('rolls a configured challenge for selected combatants in embedded row results', () => {
    expect(encounterSource).toContain('<EncounterChallengeMenu />')
    expect(encounterChallengeMenuSource).toContain('enc.runChallenge({ ...draft })')
    expect(encounterChallengeMenuSource).toContain("'enc-icon-btn--challenge-active': enc.challengeActive")
    expect(encounterChallengeMenuSource).toContain('enc.resetChallenge()')
    expect(encounterChallengeSource).toContain('inCombat.value.filter(combatant => selectedUids.value.has(combatant.uid))')
    expect(encounterChallengeSource).toContain('for (const combatant of combatants)')
    expect(encounterChallengeSource).toContain('crit_mode: true,')
    expect(encounterChallengeSource).toContain('popup: false,')
    expect(encounterChallengeSource).toContain('actor: { name: displayName(combatant)')
    expect(encounterChallengeMenuSource).toContain('enc.selectedChallengeCount')
    expect(encounterChallengeMenuSource).toContain('Испытание выбранным')
    expect(encounterChallengeSource).toContain('npcSavingThrow(combatant, key)')
    expect(encounterRowSource).toContain('</div>\n\n    <EncounterChallengeResult')
    expect(encounterRowSource).toContain('class="enc-row-challenge"')
    expect(encounterRowSource).toContain('@reroll="enc.rerollChallenge(combatant, $event)"')
    expect(encounterRowSource).toContain('height: 92px;')
    expect(encounterRowSource).toContain('.enc-row-shell[data-encounter-section="combat"]')
    expect(encounterRowSource).toContain('max-width: 880px;')
    expect(encounterRowSource).toContain('flex: 0 0 248px;')
    expect(encounterRowSource).toContain('max-width: 300px;')
    expect(encounterChallengeResultSource).toContain('<SystemDie')
    expect(encounterChallengeResultSource).toContain('useDiceRollAnimation')
    expect(encounterChallengeResultSource).toContain('Докинуть с преимуществом')
    expect(encounterChallengeResultSource).toContain('Докинуть с помехой')
    expect(encounterChallengeResultSource).toContain('v-for="(natural, rollIndex) in naturalRolls"')
    expect(encounterChallengeResultSource).toContain("'ecr-die--dropped': isNaturalDropped(rollIndex)")
    expect(encounterChallengeResultSource).toContain('hasExtraRoll.value && rollIndex === 0')
    expect(encounterChallengeResultSource).toContain('white-space: normal;')
    expect(encounterChallengeResultSource).toContain('border-inline: 1px solid')
    expect(encounterChallengeResultSource).toContain('background: none;')
    expect(encounterChallengeResultSource).not.toContain('linear-gradient')
    expect(encounterChallengeResultSource).not.toContain('box-shadow')
    expect(encounterChallengeResultSource).not.toContain('Результат испытания')
    expect(encounterChallengeResultSource).not.toContain('expression')
  })

  it('groups only multi-action combat toolbar categories', () => {
    expect(encounterSource).not.toContain('class="enc-action-group-label">Экран</span>')
    expect(encounterSource).toContain('class="enc-action-group-label">Броски</span>')
    expect(encounterSource).toContain('class="enc-action-group-label">Выбор</span>')
    expect(encounterSource).not.toContain('class="enc-action-group-label">Погибшие</span>')
    expect(encounterSource).toContain('v-if="props.isDm && enc.encounter.active" class="enc-action-group" aria-label="Броски"')
    expect(encounterSource).toContain('v-else-if="props.isDm"')
    expect(encounterStylesSource).toContain('.enc-toolbar :deep(.enc-icon-btn)')
    expect(encounterStylesSource).toContain('.enc-action-group-controls')
  })

  it('compacts the primary action and left-aligns toolbar actions when the combat workspace is narrow', () => {
    expect(encounterSource).toContain("{{ enc.encounter.active ? 'Закончить бой' : 'Начать бой' }}")
    expect(encounterSource).toContain('class="enc-primary-label"')
    expect(encounterStylesSource).toContain('min-width: 144px;')
    expect(encounterStylesSource).toContain('height: 48px;')
    expect(encounterStylesSource).toContain('.enc-primary-label { line-height: 1; }')
    expect(encounterSource).toContain("'enc-wrap--compact-toolbar': compactToolbar")
    expect(encounterSource).toContain('toolbarResizeObserver = new ResizeObserver(entries =>')
    expect(encounterSource).toContain("encounterRoot.value?.querySelector('.enc-toolbar')")
    expect(encounterSource).toContain('toolbarResizeObserver.observe(toolbar)')
    expect(encounterSource).toContain('compactToolbar.value = Number(width) <= 900')
    expect(encounterStylesSource).toContain('.enc-wrap--compact-toolbar .enc-primary-label { display: none; }')
    expect(encounterStylesSource).toContain('.enc-wrap--compact-toolbar .enc-toolbar-actions { justify-content: flex-start; }')
  })

  it('opens row actions from the tile and keeps concrete controls independent', () => {
    expect(encounterRowSource).toContain('@click="onRowClick"')
    expect(encounterRowSource).toContain('ref="rowMenuRef"')
    expect(encounterRowSource).toContain('enc.sortable.shouldSuppressClick()')
    expect(encounterRowSource).toContain('event.target?.closest?.(DRAG_IGNORE)')
    expect(encounterMenuSource).toContain('defineExpose({ toggle })')
    expect(encounterMenuSource).toContain('>Открыть карточку</RowActionItem>')
    expect(encounterMenuSource).toContain('enc.openNpcDetail(combatant); close()')
    expect(encounterSource).toContain(':actor-name="enc.npcActorName(enc.detailNpc)"')
    expect(encounterComposableSource).toContain('npcActorName:           npcData.npcActorName')
    expect(encounterMenuSource).toContain('isNpc.value && props.combatant.itemId != null')
    expect(encounterMenuSource).toContain('>Состояния</RowActionItem>')
    expect(encounterMenuSource).toContain('>В запас</RowActionItem>')
    expect(encounterMenuSource).toContain('>Перебросить HP</RowActionItem>')
    expect(encounterMenuSource).toContain('enc.rollNpcHpFromFormula(combatant)')
    expect(encounterMenuSource).toContain("props.section !== 'combat'")
    expect(encounterRowSource).not.toContain('enc-hp-dice-btn')
    expect(encounterMenuSource).toContain('const canDelete = computed(() => isNpc.value)')
    expect(encounterMenuSource).not.toContain('ColorPresetPicker')
    expect(encounterFlowSource).toContain('function sendToReserve(c)')
    expect(encounterStatesSource).toContain('DND_EFFECT_ITEM_TYPE_ID = 15')
    expect(encounterStatesSource).toContain('content: { item_type_id: DND_EFFECT_ITEM_TYPE_ID')
    expect(encounterRowSource).toContain('title="Состояния"')
    expect(encounterRowSource).toContain(':item-type-ids="[statesBlock.content.item_type_id]"')
    expect(encounterRowSource).not.toContain('SuggestMultiSelect')
  })

  it('fades selected NPCs out before revealing the combat scene', () => {
    expect(encounterSource).toContain('useEncounterCombatTransition(enc, encounterRoot)')
    expect(encounterSource).toContain(':disabled="combatTransitioning ||')
    expect(encounterSource).toContain('<Transition name="enc-combat-scene">')
    expect(encounterRowSource).toContain(':data-encounter-uid="combatant.uid"')
    expect(encounterTransitionSource).toContain("phase.value = starting ? 'starting' : 'ending'")
    expect(encounterTransitionSource).toContain('fadeReserveNpcsOut()')
    expect(encounterTransitionSource).toContain("combatant.type === 'npc'")
    expect(encounterTransitionSource).not.toContain('cloneForFlight')
    expect(encounterTransitionSource).toContain('prefers-reduced-motion: reduce')
    expect(encounterStylesSource).toContain('.enc-combat-scene-enter-from')
  })

  it('keeps per-participant actions alongside the combat-only bulk selection control', () => {
    expect(source).toContain('@view="openParticipant"')
    expect(source).toContain('@color="setParticipantColor"')
    expect(source).toContain('@kick="requestKickParticipant"')
    expect(source).not.toContain('Выбрать игроков для действия')
    expect(source).not.toContain('selectionMode')
  })

  it('reorders participants by drag and persists the complete order', () => {
    expect(source).toContain('data-sortable-container="participants"')
    expect(source).toContain(':data-sortable-key="p.charId"')
    expect(source).toContain(':should-suppress-reorder-click="participantSortable.shouldSuppressClick"')
    expect(source).toContain('const participantSortable = useSortable({')
    expect(source).toContain('const reordered = reorderByDrop(participants.value, fromIndex, toIndex)')
    expect(source).toContain('await reorderParticipants(sessionUuid, reordered.map(participant => participant.charId))')
    expect(source).toContain("participantOrderError.value = 'Не удалось сохранить порядок игроков'")
  })

  it('saves a session-local participant color and marks player tiles in both rails', () => {
    expect(source).toContain('await updateParticipantColor(sessionUuid, charId, color)')
    expect(source).toContain('{ ...participant, color: color || null }')
    expect(encounterRowSource).toContain('<EncounterAvatar :combatant="combatant" />')
    expect(encounterRowSource).toContain('enc.participantColor(props.combatant.charId)')
    expect(encounterRowSource).toContain(':strip="isNpc && !!rowAccentColor"')
    expect(encounterRowSource).toContain("'enc-row--player-colored': isPlayer.value && !!playerColor.value")
    expect(encounterRowSource).toContain('box-shadow: inset 0 0 0 2px var(--enc-player-color);')
    expect(encounterRowSource).toContain(":color=\"rowAccentColor || 'var(--section-color)'\"")
    expect(encounterComposableSource).toContain("if (c.type === 'player') return participantColor(c.charId) || null")
    expect(encounterComposableSource).toContain('return c.iconColor || null')
    expect(encounterAvatarSource).not.toContain('--enc-player-frame-color')
    expect(encounterAvatarSource).not.toContain('playerColor: { type: String')
  })

  it('asks for confirmation before kicking a participant', () => {
    expect(source).toContain('title="Выгнать игрока?"')
    expect(source).toContain('@kick="requestKickParticipant"')
    expect(source).toContain('@confirm="confirmKickParticipant"')
    expect(source).toContain('if (await kickParticipant(charId)) pendingKick.value = null')
    expect(selectionSource).toContain('return true')
    expect(selectionSource).toContain('return false')
  })

  it('keeps a failed kick visible and only removes a participant after success', () => {
    expect(source).toContain('role="alert"')
    expect(selectionSource.indexOf('await apiKick(sessionUuid, charId)'))
      .toBeLessThan(selectionSource.indexOf('participants.value = participants.value.filter'))
    expect(selectionSource).toContain("kickError.value = 'Не удалось выгнать участника'")
    expect(selectionSource).not.toContain('.catch(() => {})')
  })
})
