import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const read = name => readFileSync(fileURLToPath(new URL(`./${name}`, import.meta.url)), 'utf8')
const headerSource = read('ItemDetailHeader.vue')
const detailSource = read('HandbookItemDetail.vue')
const enemySummarySource = read('../../items/detail-components/EnemyDetailSummary.vue')
const enemySummaryStyles = read('../../items/detail-components/styles/EnemyDetailSummary.css')
const enemyContentSource = read('../../items/detail-components/EnemyDetailContent.vue')
const armorSummarySource = read('../../items/detail-components/ArmorDetailSummary.vue')
const armorSummaryStyles = read('../../items/detail-components/styles/ArmorDetailSummary.css')
const armorContentSource = read('../../items/detail-components/ArmorDetailContent.vue')
const weaponSummarySource = read('../../items/detail-components/WeaponDetailSummary.vue')
const weaponSummaryStyles = read('../../items/detail-components/styles/WeaponDetailSummary.css')
const weaponContentSource = read('../../items/detail-components/WeaponDetailContent.vue')
const transportSummarySource = read('../../items/detail-components/TransportDetailSummary.vue')
const transportSummaryStyles = read('../../items/detail-components/styles/TransportDetailSummary.css')
const transportContentSource = read('../../items/detail-components/TransportDetailContent.vue')
const gearSummarySource = read('../../items/detail-components/GearDetailSummary.vue')
const gearContentSource = read('../../items/detail-components/ItemDetailContent.vue')
const spellSummarySource = read('../../items/detail-components/SpellDetailSummary.vue')
const spellContentSource = read('../../items/detail-components/SpellDetailContent.vue')

describe('handbook item detail cover', () => {
  it('uses the intrinsic cover ratio without a shared maximum height', () => {
    expect(headerSource).toContain('aspect-ratio: var(--cover-aspect-ratio, auto);')
    expect(headerSource).not.toContain('max-height: min(320px, 42dvh);')
    expect(headerSource).not.toContain("'--cover-max-height'")
    expect(headerSource).toContain('flex: 0 0 auto;')
  })

  it('keeps cover art centered without height-limit layout tracking', () => {
    expect(headerSource).toContain('object-position: center;')
    expect(headerSource).not.toContain('coverHeightLimited')
    expect(headerSource).not.toContain('ResizeObserver')
    expect(headerSource).not.toContain('object-position: center top;')
  })

  it('preloads and quickly crossfades covers without resetting bestiary geometry', () => {
    expect(headerSource).toContain("if (typeId === 5) return '5 / 2'")
    expect(headerSource).toContain("if (typeId === 1 || typeId === 6 || typeId === 12) return '4 / 3'")
    expect(headerSource).toContain("return ''")
    expect(headerSource).toContain('const image = new Image()')
    expect(headerSource).toContain('await image.decode()')
    expect(headerSource).toContain(':key="displayedCoverUrl"')
    expect(headerSource).toContain('class="item-detail-cover item-detail-cover-previous"')
    expect(headerSource).toContain('animation: item-detail-cover-enter 160ms')
    expect(headerSource).toContain('@media (prefers-reduced-motion: reduce)')
    expect(headerSource).not.toContain("coverAspectRatio.value = '4 / 1'")
  })

  it('gives covered spells a 5:2 casting dashboard without duplicating its summary below', () => {
    expect(headerSource).toContain("5: {\n    '--cover-min-height': '300px'")
    expect(headerSource).toContain("if (typeId === 5) return '5 / 2'")
    expect(detailSource).toContain('<SpellDetailSummary :item="item" :type="type" />')
    expect(detailSource).toContain('summaryInHeader: isSpellCovered.value')
    expect(detailSource).toContain("props.item?.coverImageUrl || props.type?.coverImageUrl || ''")
    expect(headerSource).toContain("props.item.coverImageUrl || props.type?.coverImageUrl || ''")
    expect(spellSummarySource).toContain('grid-template-columns: repeat(3, minmax(0, 1fr));')
    expect(spellSummarySource).toContain('class="spell-summary-kind"')
    expect(spellSummarySource).toContain('class="spell-summary-casting"')
    expect(spellSummarySource).toContain('class="spell-summary-card spell-summary-components-card"')
    expect(spellSummarySource).toContain('justify-content: space-between;')
    expect(spellSummarySource).toContain('Компоненты')
    expect(spellSummarySource).toContain('Время')
    expect(spellSummarySource).toContain('Дистанция')
    expect(spellSummarySource).toContain('Длительность')
    expect(spellContentSource).toContain('!summaryInHeader && (data.time || data.range || data.duration)')
    expect(spellContentSource).toContain("summaryInHeader ? 'Материальный компонент:' : 'Компоненты:'")
  })

  it('gives armor a 4:3 object showcase with side stats and a bottom requirement rail', () => {
    expect(headerSource).toContain("if (typeId === 1 || typeId === 6 || typeId === 12) return '4 / 3'")
    expect(headerSource).toContain("'--cover-min-height': '420px'")
    expect(detailSource).toContain('<ArmorDetailSummary :item="item" />')
    expect(detailSource).toContain('12: ArmorDetailContent')
    expect(armorSummarySource).toContain('class="armor-summary-side armor-summary-left"')
    expect(armorSummarySource).toContain('class="armor-cover-safe-zone"')
    expect(armorSummarySource).toContain('class="armor-summary-side armor-summary-right"')
    expect(armorSummarySource).toContain('class="armor-requirements"')
    expect(armorSummaryStyles).toContain('"left center right"')
    expect(armorSummaryStyles).toContain('"requirements requirements requirements"')
    expect(armorContentSource).toContain('label="Описание"')
    expect(armorContentSource).toContain('label="Правила ношения"')
  })

  it('gives transport a 3:2 showcase with operational data around a safe center', () => {
    expect(headerSource).toContain("if (typeId === 13) return '3 / 2'")
    expect(headerSource).toContain("13: {\n    '--cover-min-height': '400px'")
    expect(detailSource).toContain('<TransportDetailSummary :item="item" />')
    expect(detailSource).toContain('13: TransportDetailContent')
    expect(transportSummarySource).toContain('class="transport-summary-side transport-summary-left"')
    expect(transportSummarySource).toContain('class="transport-cover-safe-zone"')
    expect(transportSummarySource).toContain('class="transport-summary-side transport-summary-right"')
    expect(transportSummarySource).toContain('class="transport-operations"')
    expect(transportSummaryStyles).toContain('"left center right"')
    expect(transportContentSource).toContain('label="Эксплуатация"')
    expect(transportContentSource).toContain('label="Характеристики объекта"')
  })

  it('shows purchasable gear as a 3:2 cover with price and weight around a safe center', () => {
    expect(headerSource).toContain("if (typeId === 2) return '3 / 2'")
    expect(headerSource).toContain("2: {\n    '--cover-min-height': '400px'")
    expect(detailSource).toContain('<GearDetailSummary :item="item" />')
    expect(detailSource).toContain('available_in_starting_shop === true')
    expect(detailSource).toContain('economyInHeader: isShopGearCovered.value')
    expect(gearSummarySource).toContain('class="gear-economy-card gear-economy-cost"')
    expect(gearSummarySource).toContain('class="gear-economy-card gear-economy-weight"')
    expect(gearSummarySource).toContain('grid-template-columns: minmax(140px, 180px) minmax(180px, 1fr) minmax(140px, 180px);')
    expect(gearContentSource).toContain('!economyInHeader && data.weight != null')
  })

  it('uses the shared 4:3 object showcase for weapon damage, economy and OR proficiencies', () => {
    expect(detailSource).toContain('<WeaponDetailSummary :item="item" />')
    expect(headerSource).toContain("1: {\n    '--cover-min-height': '420px'")
    expect(weaponSummarySource).toContain('class="weapon-summary-side weapon-summary-left"')
    expect(weaponSummarySource).toContain('class="weapon-cover-safe-zone"')
    expect(weaponSummarySource).toContain('class="weapon-summary-side weapon-summary-right"')
    expect(weaponSummarySource).toContain('class="weapon-rules"')
    expect(weaponSummarySource).toContain("labels.join(' или ')")
    expect(weaponSummarySource).toContain("'Владеют все'")
    expect(weaponSummaryStyles).toContain('"left center right"')
    expect(weaponSummaryStyles).toContain('"rules rules rules"')
    expect(weaponContentSource).toContain('v-if="showTitle && hasDamageInfo"')
    expect(weaponContentSource).toContain('v-if="showTitle && tagItems.length"')
  })

  it('caps portrait bestiary artwork at a square image-driven geometry', () => {
    expect(headerSource).toContain('function coverAspectRatioForDimensions(width, height, typeId)')
    expect(headerSource).toContain("if ((typeId === 1 || typeId === 6 || typeId === 12) && height > width) return '1 / 1'")
    expect(headerSource).toContain('coverAspectRatioForDimensions(\n        image.naturalWidth,')
    expect(headerSource).toContain('coverAspectRatioForDimensions(width, height, props.type?.id)')
  })

  it('supports a separate cover height profile for each handbook type', () => {
    expect(headerSource).toContain('const TYPE_COVER_STYLES = {')
    expect(headerSource).toContain("'--cover-min-height': '440px'")
    expect(headerSource).toContain('TYPE_COVER_STYLES[props.type?.id]')
    expect(headerSource).toContain('.item-detail-header-covered.item-detail-header-summary::before {')
    expect(headerSource).toContain('aspect-ratio: var(--cover-aspect-ratio, auto);')
  })

  it('lets a bestiary summary grow beyond the image-driven cover height', () => {
    expect(headerSource).toContain('.item-detail-header-covered.item-detail-header-summary {\n  aspect-ratio: auto;\n  display: grid;\n  grid-template-columns: minmax(0, 1fr);')
    expect(headerSource).toContain("content: '';\n  grid-area: 1 / 1;")
    expect(headerSource).toContain('min-height: var(--cover-min-height, 440px);')
    expect(headerSource).toContain('.item-detail-header-summary .item-detail-overlay {\n  min-height: var(--cover-min-height, 0);')
    expect(headerSource).toContain('.item-detail-header-covered.item-detail-header-summary .item-detail-overlay {\n  grid-area: 1 / 1;')
    expect(headerSource).toContain('.item-detail-header-summary .item-detail-summary {\n  flex: 1;\n  min-height: min-content;')
    expect(enemySummaryStyles).toContain('.enemy-summary {\n  flex: 1;\n  min-height: min-content;')
  })

  it('keeps bestiary data in local translucent blocks without shading the whole cover', () => {
    expect(detailSource).toContain('<EnemyDetailSummary :item="item" :type="type" />')
    expect(detailSource).toContain('<template v-if="isEnemy" #summary>')
    expect(headerSource).toContain('<slot name="summary" />')
    expect(headerSource).toContain('<slot name="corner" />')
    expect(detailSource).toContain(':title="itemSourceTitle"')
    expect(detailSource).toContain('source.name || source.code')
    expect(headerSource).toContain('.item-detail-header-covered.item-detail-header-summary .item-detail-shade')
    expect(headerSource).toContain('display: none;')
    expect(headerSource).toContain('.item-detail-header-covered.item-detail-header-summary .item-detail-title')
    expect(headerSource).toContain('width: fit-content;')
    expect(headerSource).not.toContain('.item-detail-header-covered.item-detail-header-summary .item-detail-overlay {\n  background:')
    expect(enemySummarySource).toContain('class="enemy-abilities"')
    expect(enemyContentSource).not.toContain('class="enemy-abilities"')
    expect(enemyContentSource).not.toContain('class="enemy-top"')
  })

  it('keeps edit and source in one shared right-aligned row for every item type', () => {
    expect(headerSource).toContain('class="item-detail-controls"')
    expect(headerSource.indexOf('<slot name="actions" />')).toBeLessThan(headerSource.indexOf('<slot name="corner" />'))
    expect(detailSource).toContain('<template v-if="itemSourceLabel" #corner>')
    expect(detailSource).toContain('<Pencil :size="14" aria-hidden="true" />')
    expect(detailSource).not.toContain('class="detail-sources"')
  })

  it('frames a centered creature with side stats and bottom abilities', () => {
    expect(enemySummarySource).toContain('class="enemy-stats-side enemy-stats-left"')
    expect(enemySummarySource).toContain('class="enemy-cover-safe-zone"')
    expect(enemySummarySource).toContain('class="enemy-stats-side enemy-stats-right"')
    expect(enemySummarySource).toContain('class="enemy-tags enemy-tags-left"')
    expect(enemySummarySource).toContain('tag.key === \'alignment\'')
    expect(enemySummaryStyles).toContain('"left center right"')
    expect(enemySummaryStyles).toContain('"abilities abilities abilities"')
    expect(enemySummaryStyles).toContain('grid-template-rows: minmax(min-content, 1fr) auto;')
    expect(enemySummaryStyles).toContain('grid-template-columns: minmax(132px, 190px) minmax(220px, 1fr) minmax(132px, 190px);')
    expect(headerSource).toContain('.item-detail-header-summary .item-detail-summary {\n  flex: 1;')
    expect(enemySummaryStyles).toContain('min-height: 190px;')
    expect(enemySummaryStyles).toContain('"left right"')
    expect(enemySummaryStyles).toContain('"abilities abilities"')
  })

  it('uses the icon only as a missing-cover fallback and moves the id below the content', () => {
    expect(headerSource).toContain('v-if="!hasCover && (item.iconImageUrl || item.svg || type?.iconImageUrl)"')
    expect(headerSource).toContain(':type="type"')
    expect(headerSource).not.toContain('class="item-detail-id"')
    expect(detailSource).toContain('v-if="showTitle" class="detail-technical-meta"')
    expect(detailSource).toContain('<span>ID {{ item.id }}</span>')
    expect(detailSource).toContain('margin-top: auto;')
  })

  it('keeps overflowing detail content scrollable on every viewport', () => {
    expect(detailSource).toContain('min-height: 0;')
    expect(detailSource).toContain('overflow-y: auto;')
    expect(detailSource).toContain('overscroll-behavior-y: contain;')
    expect(detailSource).not.toContain('overflow: visible;')
  })
})
