import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const read = name => readFileSync(fileURLToPath(new URL(`./${name}`, import.meta.url)), 'utf8')
const headerSource = read('ItemDetailHeader.vue')
const detailSource = read('HandbookItemDetail.vue')
const coverStatCardSource = read('../../items/components/cover/CoverStatCard.vue')
const coverSummaryLayoutSource = read('../../items/components/cover/CoverSummaryLayout.vue')
const coverSummaryRailSource = read('../../items/components/cover/CoverSummaryRail.vue')
const coverSummaryRailItemSource = read('../../items/components/cover/CoverSummaryRailItem.vue')
const enemySummarySource = read('../../items/detail-components/EnemyDetailSummary.vue')
const enemySummaryStyles = read('../../items/detail-components/styles/EnemyDetailSummary.css')
const enemyContentSource = read('../../items/detail-components/EnemyDetailContent.vue')
const armorSummarySource = read('../../items/detail-components/ArmorDetailSummary.vue')
const armorContentSource = read('../../items/detail-components/ArmorDetailContent.vue')
const weaponSummarySource = read('../../items/detail-components/WeaponDetailSummary.vue')
const weaponContentSource = read('../../items/detail-components/WeaponDetailContent.vue')
const transportSummarySource = read('../../items/detail-components/TransportDetailSummary.vue')
const transportContentSource = read('../../items/detail-components/TransportDetailContent.vue')
const gearSummarySource = read('../../items/detail-components/GearDetailSummary.vue')
const gearContentSource = read('../../items/detail-components/ItemDetailContent.vue')
const toolSummarySource = read('../../items/detail-components/ToolDetailSummary.vue')
const spellSummarySource = read('../../items/detail-components/SpellDetailSummary.vue')
const spellContentSource = read('../../items/detail-components/SpellDetailContent.vue')

describe('handbook item detail cover', () => {
  it('uses the intrinsic cover ratio without a shared maximum height', () => {
    expect(headerSource).toContain('aspect-ratio: var(--cover-aspect-ratio, auto);')
    expect(headerSource).not.toContain('max-height: min(320px, 42dvh);')
    expect(headerSource).not.toContain("'--cover-max-height'")
    expect(headerSource).toContain('flex: 0 0 auto;')
  })

  it('keeps cover art centered without height-limit layout tracking', () => {
    expect(headerSource).toContain('object-position: center;')
    expect(headerSource).not.toContain('coverHeightLimited')
    expect(headerSource).not.toContain('ResizeObserver')
    expect(headerSource).not.toContain('object-position: center top;')
  })

  it('preloads and quickly crossfades covers without resetting bestiary geometry', () => {
    expect(headerSource).toContain("if ([3, 4, 5, 7, 10].includes(typeId)) return '5 / 2'")
    expect(headerSource).toContain("if ([2, 8, 9, 11, 13, 14].includes(typeId)) return '3 / 2'")
    expect(headerSource).toContain("if (typeId === 1 || typeId === 6 || typeId === 12) return '4 / 3'")
    expect(headerSource).toContain("return ''")
    expect(headerSource).toContain('const image = new Image()')
    expect(headerSource).toContain('await image.decode()')
    expect(headerSource).toContain(':key="displayedCoverUrl"')
    expect(headerSource).toContain('class="item-detail-cover item-detail-cover-previous"')
    expect(headerSource).toContain('animation: item-detail-cover-enter 160ms')
    expect(headerSource).toContain('@media (prefers-reduced-motion: reduce)')
    expect(headerSource).not.toContain("coverAspectRatio.value = '4 / 1'")
  })

  it('gives covered spells a 5:2 casting dashboard without duplicating its summary below', () => {
    expect(headerSource).toContain("5: {\n    '--cover-min-height': '300px'")
    expect(headerSource).toContain("if ([3, 4, 5, 7, 10].includes(typeId)) return '5 / 2'")
    expect(detailSource).toContain('<SpellDetailSummary :item="item" :type="type" />')
    expect(detailSource).toContain('if (props.type?.id === 5) return { summaryInHeader: true }')
    expect(headerSource).toContain("props.item.coverImageUrl || props.type?.coverImageUrl || ''")
    expect(spellSummarySource).toContain('grid-template-columns: repeat(3, minmax(0, 1fr));')
    expect(spellSummarySource).toContain('class="spell-summary-kind"')
    expect(spellSummarySource).toContain('class="spell-summary-casting"')
    expect(spellSummarySource).toContain('<CoverStatCard')
    expect(spellSummarySource).toContain('class="spell-summary-components-card"')
    expect(spellSummarySource).toContain('align-self: flex-end;')
    expect(spellSummarySource).toContain('width: min(180px, 100%);')
    expect(spellSummarySource).toContain('Компоненты')
    expect(spellSummarySource).toContain('Время')
    expect(spellSummarySource).toContain('Дистанция')
    expect(spellSummarySource).toContain('Длительность')
    expect(spellContentSource).toContain('!summaryInHeader && (data.time || data.range || data.duration)')
    expect(spellContentSource).toContain("summaryInHeader ? 'Материальный компонент:' : 'Компоненты:'")
  })

  it('gives armor a 4:3 object showcase with side stats and a bottom requirement rail', () => {
    expect(headerSource).toContain("if (typeId === 1 || typeId === 6 || typeId === 12) return '4 / 3'")
    expect(headerSource).toContain("'--cover-min-height': '420px'")
    expect(detailSource).toContain('<ArmorDetailSummary :item="item" />')
    expect(detailSource).toContain('12: ArmorDetailContent')
    expect(armorSummarySource).toContain('<CoverSummaryLayout :safe-min-height="210">')
    expect(armorSummarySource).toContain('<template #left>')
    expect(armorSummarySource).toContain('<template #right>')
    expect(armorSummarySource).toContain('<CoverSummaryRail :columns="3">')
    expect(armorContentSource).toContain('label="Описание"')
    expect(armorContentSource).toContain('label="Правила ношения"')
  })

  it('gives transport a 3:2 showcase with operational data around a safe center', () => {
    expect(headerSource).toContain("if ([2, 8, 9, 11, 13, 14].includes(typeId)) return '3 / 2'")
    expect(headerSource).toContain("13: {\n    '--cover-min-height': '400px'")
    expect(detailSource).toContain('<TransportDetailSummary :item="item" />')
    expect(detailSource).toContain('13: TransportDetailContent')
    expect(transportSummarySource).toContain('<CoverSummaryLayout')
    expect(transportSummarySource).toContain(':center-min="220"')
    expect(transportSummarySource).toContain('<CoverSummaryRail :columns="3">')
    expect(transportContentSource).toContain('label="Эксплуатация"')
    expect(transportContentSource).toContain('label="Характеристики объекта"')
  })

  it('shows gear as a 3:2 cover with price and weight around a safe center', () => {
    expect(headerSource).toContain("if ([2, 8, 9, 11, 13, 14].includes(typeId)) return '3 / 2'")
    expect(headerSource).toContain("2: {\n    '--cover-min-height': '400px'")
    expect(headerSource).toContain("14: {\n    '--cover-min-height': '400px'")
    expect(detailSource).toContain('<GearDetailSummary :item="item" :type="type" />')
    expect(detailSource).toContain('<ToolDetailSummary :item="item" />')
    expect(detailSource).toContain('if (props.type?.id === 2 || props.type?.id === 14) return { economyInHeader: true }')
    expect(gearSummarySource).toContain('class="gear-economy-card gear-economy-cost"')
    expect(gearSummarySource).toContain('tone="warning"')
    expect(gearSummarySource).toContain('class="gear-economy-card gear-economy-weight"')
    expect(gearSummarySource).toContain('measuredItemEconomy(props.type, props.item)')
    expect(gearSummarySource).toContain('`за ${measuredEconomy.value.quantity} ${measuredEconomy.value.unit}`')
    expect(gearSummarySource).toContain('tone="accent"')
    expect(gearSummarySource).toContain('grid-template-columns: minmax(140px, 180px) minmax(180px, 1fr) minmax(140px, 180px);')
    expect(gearContentSource).toContain('!economyInHeader && data.weight != null')
  })

  it('shows tool proficiency requirements below the cover with OR semantics', () => {
    expect(detailSource).toContain('<template v-else-if="isTool" #summary>')
    expect(toolSummarySource).toContain('label="Требуется владение"')
    expect(toolSummarySource).toContain('data.value.required_tool_proficiencies')
    expect(toolSummarySource).toContain('suggestStore.ensure(5)')
    expect(toolSummarySource).toContain("labels.join(' или ')")
    expect(toolSummarySource).toContain("'Не требуется'")
  })

  it('uses the shared 4:3 object showcase for weapon damage, economy and OR proficiencies', () => {
    expect(detailSource).toContain('<WeaponDetailSummary :item="item" />')
    expect(headerSource).toContain("1: {\n    '--cover-min-height': '420px'")
    expect(weaponSummarySource).toContain('<CoverSummaryLayout>')
    expect(weaponSummarySource).toContain('<template #left>')
    expect(weaponSummarySource).toContain('<template #right>')
    expect(weaponSummarySource).toContain('<CoverSummaryRail columns="1.35fr 1fr">')
    expect(weaponSummarySource).toContain("labels.join(' или ')")
    expect(weaponSummarySource).toContain("'Владеют все'")
    expect(weaponContentSource).toContain('v-if="showTitle && hasDamageInfo"')
    expect(weaponContentSource).toContain('v-if="showTitle && tagItems.length"')
  })

  it('caps portrait bestiary artwork at a square image-driven geometry', () => {
    expect(headerSource).toContain('function coverAspectRatioForDimensions(width, height, typeId)')
    expect(headerSource).toContain("if ((typeId === 1 || typeId === 6 || typeId === 12) && height > width) return '1 / 1'")
    expect(headerSource).toContain('coverAspectRatioForDimensions(\n        image.naturalWidth,')
    expect(headerSource).toContain('coverAspectRatioForDimensions(width, height, props.type?.id)')
  })

  it('supports a separate cover height profile for each handbook type', () => {
    expect(headerSource).toContain('const TYPE_COVER_STYLES = {')
    expect(headerSource).toContain("'--cover-min-height': '440px'")
    expect(headerSource).toContain('TYPE_COVER_STYLES[props.type?.id]')
    expect(headerSource).toContain('.item-detail-header-covered.item-detail-header-summary::before {')
    expect(headerSource).toContain('aspect-ratio: var(--cover-aspect-ratio, auto);')
  })

  it('lets a bestiary summary grow beyond the image-driven cover height', () => {
    expect(headerSource).toContain('.item-detail-header-covered.item-detail-header-summary {\n  aspect-ratio: auto;\n  display: grid;\n  grid-template-columns: minmax(0, 1fr);')
    expect(headerSource).toContain("content: '';\n  grid-area: 1 / 1;")
    expect(headerSource).toContain('min-height: var(--cover-min-height, 440px);')
    expect(headerSource).toContain('.item-detail-header-summary .item-detail-overlay {\n  min-height: var(--cover-min-height, 0);')
    expect(headerSource).toContain('.item-detail-header-covered.item-detail-header-summary .item-detail-overlay {\n  grid-area: 1 / 1;')
    expect(headerSource).toContain('.item-detail-header-summary .item-detail-summary {\n  flex: 1;\n  min-height: min-content;')
    expect(enemySummaryStyles).toContain('.enemy-summary {\n  flex: 1;\n  min-height: min-content;')
  })

  it('keeps bestiary data in local translucent blocks without shading the whole cover', () => {
    expect(detailSource).toContain('<EnemyDetailSummary :item="item" :type="type" />')
    expect(detailSource).toContain('<template v-if="isEnemy" #summary>')
    expect(headerSource).toContain('<slot name="summary" />')
    expect(headerSource).toContain('<slot name="corner" />')
    expect(detailSource).toContain(':title="itemSourceTitle"')
    expect(detailSource).toContain('source.name || source.code')
    expect(headerSource).toContain('.item-detail-header-covered.item-detail-header-summary .item-detail-shade')
    expect(headerSource).toContain('display: none;')
    expect(headerSource).toContain('.item-detail-header-covered.item-detail-header-summary .item-detail-title')
    expect(headerSource).toContain('width: fit-content;')
    expect(headerSource).not.toContain('.item-detail-header-covered.item-detail-header-summary .item-detail-overlay {\n  background:')
    expect(enemySummarySource).toContain('class="enemy-abilities"')
    expect(enemyContentSource).not.toContain('class="enemy-abilities"')
    expect(enemyContentSource).not.toContain('class="enemy-top"')
  })

  it('limits cover dimming for abilities and feats to the title panel', () => {
    expect(headerSource).toContain('const titleOnlyShade = computed(() => [3, 4, 7].includes(props.type?.id))')
    expect(headerSource).toContain("'item-detail-header-title-only-shade': titleOnlyShade")
    expect(headerSource).toContain('.item-detail-header-covered.item-detail-header-title-only-shade .item-detail-shade')
    expect(headerSource).toContain('.item-detail-header-covered.item-detail-header-title-only-shade .item-detail-title')
  })

  it('keeps edit and source in one shared right-aligned row for every item type', () => {
    expect(headerSource).toContain('class="item-detail-controls"')
    expect(headerSource.indexOf('<slot name="actions" />')).toBeLessThan(headerSource.indexOf('<slot name="corner" />'))
    expect(detailSource).toContain('<template v-if="itemSourceLabel" #corner>')
    expect(detailSource).toContain('<Pencil :size="14" aria-hidden="true" />')
    expect(detailSource).not.toContain('class="detail-sources"')
  })

  it('frames a centered creature with side stats and bottom abilities', () => {
    expect(enemySummarySource).toContain('<CoverSummaryLayout')
    expect(enemySummarySource).toContain(':side-min="132"')
    expect(enemySummarySource).toContain(':center-min="220"')
    expect(enemySummarySource).toContain(':safe-min-height="190"')
    expect(enemySummarySource).toContain('class="enemy-tags enemy-tags-left"')
    expect(enemySummarySource).toContain('tag.key === \'alignment\'')
    expect(coverSummaryLayoutSource).toContain('"left center right"')
    expect(coverSummaryLayoutSource).toContain('"bottom bottom bottom"')
    expect(coverSummaryLayoutSource).toContain('grid-template-rows: minmax(var(--cover-summary-safe-min-height), 1fr) auto;')
    expect(headerSource).toContain('.item-detail-header-summary .item-detail-summary {\n  flex: 1;')
    expect(coverSummaryLayoutSource).toContain('"left right"')
    expect(coverSummaryLayoutSource).toContain('"bottom bottom"')
  })

  it('standardizes cover tiles and uses larger translucent right-centered icon marks', () => {
    for (const source of [enemySummarySource, armorSummarySource, weaponSummarySource, transportSummarySource, gearSummarySource, spellSummarySource]) {
      expect(source).toContain('CoverStatCard')
    }
    expect(coverStatCardSource).toContain('class="cover-stat-card-mark"')
    expect(coverStatCardSource).toContain('position: absolute;')
    expect(coverStatCardSource).toContain('top: 50%;')
    expect(coverStatCardSource).toContain('right: 12px;')
    expect(coverStatCardSource).toContain('width: 27px;')
    expect(coverStatCardSource).toContain('opacity: .46;')
    expect(coverStatCardSource).toContain('transform: translateY(-50%);')
    expect(coverSummaryRailSource).toContain('var(--cover-summary-rail-columns)')
    expect(coverSummaryRailItemSource).toContain('class="cover-summary-rail-mark"')
    expect(coverSummaryRailItemSource).toContain('opacity: .46;')
  })

  it('always uses cover geometry and moves the id below the content', () => {
    expect(headerSource).toContain('class="item-detail-header item-detail-header-covered"')
    expect(headerSource).not.toContain('<ItemIcon')
    expect(headerSource).not.toContain('item-detail-header:not(.item-detail-header-covered)')
    expect(headerSource).not.toContain('class="item-detail-id"')
    expect(detailSource).toContain('v-if="showTitle" class="detail-technical-meta"')
    expect(detailSource).toContain('<span>ID {{ item.id }}</span>')
    expect(detailSource).toContain('margin-top: auto;')
  })

  it('keeps overflowing detail content scrollable on every viewport', () => {
    expect(detailSource).toContain('min-height: 0;')
    expect(detailSource).toContain('overflow-y: auto;')
    expect(detailSource).toContain('overscroll-behavior-y: contain;')
    expect(detailSource).not.toContain('overflow: visible;')
  })
})
