import { test, expect } from '@playwright/test'
import fixture from './data.json' with { type: 'json' }

test.beforeEach(async ({ page }) => {
  page.on('pageerror', error => { throw error })
  await page.route('**/api/**', route => {
    const url = new URL(route.request().url())
    if (!url.pathname.startsWith('/api/')) return route.continue()
    if (url.pathname === '/api/suggest/batch') return route.fulfill({ json: { items: { 12: fixture.damageTypes } } })
    const ids = new Set((url.searchParams.get('ids') || '').split(',').map(Number))
    return route.fulfill({ json: { items: url.pathname === '/api/items/by-ids' ? fixture.spells.filter(spell => ids.has(spell.id)) : [] } })
  })
})
for (const width of [1280, 390]) {
  test(`tiefling separates heritage and size and opens real spell entries (${width})`, async ({ page }) => {
    await page.setViewportSize({ width, height: 1000 })
    await page.goto('/tests/species/fixture.html?tiefling')
    await expect(page.locator('.race-details > .race-spells')).toHaveCount(0)
    await page.getByRole('button', { name: /^Потустороннее присутствие/ }).click()
    await page.getByRole('dialog').getByRole('button', { name: 'Чудотворство', exact: true }).click()
    await expect(page.getByRole('dialog')).toHaveCount(2)
    await expect(page.getByRole('dialog').last()).toContainText('Чудотворство')
    await page.getByRole('dialog').last().getByRole('button', { name: 'Закрыть', exact: true }).click()
    await expect(page.getByRole('dialog')).toHaveCount(1)
    await page.getByRole('dialog').getByRole('button', { name: 'Закрыть', exact: true }).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(page.getByText('Не удалось загрузить связанные записи.', { exact: true })).toHaveCount(0)
    const heritage = page.getByRole('region', { name: 'Выбор подрасы' })
    const size = page.getByRole('region', { name: 'Вариант расы' })
    await expect(heritage.locator('.subrace-card')).toHaveCount(3)
    await expect(size.locator('.variant-card')).toHaveCount(2)
    await heritage.getByRole('button', { name: /Наследие Бездны/ }).click()
    await size.getByRole('button', { name: /Маленький/ }).click()
    await expect(page.locator('.race-card-fact').filter({ hasText: 'Размер' })).toContainText('Маленький')
    const spells = heritage.getByRole('region', { name: 'Заклинания происхождения' })
    await expect(spells.getByRole('button', { name: 'Ядовитые брызги', exact: true })).toBeVisible()
    await expect(heritage.getByRole('button', { name: /Магия:/ })).toHaveCount(0)
    await expect(spells).toContainText('С 3-го уровня')
    await expect(spells).toContainText('С 5-го уровня')
    await expect(spells.locator('.handbook-reference-content small')).toHaveCount(0)
    const levelBox = await spells.locator('.race-spell-level').filter({ hasText: 'С 3-го уровня' }).boundingBox()
    const spellBox = await spells.getByRole('button', { name: 'Луч болезни', exact: true }).boundingBox()
    expect(levelBox.x + levelBox.width).toBeLessThan(spellBox.x)
    expect(Math.abs(levelBox.y + levelBox.height / 2 - spellBox.y - spellBox.height / 2)).toBeLessThan(2)
    await spells.getByRole('button', { name: 'Луч болезни', exact: true }).click()
    await expect(page.getByRole('dialog')).toContainText('Луч болезни')
    await page.getByRole('button', { name: 'Закрыть', exact: true }).click()
    await size.getByRole('button', { name: /Средний/ }).click()
    await expect(spells).toContainText('Ядовитые брызги')
    await heritage.getByRole('button', { name: /Инфернальное наследие/ }).click()
    await expect(spells).toContainText('Огненный снаряд')
    await expect(spells).not.toContainText('Ядовитые брызги')
    await expect(page.locator('.race-card-fact').filter({ hasText: 'Размер' })).toContainText('Средний')
    await expect(heritage.getByRole('button', { name: /Магия:/ })).toHaveCount(0)
    await spells.getByRole('button', { name: 'Тьма', exact: true }).click()
    await expect(page.getByRole('dialog')).toContainText('Тьма')
  })
  test(`dragonborn and human do not repeat their wizard choices (${width})`, async ({ page }) => {
    await page.setViewportSize({ width, height: 1000 })
    await page.goto('/tests/species/fixture.html?dragonborn')
    await expect(page.locator('.variant-card')).toHaveCount(10)
    await expect(page.locator('.variant-damage-icon')).toHaveCount(10)
    const red = page.locator('.variant-card').filter({ hasText: 'Красный' })
    await red.getByRole('button').click()
    await expect(red.getByRole('img', { name: 'Тип урона: Огнем' })).toBeVisible()
    await expect(page.getByRole('region', { name: 'Способности расы', exact: true })).not.toContainText('Сопротивление урону')
    await expect(page.getByText('Подробные правила', { exact: true })).toHaveCount(0)
    await expect(page.locator('.variant-size')).toHaveCount(0)
    await expect(page.getByRole('region', { name: 'Способности расы', exact: true })).not.toContainText('Драконье происхождение')
    await page.goto('/tests/species/fixture.html?human')
    const abilities = page.getByRole('region', { name: 'Способности расы', exact: true })
    await expect(abilities).not.toContainText('Универсальность')
    await expect(abilities).not.toContainText('Умелый')
    const request = page.waitForRequest(req => {
      const url = new URL(req.url())
      return url.pathname === '/api/items' && url.searchParams.get('typeId') === '7' && url.searchParams.get('filters')?.includes('origin')
    })
    await page.getByRole('button', { name: 'Выбрать черту' }).click()
    const url = new URL((await request).url())
    expect(JSON.parse(url.searchParams.get('filters'))).toEqual({ category: ['origin'] })
  })
}
