import { expect, test } from '@playwright/test'
test.beforeEach(async ({ page }) => {
  page.on('pageerror', error => { throw error })
  await page.route('**/api/**', route => new URL(route.request().url()).pathname.startsWith('/api/') ? route.fulfill({ json: { items: [] } }) : route.continue())
})
for (const width of [1280, 390]) {
  test(`abilities below cover, lineage benefits and size notes (${width})`, async ({ page }) => {
    await page.setViewportSize({ width, height: 1000 })
    await page.goto('/tests/species/fixture.html')
    const cover = page.locator('.race-card'), list = page.getByRole('region', { name: 'Способности расы' })
    await expect(list.locator('.race-ability-card')).toHaveCount(2)
    await expect(cover).not.toContainText('Способности')
    await expect(cover).toContainText('Гуманоид')
    expect((await list.boundingBox()).y).toBeGreaterThanOrEqual((await cover.boundingBox()).y + (await cover.boundingBox()).height)
    const picker = page.getByRole('region', { name: 'Выбор подрасы' })
    await picker.getByRole('button', { name: /Лесной гном/ }).click()
    await expect(picker.locator('.subrace-details')).toContainText('Малая иллюзия лесного гнома')
    await expect(picker.locator('.subrace-details')).not.toContainText('Заводное устройство')
    await picker.getByRole('button', { name: /Скальный гном/ }).click()
    await expect(picker.locator('.subrace-details')).toContainText('Заводное устройство')
    await expect(picker.locator('.subrace-details')).not.toContainText('Малая иллюзия лесного гнома')
    await expect(picker.locator('.race-ability-card p')).toHaveCount(0)
    await list.getByRole('button', { name: /Гномья хитрость/ }).click()
    await expect(page.getByRole('dialog')).toContainText('спасброски Интеллекта')
    await page.getByRole('button', { name: 'Закрыть', exact: true }).click()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  })
  for (const title of ['Раса', 'Класс', 'Предыстория']) {
    test(`back beside ${title} heading (${width})`, async ({ page }) => {
      await page.setViewportSize({ width, height: 900 })
      await page.goto('/tests/species/fixture.html?stage=' + encodeURIComponent(title))
      const heading = await page.getByRole('heading', { name: title, exact: true }).boundingBox()
      const back = page.getByRole('button', { name: /Назад/ })
      const button = await back.boundingBox(), cover = await page.locator('.fixture-cover').boundingBox()
      expect(button.x).toBeGreaterThan(heading.x + heading.width)
      expect(button.y + button.height).toBeLessThanOrEqual(cover.y)
      await back.click()
      await expect(back).toHaveCount(0)
    })
  }
}
test('future abilities are visible with level labels; size choices retain explanatory heights', async ({ page }) => {
  await page.goto('/tests/species/fixture.html?aasimar')
  await expect(page.locator('.race-ability-card')).toHaveCount(5)
  await expect(page.locator('.race-ability-card').filter({ hasText: 'Небесное откровение' })).toContainText('С 3-го уровня')
  await page.getByRole('button', { name: /Маленький Выбрать/ }).click()
  await expect(page.locator('.race-card-fact').filter({ hasText: 'Размер' })).toContainText('Маленький')
  await expect(page.locator('.variant-card').filter({ hasText: 'Маленький' })).toContainText('2–4 футов')
  await expect(page.locator('.race-lore')).not.toContainText('Тип существа:')
  await expect(page.locator('.race-lore')).not.toContainText('Скорость:')
})
